import type { CurriculumCourse } from "@/types/curriculum";

export const curriculumCourses: CurriculumCourse[] = [
  { id: "developer-foundations", title: "Developer Foundations", description: "เข้าใจคอมพิวเตอร์ ไฟล์ terminal process error และ Git ก่อนพึ่ง framework", track: "foundation", status: "live", targetSteps: 48 },
  { id: "java-foundations", title: "Java Foundations", description: "JDK 21 ตั้งแต่ compile/run, ชนิดข้อมูล, String, Scanner, if/switch, loops, methods, arrays, ArrayList, exception เบื้องต้น และโปรแกรมหลายไฟล์ พร้อม Library CLI M0", track: "java", status: "live", targetSteps: 90 },
  { id: "java-oop", title: "Java OOP", description: "ออกแบบจากความรับผิดชอบ: class, constructor, identity, encapsulation, composition, interfaces, polymorphism, inheritance, collections, exceptions, refactoring และ JUnit พร้อม Library CLI M1–M3 และ RPG Battle CLI", track: "java", status: "live", targetSteps: 105 },
  { id: "javascript-foundations", title: "JavaScript Foundations", description: "ภาษาและการแก้ปัญหา: values, conditions, functions, loops, arrays/objects, references, callbacks, errors และ async พร้อม Activity Planner M1–M2", track: "web", status: "live", targetSteps: 100 },
  { id: "node-foundations", title: "Node.js Fundamentals", description: "runtime, process/CLI, modules, npm, files, event loop, streams, HTTP และ node:test พร้อม Activity Planner M4 ", track: "web", status: "live", targetSteps: 50 },
  { id: "backend", title: "Back-end Development", description: "REST design, Express 5, validation, middleware, error handling, SQL/PostgreSQL, transactions, authentication, authorization, security และ API testing พร้อม Activity Planner M5–M7", track: "web", status: "live", targetSteps: 85 },
  { id: "typescript", title: "TypeScript Foundations → Intermediate", description: "Type Observatory: types, functions, object types, unions, narrowing, null safety, generics, utility types, classes, tsconfig และข้อมูลจาก API พร้อม Activity Planner M3", track: "web", status: "live", targetSteps: 70 },
  { id: "react", title: "React Foundations", description: "วางแผนไว้ ต่อจาก JavaScript Foundations และ TypeScript: components, props, state, forms, effects และ accessibility โดยสร้างหน้า UI ของ Activity Planner", track: "web", status: "planned", targetSteps: 84 },
  { id: "nextjs", title: "Next.js App Router", description: "วางแผนไว้ ต่อจาก React: App Router, Server/Client Components, data fetching, cache และ loading/error states ที่เชื่อมกับ Planner API", track: "web", status: "planned", targetSteps: 60 },
  { id: "postgres", title: "PostgreSQL Deep Dive", description: "วางแผนไว้ ต่อจาก Back-end Development (ซึ่งสอน SQL, constraint, JOIN และ transaction แล้ว): index, query plan, migration tool และการใช้ ORM อย่างรู้เท่าทัน", track: "web", status: "planned", targetSteps: 84 },
];
