import type { TopicSource } from "@/types/curriculum";

import { javascriptBridgeTopics } from "./javascript-bridges";
import { javascriptCheckpoints } from "./javascript-checkpoints";
import { javascriptStartTopic } from "./javascript-start";

const courseId = "javascript-foundations";
const v = (a: string, b: string): [string, string] => [a, b];

// Order is the learning order. Topic IDs are stored in learner progress: never rename them.
const originalTopics: TopicSource[] = [
{
  id: "js-runtime",
  courseId,
  unit: "รันโค้ดและอ่านผล",
  title: "JavaScript engine และลำดับการทำงาน",
  objective: "ทำนายลำดับ output ของโค้ด synchronous ที่มีการเรียก function ซ้อนกัน โดยใช้แนวคิด call stack",
  why: "บั๊กจำนวนมากเกิดจากคิดว่าโค้ดทำงาน “พร้อมกัน” หรือ “ตามลำดับที่เขียนไฟล์” ทั้งที่จริงทำตามลำดับการเรียก การ trace ได้คือพื้นฐานของการอ่านโค้ดคนอื่นและ debug",
  explanation: "JavaScript engine อ่านโค้ดแล้วรันทีละคำสั่งบน call stack เมื่อเรียก function จะวางกรอบ (frame) ใหม่ทับไว้บนสุด ทำจนเสร็จแล้วค่อยถอดออกและกลับมาทำต่อที่จุดเรียก โค้ดแบบนี้เรียกว่า synchronous ส่วน browser หรือ Node เป็น runtime ที่เพิ่มความสามารถรอบตัวภาษา เช่น console, timer, fetch",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-functions"],
  example: "function makeTea() {\n  console.log(\"2) ต้มน้ำ\");\n  pour();\n  console.log(\"4) ยกเสิร์ฟ\");\n}\n\nfunction pour() {\n  console.log(\"3) เทน้ำลงแก้ว\");\n}\n\nconsole.log(\"1) รับออร์เดอร์\");\nmakeTea();\nconsole.log(\"5) ปิดบิล\");",
  expectedOutput: "1) รับออร์เดอร์\n2) ต้มน้ำ\n3) เทน้ำลงแก้ว\n4) ยกเสิร์ฟ\n5) ปิดบิล",
  tracePrompt: "ก่อนรัน: เขียนว่า call stack มีอะไรอยู่บ้าง ตอนที่บรรทัด “3) เทน้ำลงแก้ว” ถูกพิมพ์ และทำไม function pour ที่ประกาศทีหลังจึงเรียกได้",
  traceAnswer: "ตอนพิมพ์ “3)” stack (ล่างขึ้นบน) คือ โค้ดระดับบนสุด → makeTea → pour เมื่อ pour จบจะถูกถอดออก แล้ว makeTea ทำต่อที่บรรทัด “4)” การประกาศ function ด้วย function declaration ถูกเตรียมไว้ก่อนรันโค้ดในไฟล์ (hoisting) จึงเรียก pour ได้แม้ประกาศทีหลัง",
  practicePrompt: "เพิ่ม function addSugar() ที่พิมพ์ “3.5) ใส่น้ำตาล” แล้วเรียกจาก pour หลังพิมพ์ “3)” จากนั้นทำนายลำดับทั้งหมดก่อนกด Run",
  starter: "function makeTea() {\n  console.log(\"2) ต้มน้ำ\");\n  pour();\n  console.log(\"4) ยกเสิร์ฟ\");\n}\n\nfunction pour() {\n  console.log(\"3) เทน้ำลงแก้ว\");\n  // เรียก addSugar ที่นี่\n}\n\n// ประกาศ addSugar ที่นี่\n\nconsole.log(\"1) รับออร์เดอร์\");\nmakeTea();\nconsole.log(\"5) ปิดบิล\");",
  solution: "function makeTea() {\n  console.log(\"2) ต้มน้ำ\");\n  pour();\n  console.log(\"4) ยกเสิร์ฟ\");\n}\n\nfunction pour() {\n  console.log(\"3) เทน้ำลงแก้ว\");\n  addSugar();\n}\n\nfunction addSugar() {\n  console.log(\"3.5) ใส่น้ำตาล\");\n}\n\nconsole.log(\"1) รับออร์เดอร์\");\nmakeTea();\nconsole.log(\"5) ปิดบิล\");",
  buggy: "function serve() {\n  console.log(\"เสิร์ฟ\");\n  serve();\n}\n\nserve();",
  bugExplanation: "serve เรียกตัวเองโดยไม่มีเงื่อนไขหยุด แต่ละการเรียกวาง frame ใหม่บน call stack จน stack เต็มและเกิด RangeError: Maximum call stack size exceeded แก้โดยลบการเรียกซ้ำ หรือถ้าตั้งใจให้ทำซ้ำ ต้องมีเงื่อนไขหยุด เช่นรับจำนวนรอบเป็น parameter แล้ว if (rounds === 0) return;",
  vocabulary: [v("engine", "ส่วนที่อ่านและรันโค้ด JavaScript เช่น V8"), v("runtime", "สภาพแวดล้อมที่ engine ทำงานอยู่ เช่น browser หรือ Node พร้อม API เสริม"), v("call stack", "กองบันทึกว่ากำลังอยู่ใน function ไหน เรียกใหม่วางทับ จบแล้วถอดออก"), v("synchronous", "ทำทีละงาน งานถัดไปรอจนงานก่อนเสร็จ"), v("hoisting", "การที่ function declaration ถูกเตรียมไว้ก่อนรันโค้ดในขอบเขตนั้น")],
},
{
  id: "js-values",
  courseId,
  unit: "ค่าและตัวแปร",
  title: "values, types และ typeof",
  objective: "จำแนกชนิดของค่าด้วย typeof และทำนายผลของ operator เมื่อชนิดต่างกัน",
  why: "JavaScript ตัดสินพฤติกรรมจากชนิดของค่าตอนรัน ค่าจากฟอร์มหรือ URL เป็น string เสมอ ถ้าไม่รู้ชนิดจะเจอ \"5\" + 1 ได้ \"51\" ในหน้าคิดเงิน",
  explanation: "ค่าพื้นฐานที่ใช้บ่อยคือ string (ข้อความ), number (ตัวเลข), boolean (true/false), undefined (ยังไม่ได้กำหนด) และ null (ตั้งใจไม่มีค่า) typeof คืนชื่อชนิดเป็นข้อความ เช่น typeof 25 ได้ \"number\" แต่ typeof null ได้ \"object\" เป็นข้อยกเว้นเก่าของภาษา ไม่ได้แปลว่า null เป็น object ข้อมูลเป็นกลุ่มจะเรียนในบท arrays และ objects",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-start"],
  example: "console.log(typeof \"25\", typeof 25);\nconsole.log(\"25\" + 1);\nconsole.log(\"25\" - 1);\nconsole.log(typeof null);\nconsole.log(typeof true);",
  expectedOutput: "string number\n251\n24\nobject\nboolean",
  tracePrompt: "ทำนายแต่ละบรรทัดก่อนรัน แล้วอธิบายว่าทำไม \"25\" + 1 กับ \"25\" - 1 ได้ผลคนละแบบ",
  traceAnswer: "string number / 251 / 24 / object / boolean — + เมื่อมี string ฝั่งหนึ่งต่อข้อความ ส่วน - แปลงข้อความเป็นตัวเลขแล้วลบ การแปลงอัตโนมัติเรียก type coercion; typeof null เป็นข้อยกเว้นที่ต้องระวัง",
  practicePrompt: "ค่าทั้งสามด้านล่างมาจากฟอร์มทั้งหมด แปลง quantity และ price เป็นตัวเลขด้วย Number() แล้วพิมพ์ 2 บรรทัด: บรรทัดแรก typeof ของ quantity หลังแปลง บรรทัดที่สองราคารวม (quantity × price) ตามด้วย \" บาท\" — ห้ามพิมพ์ตัวเลขคำตอบเอง",
  starter: "const quantity = \"3\";\nconst price = \"45\";\n\n// แปลงเป็นตัวเลข แล้วพิมพ์ typeof และราคารวม\nconsole.log(typeof quantity);\nconsole.log(quantity * price + \" บาท\");",
  solution: "const quantity = \"3\";\nconst price = \"45\";\n\nconst count = Number(quantity);\nconst each = Number(price);\nconsole.log(typeof count);\nconsole.log(count * each + \" บาท\");",
  outputCheck: {
    expected: "number\n135 บาท",
    wrongAnswers: [
      "const quantity = \"3\";\nconst price = \"45\";\nconsole.log(typeof quantity);\nconsole.log(Number(quantity) * Number(price) + \" บาท\");",
      "const quantity = \"3\";\nconst price = \"45\";\nconst count = Number(quantity);\nconsole.log(typeof count);\nconsole.log(quantity + price + \" บาท\");",
    ],
  },
  buggy: "const price = \"120\";\nconst shipping = 30;\nconsole.log(\"ยอดรวม\", price + shipping);",
  bugExplanation: "ได้ “ยอดรวม 12030” เพราะ price เป็น string การใช้ + กับ string จะต่อข้อความ แก้โดยแปลงเป็น number ก่อนบวก: Number(price) + shipping ได้ 150 — ค่าที่มาจากฟอร์มหรือ URL ต้องแปลงชนิดก่อนคำนวณเสมอ",
  vocabulary: [v("value", "ข้อมูลหนึ่งชิ้น เช่น 25 หรือ \"ซี\""), v("type", "ชนิดของค่า กำหนดว่าทำอะไรกับค่านั้นได้"), v("primitive", "ค่าพื้นฐานที่ไม่ใช่ object เช่น string number boolean undefined null"), v("typeof", "operator ที่คืนชื่อชนิดเป็น string"), v("type coercion", "การที่ JavaScript แปลงชนิดให้อัตโนมัติ")],
},
{
  id: "js-variables",
  courseId,
  unit: "ค่าและตัวแปร",
  title: "const, let และ assignment",
  objective: "เลือก const หรือ let ตามการเปลี่ยนค่า ไล่ assignment และระบุขอบเขตของชื่อใน block ได้",
  why: "ตัวแปรที่เปลี่ยนค่าได้ทุกที่ทำให้ตามไม่ทันว่าค่าปัจจุบันมาจากไหน การจำกัดด้วย const ทำให้อ่านโค้ดแล้วรู้ทันทีว่าอะไรคงที่",
  explanation: "const ประกาศชื่อพร้อมค่าตั้งต้นแล้ว assign ใหม่ไม่ได้ let ผูกค่าใหม่ได้ assignment (=) คำนวณทางขวาก่อนใส่ชื่อทางซ้าย -= เป็นรูปย่อของการลบแล้ว assign เช่น budget -= 150 เท่ากับ budget = budget - 150; { } ครอบกลุ่มคำสั่งเรียกว่า block ชื่อที่ประกาศข้างในมองเห็นเฉพาะข้างใน นี่คือ block scope",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-values"],
  example: "const friends = 4;\nlet budget = 1000;\nbudget = budget - 250;\nbudget -= 150;\n{\n  const note = \"งบหลังหัก\";\n  console.log(note, budget);\n}\nconsole.log(friends, budget);",
  expectedOutput: "งบหลังหัก 600\n4 600",
  tracePrompt: "ทำนาย output และบอกว่าถ้าเพิ่มบรรทัด console.log(note) ไว้ท้ายไฟล์ จะเกิดอะไรขึ้น ทำไม",
  traceAnswer: "งบหลังหัก 600 / 4 600 — 1000 − 250 − 150 = 600; note ใช้ได้ใน { } เท่านั้น เพิ่ม console.log(note) ท้ายไฟล์ได้ ReferenceError เพราะอยู่นอก block",
  practicePrompt: "เขียนโปรแกรมเล็ก ๆ: เริ่มงบ 1500 บาท ใช้ const สำหรับราคาที่พัก 900 และราคาอาหาร 350 ใช้ let สำหรับเงินคงเหลือ แล้วพิมพ์เงินคงเหลือหลังหักทีละรายการ",
  starter: "// ประกาศงบเริ่มต้น ราคาที่พัก และราคาอาหาร\n// เลือกว่าตัวไหนควรเป็น const ตัวไหนควรเป็น let\n\n// หักที่พัก แล้วพิมพ์ยอดคงเหลือ\n\n// หักอาหาร แล้วพิมพ์ยอดคงเหลือ",
  solution: "const lodging = 900;\nconst food = 350;\nlet remaining = 1500;\n\nremaining = remaining - lodging;\nconsole.log(\"หลังจ่ายที่พัก\", remaining);\n\nremaining = remaining - food;\nconsole.log(\"หลังจ่ายอาหาร\", remaining);",
  outputCheck: {
    expected: "หลังจ่ายที่พัก 600\nหลังจ่ายอาหาร 250",
    wrongAnswers: [
      "const lodging = 900;\nconst food = 350;\nlet remaining = 1500;\nconsole.log(\"หลังจ่ายที่พัก\", remaining - lodging);\nconsole.log(\"หลังจ่ายอาหาร\", remaining - food);",
    ],
  },
  buggy: "const total = 120;\ntotal = total + 80;\nconsole.log(total);",
  bugExplanation: "คาด 200 แต่ TypeError: Assignment to constant variable เพราะ assign ใหม่ให้ const ถ้า total ต้องเปลี่ยนให้ประกาศ let total = 120; อีกทางคือ const combined = total + 80; แล้วพิมพ์ combined ทดลองยืนยัน output 200",
  vocabulary: [v("variable", "ชื่อที่ผูกกับค่า"), v("const", "ประกาศชื่อที่ assign ใหม่ไม่ได้"), v("let", "ประกาศชื่อที่ assign ใหม่ได้"), v("assignment", "การใส่ค่าทางขวาให้ชื่อทางซ้ายด้วย ="), v("block scope", "ขอบเขตที่มองเห็นตัวแปรได้เฉพาะใน { } ที่ประกาศ")],
},
{
  id: "js-strings",
  courseId,
  unit: "ค่าและตัวแปร",
  title: "string, template literal และ string methods",
  objective: "สร้างข้อความจากข้อมูลด้วย template literal และใช้ trim, toLowerCase, includes, slice แปลงข้อความโดยไม่แก้ค่าเดิม",
  why: "ชื่อผู้ใช้ อีเมล ข้อความค้นหา และข้อความแจ้งเตือนในเว็บล้วนเป็น string การทำความสะอาดและเทียบข้อความให้ถูกช่วยกันบั๊ก เช่นค้นคำว่า “Java” แล้วไม่เจอ “java”",
  explanation: "string คือลำดับตัวอักษร เข้าถึงตัวที่ index ได้และมี length string เปลี่ยนแปลงไม่ได้ (immutable): method อย่าง trim หรือ toUpperCase คืน string ใหม่เสมอ template literal ใช้ backtick และแทรกค่าด้วย ${...} อ่านง่ายกว่าการต่อด้วย +",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-variables"],
  example: "const rawName = \"  Sea Kanok  \";\nconst name = rawName.trim();\nconst first = name.slice(0, 3);\n\nconsole.log(`[${rawName}] → [${name}]`);\nconsole.log(name.length, first);\nconsole.log(name.toLowerCase().includes(\"sea\"));\nconsole.log(rawName.length);",
  expectedOutput: "[  Sea Kanok  ] → [Sea Kanok]\n9 Sea\ntrue\n13",
  tracePrompt: "ทำนายทุกบรรทัด และอธิบายว่าทำไมบรรทัดสุดท้าย rawName.length ยังเป็น 13 ทั้งที่เรียก trim ไปแล้ว",
  traceAnswer: "[  Sea Kanok  ] → [Sea Kanok] / 9 Sea / true / 13 — trim ไม่ได้แก้ rawName แต่คืน string ใหม่ที่เก็บใน name เพราะ string เป็น immutable rawName ยังมีช่องว่างหน้า 2 หลัง 2 รวม 13 ตัว slice(0, 3) เอา index 0–2 (ไม่รวม 3)",
  practicePrompt: "ตัวแปร rawTag มาจากช่องพิมพ์ tag ของกิจกรรม ทำให้เป็นรูปแบบมาตรฐาน: ตัดช่องว่างหัวท้าย ทำเป็นตัวพิมพ์เล็ก แล้วแทนช่องว่างระหว่างคำด้วย - จากนั้นพิมพ์ผลลัพธ์ และพิมพ์ความยาวของผลลัพธ์ในบรรทัดถัดไป (ห้ามพิมพ์คำตอบเอง)",
  starter: "const rawTag = \"  Night Market Tour \";\n\n// 1) ตัดช่องว่างหัวท้าย  2) ตัวพิมพ์เล็ก  3) แทนช่องว่างด้วย -\nconst tag = rawTag;\nconsole.log(tag);\nconsole.log(tag.length);",
  solution: "const rawTag = \"  Night Market Tour \";\n\nconst tag = rawTag.trim().toLowerCase().replaceAll(\" \", \"-\");\nconsole.log(tag);\nconsole.log(tag.length);",
  outputCheck: {
    expected: "night-market-tour\n17",
    wrongAnswers: [
      "const rawTag = \"  Night Market Tour \";\nconst tag = rawTag.toLowerCase().replaceAll(\" \", \"-\");\nconsole.log(tag);\nconsole.log(tag.length);",
      "const rawTag = \"  Night Market Tour \";\nconst tag = rawTag.trim().toLowerCase().replace(\" \", \"-\");\nconsole.log(tag);\nconsole.log(tag.length);",
    ],
  },
  buggy: "const email = \"  Sea@Example.com \";\nemail.trim();\nemail.toLowerCase();\nconsole.log(email === \"sea@example.com\");",
  bugExplanation: "ได้ false เพราะ trim และ toLowerCase คืน string ใหม่แต่ไม่ได้เก็บไว้ email จึงยังเป็นค่าเดิม แก้โดยเก็บผล: const cleaned = email.trim().toLowerCase(); แล้วเทียบ cleaned — method ของ string ไม่แก้ค่าเดิม",
  vocabulary: [v("string", "ลำดับตัวอักษร"), v("index", "ตำแหน่งของตัวอักษร เริ่มนับที่ 0"), v("immutable", "เปลี่ยนแปลงค่าเดิมไม่ได้ ต้องสร้างค่าใหม่"), v("template literal", "string ที่ใช้ backtick และแทรกค่าด้วย ${...}"), v("method", "function ที่ผูกกับค่า เรียกด้วยจุด เช่น name.trim()")],
},
{
  id: "js-numbers",
  courseId,
  unit: "ค่าและตัวแปร",
  title: "number, การคำนวณ และการแปลงจากข้อความ",
  objective: "คำนวณด้วย operator พื้นฐาน แปลง string เป็น number อย่างปลอดภัย และตรวจ NaN ด้วย Number.isNaN",
  why: "ราคา จำนวนคน และคะแนนที่รับจากผู้ใช้มาเป็นข้อความ ถ้าแปลงไม่ถูกหรือไม่ตรวจค่าที่ไม่ใช่ตัวเลข ยอดรวมจะกลายเป็น NaN แล้วลามไปทั้งหน้า",
  explanation: "JavaScript ใช้ชนิด number ชนิดเดียวทั้งจำนวนเต็มและทศนิยม operator ที่ใช้บ่อยคือ + - * / และ % (เศษจากการหาร) Number(\"42\") แปลงข้อความทั้งก้อน ถ้าแปลงไม่ได้ได้ NaN (Not a Number) ซึ่งเป็นชนิด number แต่ไม่เท่ากับอะไรเลยแม้แต่ตัวเอง จึงต้องตรวจด้วย Number.isNaN ทศนิยมบางค่าเก็บไม่ตรงเป๊ะ เช่น 0.1 + 0.2 เงินจึงมักคำนวณเป็นหน่วยสตางค์ (จำนวนเต็ม ซึ่งตรงเสมอในช่วงที่ปลอดภัย คือไม่เกิน Number.MAX_SAFE_INTEGER)",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-variables"],
  example: "console.log(17 % 5, 7 / 2);\nconsole.log(Number(\"42\") + 8);\nconsole.log(Number(\"42 บาท\"));\nconsole.log(Number.isNaN(Number(\"abc\")));\nconsole.log(0.1 + 0.2);\nconsole.log((10 + 20) / 100);",
  expectedOutput: "2 3.5\n50\nNaN\ntrue\n0.30000000000000004\n0.3",
  tracePrompt: "ทำนายทุกบรรทัด โดยเฉพาะ Number(\"42 บาท\") และ 0.1 + 0.2 แล้วอธิบายว่าบรรทัดสุดท้ายแก้ปัญหาทศนิยมอย่างไร",
  traceAnswer: "2 3.5 / 50 / NaN / true / 0.30000000000000004 / 0.3 — Number ต้องแปลงได้ทั้งข้อความ \"42 บาท\" มีตัวอักษรจึงได้ NaN ส่วน 0.1 กับ 0.2 เก็บในเลขฐานสองไม่ตรงเป๊ะจึงคลาดเล็กน้อย บรรทัดสุดท้ายคิดเป็นสตางค์ 10 + 20 = 30 (จำนวนเต็มขนาดนี้คำนวณได้ตรง) แล้วค่อยหาร 100",
  practicePrompt: "ราคาสามช่องด้านล่างมาจากฟอร์ม สำหรับแต่ละช่องให้พิมพ์บรรทัดละช่อง: ผลแปลงด้วย Number() ตามด้วยผลของ Number.isFinite(ผลแปลงนั้น) คั่นด้วยช่องว่าง (console.log รับหลายค่าได้) — ห้ามพิมพ์คำตอบเอง",
  starter: "const first = \" 59.5 \";\nconst second = \"120 บาท\";\nconst third = \"Infinity\";\n\n// พิมพ์ผลแปลงและผลตรวจว่าเป็นจำนวนจำกัดไหม\nconsole.log(first);\nconsole.log(second);\nconsole.log(third);",
  solution: "const first = \" 59.5 \";\nconst second = \"120 บาท\";\nconst third = \"Infinity\";\n\nconst a = Number(first);\nconst b = Number(second);\nconst c = Number(third);\nconsole.log(a, Number.isFinite(a));\nconsole.log(b, Number.isFinite(b));\nconsole.log(c, Number.isFinite(c));",
  outputCheck: {
    expected: "59.5 true\nNaN false\nInfinity false",
    wrongAnswers: [
      "for (const t of [\" 59.5 \", \"120 บาท\", \"Infinity\"]) { const n = parseFloat(t); console.log(n, Number.isFinite(n)); }",
      "for (const t of [\" 59.5 \", \"120 บาท\", \"Infinity\"]) { const n = Number(t); console.log(n, !Number.isNaN(n)); }",
    ],
  },
  buggy: "const input = \"abc\";\nconst price = Number(input);\nif (price === NaN) {\n  console.log(\"ราคาไม่ถูกต้อง\");\n} else {\n  console.log(\"ราคา\", price);\n}",
  bugExplanation: "พิมพ์ “ราคา NaN” เพราะ NaN ไม่เท่ากับอะไรเลยแม้แต่ NaN ด้วยกัน เงื่อนไข price === NaN จึงเป็น false เสมอ แก้เป็น if (Number.isNaN(price))",
  vocabulary: [v("number", "ชนิดข้อมูลตัวเลขทั้งจำนวนเต็มและทศนิยม"), v("% (remainder)", "เศษจากการหาร"), v("NaN", "ค่า Not a Number ได้จากการแปลง/คำนวณที่ไม่สำเร็จ"), v("Number.isNaN", "ตรวจว่าค่าเป็น NaN จริงหรือไม่"), v("floating point", "วิธีเก็บทศนิยมแบบฐานสองที่ทำให้บางค่าคลาดเล็กน้อย")],
},
{
  id: "js-conditions",
  courseId,
  unit: "ตัดสินใจ",
  title: "comparison, logical operators และ if/else",
  objective: "เขียนเงื่อนไขด้วย ===, &&, ||, ! และ if/else if/else ที่ครอบคลุมทุกกรณี พร้อมอธิบาย truthy/falsy",
  why: "ทุกกฎทางธุรกิจคือเงื่อนไข: เข้าร่วมกิจกรรมได้ไหม ส่วนลดเท่าไร ฟอร์มผ่านหรือไม่ เงื่อนไขที่ลำดับผิดหรือใช้ == จะให้สิทธิ์คนที่ไม่ควรได้",
  explanation: "comparison คืนค่า boolean: === เทียบทั้งค่าและชนิด (\"5\" === 5 เป็น false) ส่วน == แปลงชนิดก่อนจึงคาดเดายาก ให้ใช้ === เสมอ && ต้องจริงทั้งคู่ || จริงอย่างน้อยหนึ่ง ! กลับค่า if/else if/else ตรวจจากบนลงล่างและทำเฉพาะกิ่งแรกที่จริง ค่าที่เป็น falsy ได้แก่ false, 0, \"\", null, undefined, NaN นอกนั้น truthy",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-values", "js-numbers"],
  example: "const age = 20;\nconst isStudent = true;\n\nlet price;\nif (age < 0) {\n  price = null;\n} else if (age < 12) {\n  price = 50;\n} else if (isStudent || age >= 60) {\n  price = 80;\n} else {\n  price = 120;\n}\nconsole.log(\"ราคา\", price);\n\nconst joined = 9;\nconst capacity = 9;\nconsole.log(joined < capacity, joined <= capacity);\nconsole.log(\"5\" === 5, \"5\" == 5);",
  expectedOutput: "ราคา 80\nfalse true\nfalse true",
  tracePrompt: "ก่อนรัน: ถ้าเปลี่ยนเป็น age = 10 และ isStudent = true จะได้ราคาไหน และถ้าสลับให้เช็ก isStudent ก่อน age < 12 ผลจะเปลี่ยนอย่างไร",
  traceAnswer: "ได้ 50 เพราะ if/else if ตรวจจากบนลงล่างและหยุดที่กิ่งแรกที่จริง age < 12 จริงก่อน ถ้าสลับให้เช็ก isStudent ก่อน เด็กนักเรียนจะได้ 80 ซึ่งแพงกว่าราคาเด็ก — ลำดับเงื่อนไขคือส่วนหนึ่งของกฎ ส่วนบรรทัด joined < capacity เป็น false เมื่อเท่ากันพอดี (เต็มแล้ว)",
  practicePrompt: "กิจกรรมด้านล่างรับ 9 คนและต้องอายุ 18 ขึ้นไป เขียนเงื่อนไขสำหรับสมาชิกสามคน (ซี ต้น ฝน) แล้วพิมพ์บรรทัดละคนว่า “ชื่อ: เข้าร่วมได้” หรือ “ชื่อ: เข้าร่วมไม่ได้” โดยเข้าร่วมได้เมื่อยังมีที่นั่ง อายุถึง และไม่ถูกแบน — สังเกตว่าต้องเขียนเงื่อนไขซ้ำสามครั้ง (บทถัดไปจะแก้ด้วย function)",
  starter: "const capacity = 9;\nconst joined = 8;\nconst minAge = 18;\n\nconst seaAge = 18;\nconst seaBanned = false;\nconst tonAge = 17;\nconst tonBanned = false;\nconst fonAge = 25;\nconst fonBanned = true;\n\n// แทน false ด้วยเงื่อนไขจริงของแต่ละคน\nconst seaCanJoin = false;\nconsole.log(\"ซี: \" + (seaCanJoin ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));",
  solution: "const capacity = 9;\nconst joined = 8;\nconst minAge = 18;\n\nconst seaAge = 18;\nconst seaBanned = false;\nconst tonAge = 17;\nconst tonBanned = false;\nconst fonAge = 25;\nconst fonBanned = true;\n\nconst hasSeat = joined < capacity;\nconst seaCanJoin = hasSeat && seaAge >= minAge && !seaBanned;\nconst tonCanJoin = hasSeat && tonAge >= minAge && !tonBanned;\nconst fonCanJoin = hasSeat && fonAge >= minAge && !fonBanned;\n\nconsole.log(\"ซี: \" + (seaCanJoin ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));\nconsole.log(\"ต้น: \" + (tonCanJoin ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));\nconsole.log(\"ฝน: \" + (fonCanJoin ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));",
  outputCheck: {
    expected: "ซี: เข้าร่วมได้\nต้น: เข้าร่วมไม่ได้\nฝน: เข้าร่วมไม่ได้",
    wrongAnswers: [
      "const capacity = 9; const joined = 8; const minAge = 18; const seaAge = 18; const seaBanned = false; const tonAge = 17; const tonBanned = false; const fonAge = 25; const fonBanned = true;\nconsole.log(\"ซี: \" + (seaAge > minAge && !seaBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ต้น: \" + (tonAge > minAge && !tonBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ฝน: \" + (fonAge > minAge && !fonBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));",
      "const capacity = 9; const joined = 8; const minAge = 18; const seaAge = 18; const seaBanned = false; const tonAge = 17; const tonBanned = false; const fonAge = 25; const fonBanned = true;\nconsole.log(\"ซี: \" + (joined < capacity && seaAge >= minAge ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ต้น: \" + (joined < capacity && tonAge >= minAge ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ฝน: \" + (joined < capacity && fonAge >= minAge ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));",
      "const capacity = 9; const joined = 8; const minAge = 18; const seaAge = 18; const seaBanned = false; const tonAge = 17; const tonBanned = false; const fonAge = 25; const fonBanned = true;\nconsole.log(\"ซี: \" + (joined < capacity || seaAge >= minAge && !seaBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ต้น: \" + (joined < capacity || tonAge >= minAge && !tonBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\")); console.log(\"ฝน: \" + (joined < capacity || fonAge >= minAge && !fonBanned ? \"เข้าร่วมได้\" : \"เข้าร่วมไม่ได้\"));",
    ],
  },
  buggy: "const total = 800;\nlet shipping;\nif (total > 0) {\n  shipping = 50;\n} else if (total >= 500) {\n  shipping = 0;\n} else {\n  shipping = 50;\n}\nconsole.log(\"ค่าส่ง\", shipping);",
  bugExplanation: "ได้ค่าส่ง 50 ทั้งที่ยอด 800 ควรส่งฟรี เพราะเงื่อนไขกว้าง total > 0 อยู่ก่อนและจริงสำหรับทุกยอด กิ่ง total >= 500 จึงไม่เคยถูกตรวจ แก้โดยเรียงเงื่อนไขที่เฉพาะเจาะจงกว่าไว้ก่อน: if (total >= 500) shipping = 0; else shipping = 50;",
  vocabulary: [v("boolean", "ค่า true หรือ false"), v("===", "เท่ากันทั้งค่าและชนิด"), v("&& / || / !", "และ / หรือ / ไม่"), v("truthy / falsy", "ค่าที่ถูกมองเป็นจริง/เท็จเมื่ออยู่ในเงื่อนไข"), v("branch", "กิ่งของ if/else ที่ถูกเลือกทำ")],
},
{
  id: "js-functions",
  courseId,
  unit: "Functions",
  title: "function input, output และ pure behavior",
  objective: "เขียน function ที่รับ input ผ่าน parameter คืนผลด้วย return และอธิบายได้ว่าทำไม pure function ทดสอบง่าย",
  why: "การคำนวณราคา ตรวจฟอร์ม และจัดรูปแบบข้อความในเว็บจริงเขียนเป็น function ที่ return ค่า แล้วให้ส่วนอื่นนำไปแสดงหรือบันทึก ถ้าแยกไม่ออกระหว่าง return กับ console.log จะได้ undefined โผล่ในหน้าเว็บ",
  explanation: "function คือชุดคำสั่งที่ตั้งชื่อไว้ รับค่าเข้าทาง parameter และส่งผลกลับด้วย return การประกาศยังไม่ทำงานจนกว่าจะถูกเรียก return ส่งค่ากลับแล้วจบ function ทันที ส่วน console.log แค่แสดงผล pure function คำนวณจาก input เท่านั้นและไม่มี side effect",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-function-basics", "js-numbers"],
  example: "function splitCost(total, people) {\n  const share = total / people;\n  return Math.ceil(share);\n}\n\nconst perPerson = splitCost(1250, 4);\nconsole.log(perPerson);\nconsole.log(splitCost(900, 3));\nconsole.log(splitCost(100, 3) * 3);",
  expectedOutput: "313\n300\n102",
  tracePrompt: "ก่อนกด Run: ทำนาย output ทั้งสามบรรทัด และบอกว่าตัวแปร perPerson เก็บค่าอะไร ทำไมบรรทัดสุดท้ายจึงไม่ได้ 100",
  traceAnswer: "313, 300, 102 — perPerson เก็บ 313 เพราะ 1250 / 4 = 312.5 แล้ว Math.ceil ปัดขึ้น บรรทัดสุดท้าย splitCost(100, 3) ได้ Math.ceil(33.33…) = 34 แล้ว × 3 = 102 ไม่ใช่ 100 เพราะปัดขึ้นก่อนคูณ",
  practicePrompt: "เขียน costPerPerson(total, people, tipPercent) ที่คืนยอดต่อคนแบบปัดขึ้นหลังรวมทิปเป็นเปอร์เซ็นต์ และคืน null เมื่อจำนวนคนน้อยกว่าหรือเท่ากับ 0 จากนั้นกด Run tests",
  starter: "function costPerPerson(total, people, tipPercent) {\n  // 1) ถ้าจำนวนคนเป็นไปไม่ได้ ให้คืน null\n  // 2) คำนวณยอดรวมทิป\n  // 3) หารแล้วปัดขึ้น\n  return 0;\n}\n\nconsole.log(costPerPerson(1000, 4, 10)); // ควรได้ 275",
  solution: "function costPerPerson(total, people, tipPercent) {\n  if (people <= 0) return null;\n  const tip = total * tipPercent / 100;\n  const grandTotal = total + tip;\n  return Math.ceil(grandTotal / people);\n}",
  autoCheck: {
    functionName: "costPerPerson",
    tests: [
      { name: "ไม่มีทิป หารลงตัว", args: [1000, 4, 0], expected: 250 },
      { name: "ทิป 10%", args: [1000, 4, 10], expected: 275 },
      { name: "ทิป 10% ของบิล 100 บาท", args: [100, 2, 10], expected: 55 },
      { name: "ปัดขึ้นเมื่อหารไม่ลงตัว", args: [100, 3, 0], expected: 34 },
      { name: "ทิปที่ทำให้มีทศนิยม", args: [999, 3, 15], expected: 383 },
      { name: "จำนวนคนเป็น 0", args: [500, 0, 10], expected: null },
      { name: "จำนวนคนติดลบ", args: [500, -2, 0], expected: null },
    ],
    wrongAnswers: [
      "function costPerPerson(total, people, tipPercent) { return Math.ceil(total / people); }",
      "function costPerPerson(total, people, tipPercent) { if (people <= 0) return null; return Math.round((total + total * tipPercent / 100) / people); }",
      "function costPerPerson(total, people, tipPercent) { if (people <= 0) return null; console.log(Math.ceil((total + total * tipPercent / 100) / people)); }",
      "function costPerPerson(total, people, tipPercent) { return Math.ceil((total + total * tipPercent / 100) / people); }",
      "function costPerPerson(total, people, tipPercent) { if (people <= 0) return null; return Math.ceil(total * (1 + tipPercent / 100) / people); }",
    ],
  },
  buggy: "function splitCost(total, people) {\n  console.log(Math.ceil(total / people));\n}\n\nconst share = splitCost(900, 3);\nconsole.log(\"คนละ \" + share + \" บาท\");",
  bugExplanation: "Terminal แสดง 300 แล้วตามด้วย “คนละ undefined บาท” เพราะ splitCost แค่พิมพ์ผลแต่ไม่ได้ return ค่า share จึงเป็น undefined แก้ให้น้อยที่สุดโดยเปลี่ยน console.log(...) ใน function เป็น return Math.ceil(total / people); แล้วผลจะเป็น “คนละ 300 บาท” — function คำนวณ ส่วนผู้เรียกเป็นคนตัดสินใจว่าจะแสดงอย่างไร",
  vocabulary: [v("function", "ชุดคำสั่งที่ตั้งชื่อไว้และเรียกใช้ซ้ำได้"), v("parameter", "ตัวแปรในวงเล็บตอนประกาศ รอรับค่า"), v("argument", "ค่าจริงที่ส่งเข้าไปตอนเรียก"), v("return", "ส่งค่ากลับไปยังจุดที่เรียกและจบ function"), v("call / invoke", "สั่งให้ function ทำงานด้วยชื่อ()"), v("side effect", "ผลกระทบนอก function เช่น พิมพ์ แก้ตัวแปรข้างนอก บันทึกไฟล์"), v("pure function", "ใช้แค่ input ได้ output เดิมเสมอและไม่มี side effect")],
},{
  id: "js-scope",
  courseId,
  unit: "Functions",
  title: "scope, closure และ state ที่ function จำได้",
  objective: "ทำนายว่าตัวแปรไหนมองเห็นได้จากตรงไหน และใช้ closure สร้าง function ที่จำค่าของตัวเองโดยไม่ใช้ตัวแปร global",
  why: "เครื่องออกบัตรสองเครื่องต้องจำเลขของตนเอง ถ้าใช้ชื่อเดียวจากภายนอกจะเพิ่มเลขปนกัน closure ช่วยเก็บข้อมูลแยกไว้ให้แต่ละ function",
  explanation: "scope คือขอบเขตที่ชื่อตัวแปรมองเห็นได้ JavaScript ใช้ lexical scope: ดูจากตำแหน่งที่เขียนโค้ด function ข้างในอ่านตัวแปรของ function ข้างนอกได้ แต่ข้างนอกมองเข้าไปข้างในไม่ได้ closure คือ function ที่จำตัวแปรรอบตัวตอนที่ถูกสร้างไว้ แม้ function ข้างนอกจะ return ไปแล้ว แต่ละครั้งที่เรียก function ข้างนอกจะได้ชุดตัวแปรใหม่แยกกัน",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-runtime", "js-function-values"],
  example: "function makeTicketMachine(prefix) {\n  let next = 1;\n  return function () {\n    const ticket = prefix + \"-\" + next;\n    next = next + 1;\n    return ticket;\n  };\n}\n\nconst food = makeTicketMachine(\"F\");\nconst drink = makeTicketMachine(\"D\");\n\nconsole.log(food());\nconsole.log(food());\nconsole.log(drink());\nconsole.log(food());",
  expectedOutput: "F-1\nF-2\nD-1\nF-3",
  tracePrompt: "ทำนายทั้งสี่บรรทัดก่อนรัน แล้วอธิบายว่าทำไม drink() ได้ D-1 ทั้งที่ food ถูกเรียกไปแล้วสองครั้ง",
  traceAnswer: "F-1, F-2, D-1, F-3 — การเรียก makeTicketMachine แต่ละครั้งสร้าง next ชุดใหม่ food จำ next ของตัวเอง (1→2→3) ส่วน drink จำอีกตัวที่เริ่ม 1 ทั้งสองไม่แชร์ค่ากัน และโค้ดข้างนอกเข้าถึง next ตรง ๆ ไม่ได้",
  practicePrompt: "เขียน makeCounter(start) ที่คืน function ซึ่งทุกครั้งที่เรียกจะเพิ่มค่าทีละ 1 แล้วคืนค่าใหม่ counter แต่ละตัวต้องไม่แชร์ค่ากัน (อย่าแก้ checkCounters ที่ใช้ตรวจ)",
  starter: "function makeCounter(start) {\n  // เก็บค่าปัจจุบันไว้ใน scope ของ makeCounter\n  return function () {\n    return start;\n  };\n}\n\n// ใช้ตรวจคำตอบ — อย่าแก้\nfunction checkCounters(start) {\n  const a = makeCounter(start);\n  const b = makeCounter(100);\n  return [a(), a(), b(), a()];\n}",
  solution: "function makeCounter(start) {\n  let count = start;\n  return function () {\n    count = count + 1;\n    return count;\n  };\n}\n\nfunction checkCounters(start) {\n  const a = makeCounter(start);\n  const b = makeCounter(100);\n  return [a(), a(), b(), a()];\n}",
  autoCheck: {
    functionName: "checkCounters",
    tests: [
      { name: "เริ่มที่ 0", args: [0], expected: [1, 2, 101, 3] },
      { name: "เริ่มที่ 10", args: [10], expected: [11, 12, 101, 13] },
    ],
    wrongAnswers: [
      "let count = 0;\nfunction makeCounter(start) { count = start; return function () { count = count + 1; return count; }; }\nfunction checkCounters(start) { const a = makeCounter(start); const b = makeCounter(100); return [a(), a(), b(), a()]; }",
      "function makeCounter(start) { return function () { start + 1; return start + 1; }; }\nfunction checkCounters(start) { const a = makeCounter(start); const b = makeCounter(100); return [a(), a(), b(), a()]; }",
    ],
  },
  buggy: "function setup() {\n  const secret = \"1234\";\n}\n\nsetup();\nconsole.log(secret);",
  bugExplanation: "ReferenceError: secret is not defined เพราะ secret ประกาศใน scope ของ setup ข้างนอกมองไม่เห็น ถ้าต้องใช้ค่าข้างนอก ให้ setup return ค่า แล้วรับด้วย const secret = setup(); — ข้อมูลไหลออกจาก function ผ่าน return ไม่ใช่การรั่วของตัวแปร",
  vocabulary: [v("scope", "ขอบเขตที่มองเห็นชื่อตัวแปร"), v("lexical scope", "scope ที่กำหนดจากตำแหน่งเขียนโค้ด"), v("closure", "function ที่จำตัวแปรรอบตัวตอนถูกสร้าง"), v("global variable", "ตัวแปรที่มองเห็นจากทุกที่ ทำให้ state แชร์กันง่ายเกินไป"), v("factory function", "function ที่สร้างและคืน function หรือ object ใหม่")],
},
{
  id: "js-loops",
  courseId,
  unit: "ทำซ้ำและ collections",
  title: "for, while, for...of และ accumulator",
  objective: "เลือกใช้ for, while หรือ for...of ให้เหมาะกับงาน เขียนเงื่อนไขหยุดที่ถูกต้อง และสะสมผลด้วยตัวแปร accumulator",
  why: "รวมยอดบิล นับคนที่ตอบรับ หรือหยุดเมื่องบหมด ล้วนเป็นการทำซ้ำ ลูปที่เงื่อนไขหยุดผิดทำให้ได้ผลขาด/เกินหนึ่งรอบ หรือค้างไม่จบ",
  explanation: "for ใช้เมื่อรู้จำนวนรอบ: เริ่มค่า; เงื่อนไขทำต่อ; ขั้นถัดไป while ใช้เมื่อหยุดตามเงื่อนไขที่ไม่รู้ล่วงหน้า for...of วนค่าทีละตัวใน array โดยไม่ต้องจัดการ index accumulator คือตัวแปรที่ประกาศก่อนลูปและสะสมผลทุกรอบ break ออกจากลูปทันที continue ข้ามไปรอบถัดไป",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-loop-control"],
  example: "const prices = [120, 80, 300, 50];\n\nlet total = 0;\nfor (const price of prices) {\n  total = total + price;\n}\nconsole.log(\"รวม\", total);\n\nfor (let i = 0; i < prices.length; i++) {\n  if (prices[i] > 100) continue;\n  console.log(\"ราคาไม่เกิน 100 ที่ index\", i);\n}\n\nlet budget = 250;\nlet bought = 0;\nwhile (bought < prices.length && budget >= prices[bought]) {\n  budget = budget - prices[bought];\n  bought = bought + 1;\n}\nconsole.log(\"ซื้อได้\", bought, \"ชิ้น เหลือ\", budget);",
  expectedOutput: "รวม 550\nราคาไม่เกิน 100 ที่ index 1\nราคาไม่เกิน 100 ที่ index 3\nซื้อได้ 2 ชิ้น เหลือ 50",
  tracePrompt: "ทำตารางรอบของ while: budget และ bought ก่อนตรวจเงื่อนไขแต่ละรอบ แล้วบอกว่าทำไมลูปหยุดทั้งที่ยังมีของราคา 50 อยู่",
  traceAnswer: "รอบ 1: budget 250 ≥ 120 → budget 130, bought 1 · รอบ 2: 130 ≥ 80 → budget 50, bought 2 · ตรวจรอบ 3: 50 ≥ 300 เป็น false จึงหยุด ลูปนี้ซื้อตามลำดับและหยุดที่ชิ้นแรกที่ซื้อไม่ไหว จึงไม่ข้ามไปซื้อชิ้น 50",
  practicePrompt: "เขียน affordableCount(prices, budget) ที่ซื้อตามลำดับรายการจนกว่างบจะไม่พอสำหรับชิ้นถัดไป แล้วคืนจำนวนชิ้นที่ซื้อได้",
  starter: "function affordableCount(prices, budget) {\n  let count = 0;\n  // วนตามลำดับ หยุดเมื่องบไม่พอสำหรับชิ้นถัดไป\n  return count;\n}",
  solution: "function affordableCount(prices, budget) {\n  let count = 0;\n  let remaining = budget;\n  for (const price of prices) {\n    if (price > remaining) break;\n    remaining = remaining - price;\n    count = count + 1;\n  }\n  return count;\n}",
  autoCheck: {
    functionName: "affordableCount",
    tests: [
      { name: "หยุดที่ชิ้นที่แพงเกิน", args: [[120, 80, 300, 50], 250], expected: 2 },
      { name: "งบพอดีเป๊ะ", args: [[100, 100], 200], expected: 2 },
      { name: "ซื้อชิ้นแรกไม่ได้", args: [[500, 10], 100], expected: 0 },
      { name: "รายการว่าง", args: [[], 100], expected: 0 },
    ],
    wrongAnswers: [
      "function affordableCount(prices, budget) { let count = 0; let remaining = budget; for (const price of prices) { if (price > remaining) continue; remaining -= price; count++; } return count; }",
      "function affordableCount(prices, budget) { let count = 0; let remaining = budget; for (const price of prices) { if (price >= remaining) break; remaining -= price; count++; } return count; }",
      "function affordableCount(prices, budget) { return prices.length; }",
    ],
  },
  buggy: "let seats = 3;\nwhile (seats > 0) {\n  console.log(\"เหลือที่นั่ง\", seats);\n}\nconsole.log(\"เต็มแล้ว\");",
  bugExplanation: "ลูปไม่จบเพราะ seats ไม่เคยเปลี่ยน เงื่อนไข seats > 0 จึงจริงตลอด (ใน runner จะถูกหยุดหลัง 1.5 วินาที) แก้โดยลดค่าในทุกรอบ: seats = seats - 1; — ลูป while ต้องมีบรรทัดที่พาเงื่อนไขเข้าใกล้ false เสมอ",
  vocabulary: [v("loop", "การทำซ้ำชุดคำสั่ง"), v("iteration", "การทำซ้ำหนึ่งรอบ"), v("accumulator", "ตัวแปรที่สะสมผลจากทุกรอบ"), v("break / continue", "ออกจากลูปทันที / ข้ามไปรอบถัดไป"), v("off-by-one", "บั๊กที่ทำเกินหรือขาดหนึ่งรอบ")],
},
{
  id: "js-arrays",
  courseId,
  unit: "ทำซ้ำและ collections",
  title: "array, map, filter, find และ immutability",
  objective: "ใช้ map แปลงทุกสมาชิก filter เลือกบางสมาชิก และ find หาตัวแรก โดยได้ array ใหม่และไม่แก้ array เดิม",
  why: "รายการกิจกรรม สินค้า หรือคอมเมนต์ในหน้าเว็บมาจาก array การแปลงด้วย map/filter อ่านง่ายกว่าลูปเขียนเองและไม่ทำลายข้อมูลต้นฉบับที่ส่วนอื่นยังใช้อยู่",
  explanation: "map เรียก function กับทุกสมาชิกแล้วได้ array ใหม่ความยาวเท่าเดิม filter เก็บเฉพาะสมาชิกที่ function คืนค่า truthy ได้ array ใหม่ที่อาจสั้นลง find คืนสมาชิกตัวแรกที่ตรงเงื่อนไขหรือ undefined includes ตรวจว่ามีค่าหรือไม่ ทั้งหมดนี้ไม่แก้ array เดิม ต่างจาก push หรือ sort ที่แก้ของเดิม",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-objects", "js-function-values"],
  example: "const activities = [\n  { title: \"Board game\", capacity: 6, joined: 4 },\n  { title: \"Hiking\", capacity: 8, joined: 8 },\n  { title: \"Cafe hop\", capacity: 5, joined: 1 },\n];\n\nconst open = activities.filter((activity) => activity.joined < activity.capacity);\nconst labels = open.map((activity) => activity.title + \" (เหลือ \" + (activity.capacity - activity.joined) + \")\");\nconst full = activities.find((activity) => activity.joined === activity.capacity);\n\nconsole.log(labels);\nconsole.log(full.title);\nconsole.log(activities.length, open.length);",
  expectedOutput: "[\"Board game (เหลือ 2)\",\"Cafe hop (เหลือ 4)\"]\nHiking\n3 2",
  tracePrompt: "ทำนายผลของ labels ก่อนรัน และบอกว่าทำไม activities.length ยังเป็น 3 หลัง filter",
  traceAnswer: "[\"Board game (เหลือ 2)\",\"Cafe hop (เหลือ 4)\"] — filter เก็บกิจกรรมที่ยังไม่เต็ม (Hiking เต็มจึงหลุด) แล้ว map แปลงแต่ละตัวเป็นข้อความ activities ยัง 3 เพราะ filter สร้าง array ใหม่ ไม่ได้ลบของเดิม (runner แสดง array เป็น JSON จึงไม่มีช่องว่างหลัง comma)",
  practicePrompt: "เขียน openActivityTitles(activities) ที่คืนชื่อกิจกรรมที่ยังไม่เต็มเป็นตัวพิมพ์ใหญ่ทั้งหมด โดยไม่แก้ array ที่รับเข้ามา",
  starter: "function openActivityTitles(activities) {\n  // 1) เลือกเฉพาะกิจกรรมที่ joined < capacity\n  // 2) แปลงเป็นชื่อตัวพิมพ์ใหญ่\n  return activities;\n}",
  solution: "function openActivityTitles(activities) {\n  return activities\n    .filter((activity) => activity.joined < activity.capacity)\n    .map((activity) => activity.title.toUpperCase());\n}",
  autoCheck: {
    functionName: "openActivityTitles",
    tests: [
      { name: "มีทั้งว่างและเต็ม", args: [[{ title: "Board game", capacity: 6, joined: 4 }, { title: "Hiking", capacity: 8, joined: 8 }, { title: "Cafe hop", capacity: 5, joined: 1 }]], expected: ["BOARD GAME", "CAFE HOP"] },
      { name: "เต็มทุกกิจกรรม", args: [[{ title: "Hiking", capacity: 2, joined: 2 }]], expected: [] },
      { name: "ไม่มีกิจกรรม", args: [[]], expected: [] },
    ],
    wrongAnswers: [
      "function openActivityTitles(activities) { return activities.map((a) => a.title.toUpperCase()); }",
      "function openActivityTitles(activities) { return activities.filter((a) => a.joined <= a.capacity).map((a) => a.title.toUpperCase()); }",
      "function openActivityTitles(activities) { return activities.find((a) => a.joined < a.capacity).title.toUpperCase(); }",
    ],
  },
  buggy: "const scores = [70, 85, 92];\nconst curved = scores.map((score) => {\n  score + 5;\n});\nconsole.log(curved);",
  bugExplanation: "ได้ [null,null,null] ใน runner (ใน Node จะเห็น [ undefined, undefined, undefined ]) เพราะ arrow function ที่มี { } ต้อง return เอง เมื่อไม่มี return ค่าแต่ละตัวจึงเป็น undefined แก้เป็น scores.map((score) => score + 5) หรือเขียน return score + 5; ใน { }",
  vocabulary: [v("array", "รายการค่าที่เรียงตาม index"), v("map", "แปลงทุกสมาชิก ได้ array ใหม่ยาวเท่าเดิม"), v("filter", "เลือกสมาชิกที่ผ่านเงื่อนไข ได้ array ใหม่"), v("find", "คืนสมาชิกตัวแรกที่ตรงเงื่อนไขหรือ undefined"), v("callback", "function ที่ส่งให้ function อื่นเรียก"), v("arrow function", "รูปย่อของ function: (x) => x + 1")],
},
{
  id: "js-objects",
  courseId,
  unit: "ทำซ้ำและ collections",
  title: "object properties, destructuring และ spread",
  objective: "อ่านและสร้าง object ด้วย dot/bracket notation, destructuring และ spread เพื่อสร้าง object ใหม่ที่อัปเดตบาง field",
  why: "request body, response จาก API และ state ในหน้าเว็บล้วนเป็น object การอัปเดตแบบสร้าง object ใหม่คือพื้นฐานของ React state และการเขียน reducer",
  explanation: "object จับคู่ key กับ value อ่านด้วย activity.title หรือ activity[\"title\"] (bracket ใช้เมื่อชื่อ key อยู่ในตัวแปร) destructuring ดึง field ออกเป็นตัวแปร: const { title, joined } = activity spread {...activity, joined: 5} คัดลอก field ทั้งหมดลง object ใหม่แล้ว field ทางขวาทับของเดิม การคัดลอกนี้เป็นแบบตื้น (shallow): array หรือ object ที่อยู่ข้างในยังเป็นตัวเดิม",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-array-basics", "js-function-values"],
  example: "const activity = { title: \"Board game\", capacity: 6, joined: 4 };\n\nconst { title, joined } = activity;\nconsole.log(title, joined);\n\nconst key = \"capacity\";\nconsole.log(activity[key]);\n\nconst updated = { ...activity, joined: activity.joined + 1, place: \"Cafe\" };\nconsole.log(updated);\nconsole.log(activity.joined);",
  expectedOutput: "Board game 4\n6\n{\"title\":\"Board game\",\"capacity\":6,\"joined\":5,\"place\":\"Cafe\"}\n4",
  tracePrompt: "ทำนายผลของ updated และ activity.joined ก่อนรัน แล้วอธิบายว่าถ้าสลับเป็น { joined: 99, ...activity } จะได้ joined เท่าไร",
  traceAnswer: "updated มี joined 5 และ field ใหม่ place ส่วน activity.joined ยัง 4 เพราะ spread สร้าง object ใหม่ ถ้าสลับลำดับเป็น { joined: 99, ...activity } จะได้ joined 4 เพราะ field ที่มาทีหลัง (จาก activity) ทับค่าที่มาก่อน",
  practicePrompt: "เขียน reschedule(activity, newDate) ที่คืน object ใหม่ซึ่ง date เป็นค่าใหม่ เพิ่ม field updated: true คง field อื่นไว้ทั้งหมด และต้องไม่แก้ activity ที่รับเข้ามา (อย่าแก้ checkReschedule ที่ใช้ตรวจ)",
  starter: "function reschedule(activity, newDate) {\n  // สร้าง object ใหม่ด้วย spread แล้วกำหนด date และ updated\n  activity.date = newDate;\n  return activity;\n}\n\n// ใช้ตรวจคำตอบ — อย่าแก้\nfunction checkReschedule(activity, newDate) {\n  const before = JSON.stringify(activity);\n  const updated = reschedule(activity, newDate);\n  return { updated, originalUnchanged: JSON.stringify(activity) === before };\n}",
  solution: "function reschedule(activity, newDate) {\n  return { ...activity, date: newDate, updated: true };\n}\n\nfunction checkReschedule(activity, newDate) {\n  const before = JSON.stringify(activity);\n  const updated = reschedule(activity, newDate);\n  return { updated, originalUnchanged: JSON.stringify(activity) === before };\n}",
  autoCheck: {
    functionName: "checkReschedule",
    tests: [
      { name: "เปลี่ยนวัน คง field อื่น และไม่แก้ของเดิม", args: [{ title: "Hiking", date: "2026-10-10", joined: 3 }, "2026-10-17"], expected: { updated: { title: "Hiking", date: "2026-10-17", joined: 3, updated: true }, originalUnchanged: true } },
      { name: "เพิ่ม date ให้กิจกรรมที่ยังไม่มี", args: [{ title: "Movie" }, "2026-11-01"], expected: { updated: { title: "Movie", date: "2026-11-01", updated: true }, originalUnchanged: true } },
    ],
    wrongAnswers: [
      "function reschedule(activity, newDate) { activity.date = newDate; activity.updated = true; return activity; }\nfunction checkReschedule(activity, newDate) {\n  const before = JSON.stringify(activity);\n  const updated = reschedule(activity, newDate);\n  return { updated, originalUnchanged: JSON.stringify(activity) === before };\n}",
      "function reschedule(activity, newDate) { return { date: newDate, updated: true }; }\nfunction checkReschedule(activity, newDate) {\n  const before = JSON.stringify(activity);\n  const updated = reschedule(activity, newDate);\n  return { updated, originalUnchanged: JSON.stringify(activity) === before };\n}",
      "function reschedule(activity, newDate) { return { date: newDate, updated: true, ...activity }; }\nfunction checkReschedule(activity, newDate) {\n  const before = JSON.stringify(activity);\n  const updated = reschedule(activity, newDate);\n  return { updated, originalUnchanged: JSON.stringify(activity) === before };\n}",
    ],
  },
  buggy: "const activity = { title: \"Hiking\", joined: 3 };\nconst field = \"joined\";\nconsole.log(activity.field);",
  bugExplanation: "ได้ undefined เพราะ activity.field หา key ที่ชื่อ field ตรงตัว ไม่ได้อ่านค่าในตัวแปร field เมื่อชื่อ key อยู่ในตัวแปรต้องใช้ bracket: activity[field] ได้ 3",
  vocabulary: [v("object", "ชุดของ key กับ value"), v("property", "คู่ key–value หนึ่งคู่ใน object"), v("dot / bracket notation", "อ่าน property ด้วย obj.key หรือ obj[\"key\"]"), v("destructuring", "ดึงค่าจาก object/array ออกเป็นตัวแปร"), v("spread", "คัดลอก field/สมาชิกด้วย ..."), v("shallow copy", "คัดลอกชั้นนอก ของข้างในยังเป็นตัวเดิม")],
},
{
  id: "js-errors",
  courseId,
  unit: "Debugging",
  title: "อ่าน error และ debug ด้วย console.log",
  objective: "อ่าน error message ให้ได้ชนิด สาเหตุ และตำแหน่ง แล้วใช้ console.log ตรวจสมมติฐานก่อนแก้",
  why: "เวลาส่วนใหญ่ของงานจริงคือการหาว่าทำไมโค้ดไม่ทำงาน คนที่อ่าน error เป็นจะแก้ได้ตรงจุดแทนการเดาและแก้มั่ว",
  explanation: "error ใน JavaScript บอกสามอย่าง: ชนิด (ReferenceError, TypeError, SyntaxError) ข้อความที่บอกสิ่งที่ผิด และตำแหน่ง/stack ที่ไล่ย้อนการเรียก ขั้นตอน debug คือ อ่าน error → ตั้งสมมติฐาน → พิมพ์ค่าที่เกี่ยวข้องด้วย console.log → แก้ทีละจุด → รันซ้ำ",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-loops", "js-objects"],
  example: "const cart = { items: [\"ชาเย็น\", \"ขนมปัง\"] };\n\nconsole.log(\"จำนวนสินค้า:\", cart.items.length);\nconsole.log(\"ตะกร้ามี field อะไร:\", Object.keys(cart));\n\ntry {\n  console.log(cart.item.length);\n} catch (error) {\n  console.log(error.name + \": \" + error.message);\n}",
  expectedOutput: "จำนวนสินค้า: 2\nตะกร้ามี field อะไร: [\"items\"]\nTypeError: Cannot read properties of undefined (reading 'length')",
  tracePrompt: "ก่อนรัน: บรรทัดไหนจะเกิด error ชนิดอะไร และข้อความ (reading 'length') บอกอะไรเกี่ยวกับค่าที่อยู่ทางซ้ายของ .length",
  traceAnswer: "cart.item.length เกิด TypeError เพราะ cart ไม่มี field ชื่อ item (มีแต่ items) cart.item จึงเป็น undefined แล้วอ่าน .length จาก undefined ไม่ได้ ข้อความ (reading 'length') บอกว่าพยายามอ่าน property length จากค่าที่เป็น undefined — ให้มองหาค่าทางซ้ายของ .length",
  practicePrompt: "แก้ function totalItems ให้คืนจำนวนสินค้ารวมของทุกออร์เดอร์ โดยใช้ console.log ดูค่าก่อนแก้ จากนั้นลบ log ที่ไม่จำเป็นแล้วกด Run tests",
  starter: "function totalItems(orders) {\n  let total = 0;\n  for (const order of orders) {\n    // ลอง console.log(order) เพื่อดูว่า field ชื่ออะไร\n    total = total + order.item.length;\n  }\n  return total;\n}\n\nconst sample = [{ items: [\"ชา\", \"กาแฟ\"] }, { items: [\"ขนม\"] }];\nconsole.log(totalItems(sample)); // ควรได้ 3",
  solution: "function totalItems(orders) {\n  let total = 0;\n  for (const order of orders) {\n    total = total + order.items.length;\n  }\n  return total;\n}",
  autoCheck: {
    functionName: "totalItems",
    tests: [
      { name: "สองออร์เดอร์", args: [[{ items: ["ชา", "กาแฟ"] }, { items: ["ขนม"] }]], expected: 3 },
      { name: "ออร์เดอร์ว่าง", args: [[{ items: [] }]], expected: 0 },
      { name: "ไม่มีออร์เดอร์", args: [[]], expected: 0 },
    ],
    wrongAnswers: [
      "function totalItems(orders) { return orders.length; }",
      "function totalItems(orders) { let total = 0; for (const order of orders) { total = total + (order.item ? order.item.length : 0); } return total; }",
    ],
  },
  buggy: "const prices = [40, 55, 30];\nlet sum = 0;\nfor (let i = 0; i <= prices.length; i++) {\n  sum = sum + prices[i];\n}\nconsole.log(sum);",
  bugExplanation: "ผลคือ NaN ไม่ใช่ 125 ใส่ console.log(i, prices[i]) ในลูปจะเห็นรอบสุดท้าย i = 3 และ prices[3] เป็น undefined เพราะ index สุดท้ายคือ 2 แล้ว 125 + undefined = NaN แก้โดยเปลี่ยน <= เป็น < — การ log ค่าที่เปลี่ยนในแต่ละรอบช่วยยืนยันสมมติฐานก่อนแก้",
  vocabulary: [v("ReferenceError", "ใช้ชื่อที่ไม่มีอยู่ เช่นพิมพ์ชื่อตัวแปรผิด"), v("TypeError", "ใช้ค่าผิดชนิด เช่นอ่าน property จาก undefined หรือเรียกสิ่งที่ไม่ใช่ function"), v("SyntaxError", "เขียนผิดไวยากรณ์จน engine อ่านโค้ดไม่ได้"), v("stack trace", "รายการการเรียก function ที่นำไปสู่ error"), v("hypothesis", "สมมติฐานว่าสาเหตุคืออะไร ก่อนลงมือแก้")],
},
{
  id: "js-references",
  courseId,
  unit: "ทำซ้ำและ collections",
  title: "reference, mutation และการคัดลอก",
  objective: "อธิบายได้ว่าทำไมการแก้ object ผ่านตัวแปรหนึ่งไปเปลี่ยนอีกตัวแปร และเขียน function ที่อัปเดตข้อมูลโดยไม่ mutate input",
  why: "บั๊กที่หายากที่สุดคือข้อมูลเปลี่ยนเองจากที่อื่น React ไม่ render ใหม่เมื่อ state ถูก mutate และ API handler ที่แก้ object ที่แชร์อยู่ทำให้ request หนึ่งรั่วไปอีก request",
  explanation: "primitive (number, string, boolean) ถูกคัดลอกค่าเมื่อ assign ส่วน object และ array ตัวแปรเก็บ reference (ที่อยู่ของ object) การ assign คัดลอกแค่ reference ทั้งสองชื่อจึงชี้ object เดียวกัน === ของ object เทียบว่าเป็นตัวเดียวกันไหม ไม่ได้เทียบเนื้อหา mutation คือการแก้ object เดิม เช่น push หรือ obj.x = 1 วิธีอัปเดตอย่างปลอดภัยคือสร้างตัวใหม่ด้วย spread และสร้าง array ใหม่สำหรับ field ที่เป็น array ด้วย",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-objects"],
  example: "let a = 5;\nlet b = a;\nb = b + 1;\nconsole.log(a, b);\n\nconst original = { title: \"Hiking\", members: [\"ซี\"] };\nconst alias = original;\nalias.members.push(\"ต้น\");\nconsole.log(original.members);\n\nconst shallow = { ...original };\nshallow.members.push(\"ฝน\");\nconsole.log(original.members.length);\n\nconst safe = { ...original, members: [...original.members, \"บี\"] };\nconsole.log(original.members.length, safe.members.length);\nconsole.log(alias === original, safe === original);",
  expectedOutput: "5 6\n[\"ซี\",\"ต้น\"]\n3\n3 4\ntrue false",
  tracePrompt: "วาดกล่องตัวแปรกับลูกศรชี้ไปที่ object ทีละบรรทัด แล้วทำนายว่าทำไม shallow.members.push ทำให้ original.members ยาวขึ้นด้วย",
  traceAnswer: "a กับ b เป็น number จึงแยกกัน (5 6) alias ชี้ object เดียวกับ original การ push ผ่าน alias จึงเห็นใน original ส่วน { ...original } สร้าง object ใหม่ก็จริง แต่ field members ยังชี้ array เดิม (shallow copy) push จึงไปเพิ่มใน array เดียวกัน (ยาว 3) safe สร้าง array ใหม่ด้วย [...original.members, \"บี\"] original จึงยัง 3 และ safe ยาว 4",
  practicePrompt: "เขียน addMember(activity, name) ที่คืนกิจกรรมใหม่ซึ่ง members มีชื่อเพิ่มต่อท้าย โดยไม่แก้ activity เดิม และถ้าชื่อนั้นอยู่แล้วให้คืน activity ตัวเดิม (อย่าแก้ checkAddMember)",
  starter: "function addMember(activity, name) {\n  activity.members.push(name);\n  return activity;\n}\n\n// ใช้ตรวจคำตอบ — อย่าแก้\nfunction checkAddMember(activity, name) {\n  const updated = addMember(activity, name);\n  return { originalMembers: activity.members, updatedMembers: updated.members, sameObject: updated === activity };\n}",
  solution: "function addMember(activity, name) {\n  if (activity.members.includes(name)) return activity;\n  return { ...activity, members: [...activity.members, name] };\n}\n\nfunction checkAddMember(activity, name) {\n  const updated = addMember(activity, name);\n  return { originalMembers: activity.members, updatedMembers: updated.members, sameObject: updated === activity };\n}",
  autoCheck: {
    functionName: "checkAddMember",
    tests: [
      { name: "เพิ่มคนใหม่โดยไม่แก้ของเดิม", args: [{ title: "Hiking", members: ["ซี"] }, "ต้น"], expected: { originalMembers: ["ซี"], updatedMembers: ["ซี", "ต้น"], sameObject: false } },
      { name: "ชื่อซ้ำคืนตัวเดิม", args: [{ title: "Hiking", members: ["ซี", "ต้น"] }, "ต้น"], expected: { originalMembers: ["ซี", "ต้น"], updatedMembers: ["ซี", "ต้น"], sameObject: true } },
    ],
    wrongAnswers: [
      "function addMember(activity, name) { const copy = { ...activity }; copy.members.push(name); return copy; }\nfunction checkAddMember(activity, name) { const updated = addMember(activity, name); return { originalMembers: activity.members, updatedMembers: updated.members, sameObject: updated === activity }; }",
      "function addMember(activity, name) { return { ...activity, members: [...activity.members, name] }; }\nfunction checkAddMember(activity, name) { const updated = addMember(activity, name); return { originalMembers: activity.members, updatedMembers: updated.members, sameObject: updated === activity }; }",
    ],
  },
  buggy: "const defaults = { tags: [] };\nconst first = { ...defaults };\nconst second = { ...defaults };\nfirst.tags.push(\"เกม\");\nconsole.log(second.tags);",
  bugExplanation: "second.tags กลายเป็น [\"เกม\"] ทั้งที่ไม่ได้แตะ second เพราะ spread คัดลอกแบบตื้น first.tags และ second.tags ชี้ array เดียวกับ defaults.tags แก้โดยสร้าง array ใหม่ทุกครั้ง: const first = { ...defaults, tags: [...defaults.tags] }; หรือสร้าง default ด้วย function ที่คืน object ใหม่",
  vocabulary: [v("reference", "ที่อยู่ที่ตัวแปรใช้ชี้ไปยัง object"), v("mutation", "การแก้ object/array เดิม"), v("alias", "ตัวแปรสองชื่อที่ชี้ object เดียวกัน"), v("identity", "ความเป็นตัวเดียวกัน ตรวจด้วย === สำหรับ object"), v("immutable update", "การอัปเดตโดยสร้างค่าใหม่แทนการแก้ของเดิม")],
},
{
  id: "js-callbacks",
  courseId,
  unit: "ฟังก์ชันระดับสูง",
  title: "callback, reduce และ sort ด้วย comparator",
  objective: "ส่ง function เป็น argument ใช้ reduce สรุปรายการเป็นค่าเดียว และเรียงข้อมูลด้วย comparator โดยไม่แก้ array เดิม",
  why: "การสรุปยอด จัดอันดับ และจัดกลุ่มข้อมูลก่อนแสดงผลเป็นงานประจำของทั้ง front-end และ back-end ถ้าไม่เข้าใจ comparator จะเรียงตัวเลขผิดแบบเงียบ ๆ",
  explanation: "higher-order function คือ function ที่รับหรือคืน function callback คือ function ที่ส่งให้ตัวอื่นเรียกเมื่อถึงเวลา reduce((acc, item) => ..., initial) เดินทีละสมาชิกโดยส่งผลสะสมต่อไปเรื่อย ๆ sort แก้ array เดิมและเรียงแบบ string โดยค่าเริ่มต้น ต้องให้ comparator (a, b) ที่คืนค่าลบเมื่อ a ควรมาก่อน ค่าบวกเมื่อ b ควรมาก่อน และ 0 เมื่อเท่ากัน คัดลอกด้วย [...list] ก่อน sort เพื่อไม่แก้ของเดิม",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-arrays", "js-references"],
  example: "const votes = [\n  { title: \"Hiking\", votes: 5 },\n  { title: \"Board game\", votes: 9 },\n  { title: \"Cafe hop\", votes: 5 },\n];\n\nconst totalVotes = votes.reduce((sum, item) => sum + item.votes, 0);\nconsole.log(totalVotes);\n\nconsole.log([10, 9, 100].sort());\nconsole.log([10, 9, 100].sort((a, b) => a - b));\n\nconst ranked = [...votes].sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title));\nconsole.log(ranked.map((item) => item.title));\nconsole.log(votes[0].title);",
  expectedOutput: "19\n[10,100,9]\n[9,10,100]\n[\"Board game\",\"Cafe hop\",\"Hiking\"]\nHiking",
  tracePrompt: "ทำตาราง reduce สามรอบ (sum ก่อน/หลัง) แล้วอธิบายว่าทำไม [10, 9, 100].sort() ได้ [10, 100, 9]",
  traceAnswer: "sum: 0 → 5 → 14 → 19 · sort() ไม่มี comparator จะแปลงเป็น string แล้วเรียงแบบพจนานุกรม \"10\" < \"100\" < \"9\" เพราะเทียบทีละตัวอักษร ส่วน (a, b) => a - b คืนค่าลบเมื่อ a น้อยกว่า จึงเรียงตัวเลขจากน้อยไปมาก ranked เรียงคะแนนมากก่อน ถ้าเท่ากัน (5) ใช้ชื่อตามตัวอักษร Cafe hop จึงมาก่อน Hiking และ votes[0] ยังเป็น Hiking เพราะคัดลอกก่อน sort",
  practicePrompt: "เขียน rankActivities(activities) ที่คืนชื่อกิจกรรมเรียงตามคะแนนโหวตจากมากไปน้อย ถ้าคะแนนเท่ากันให้เรียงชื่อตามตัวอักษร และต้องไม่แก้ array ที่รับเข้ามา (อย่าแก้ checkRank ที่ใช้ตรวจ)",
  starter: "function rankActivities(activities) {\n  // คัดลอก → sort ด้วย comparator → map เป็นชื่อ\n  return activities.map((activity) => activity.title);\n}\n\n// ใช้ตรวจคำตอบ — อย่าแก้\nfunction checkRank(activities) {\n  const before = JSON.stringify(activities);\n  const ranked = rankActivities(activities);\n  return { ranked, originalUnchanged: JSON.stringify(activities) === before };\n}",
  solution: "function rankActivities(activities) {\n  return [...activities]\n    .sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title))\n    .map((activity) => activity.title);\n}\n\nfunction checkRank(activities) {\n  const before = JSON.stringify(activities);\n  const ranked = rankActivities(activities);\n  return { ranked, originalUnchanged: JSON.stringify(activities) === before };\n}",
  autoCheck: {
    functionName: "checkRank",
    tests: [
      { name: "เรียงตามคะแนนและไม่แก้ของเดิม", args: [[{ title: "Hiking", votes: 5 }, { title: "Board game", votes: 9 }, { title: "Movie", votes: 7 }]], expected: { ranked: ["Board game", "Movie", "Hiking"], originalUnchanged: true } },
      { name: "คะแนนเท่ากันเรียงชื่อ", args: [[{ title: "Hiking", votes: 5 }, { title: "Cafe hop", votes: 5 }]], expected: { ranked: ["Cafe hop", "Hiking"], originalUnchanged: true } },
      { name: "คะแนนหลักสิบกับหลักหน่วย", args: [[{ title: "A", votes: 9 }, { title: "B", votes: 10 }]], expected: { ranked: ["B", "A"], originalUnchanged: true } },
    ],
    wrongAnswers: [
      "function rankActivities(activities) { return activities.sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title)).map((a) => a.title); }\nfunction checkRank(activities) {\n  const before = JSON.stringify(activities);\n  const ranked = rankActivities(activities);\n  return { ranked, originalUnchanged: JSON.stringify(activities) === before };\n}",
      "function rankActivities(activities) { return [...activities].sort((a, b) => b.votes - a.votes).map((a) => a.title); }\nfunction checkRank(activities) {\n  const before = JSON.stringify(activities);\n  const ranked = rankActivities(activities);\n  return { ranked, originalUnchanged: JSON.stringify(activities) === before };\n}",
      "function rankActivities(activities) { return [...activities].sort((a, b) => String(b.votes).localeCompare(String(a.votes)) || a.title.localeCompare(b.title)).map((a) => a.title); }\nfunction checkRank(activities) {\n  const before = JSON.stringify(activities);\n  const ranked = rankActivities(activities);\n  return { ranked, originalUnchanged: JSON.stringify(activities) === before };\n}",
    ],
  },
  buggy: "const prices = [120, 80, 300];\nconst total = prices.reduce((sum, price) => {\n  sum + price;\n});\nconsole.log(total);",
  bugExplanation: "ได้ undefined เพราะ callback ที่มี { } ไม่ได้ return ผลรวม รอบถัดไป sum จึงเป็น undefined และยังไม่ได้ให้ค่าเริ่มต้น แก้เป็น prices.reduce((sum, price) => sum + price, 0) — ใส่ค่าเริ่มต้นเสมอเพื่อให้ array ว่างได้ 0 แทน error",
  vocabulary: [v("higher-order function", "function ที่รับหรือคืน function"), v("callback", "function ที่ส่งให้ function อื่นเรียก"), v("reduce", "รวมทุกสมาชิกให้เหลือค่าเดียวด้วย accumulator"), v("comparator", "function (a, b) ที่บอกลำดับให้ sort"), v("localeCompare", "เทียบ string ตามลำดับตัวอักษรของภาษา")],
},
{
  id: "js-project-planner-1",
  courseId,
  unit: "ฟังก์ชันระดับสูง",
  title: "Mini project: Friends Activity Planner M1 — สรุปภาพรวมกิจกรรม",
  objective: "ประกอบ conditions, functions, filter, reduce และ sort เป็น function เดียวที่สรุปข้อมูลกิจกรรมสำหรับหน้า dashboard",
  why: "โจทย์จริงไม่บอกว่าต้องใช้ method ไหน ต้องแยกปัญหาเป็นขั้นเล็ก เขียน helper ทีละตัว แล้วประกอบกัน milestone นี้คือแกนข้อมูลที่ Planner ทุกเวอร์ชันถัดไปใช้ต่อ",
  explanation: "Friends Activity Planner ให้เพื่อนสร้างกิจกรรม เข้าร่วม และโหวต M1 ทำส่วน “สรุป” แบบ pure function: รับ array ของกิจกรรม แล้วคืน object สรุปที่หน้าเว็บนำไปแสดงได้ทันที วิธีคิด: เขียนผลลัพธ์ที่อยากได้ก่อน → แตก field ละหนึ่ง helper → ทดสอบ helper กับข้อมูลเล็ก → ประกอบ",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-callbacks", "js-conditions"],
  example: "function isFull(activity) {\n  return activity.joined >= activity.capacity;\n}\n\nconst sample = [\n  { title: \"Hiking\", capacity: 8, joined: 8, votes: 5 },\n  { title: \"Board game\", capacity: 6, joined: 4, votes: 9 },\n];\n\nconst fullCount = sample.filter(isFull).length;\nconst seatsLeft = sample.reduce((sum, activity) => sum + Math.max(0, activity.capacity - activity.joined), 0);\nconsole.log({ fullCount, seatsLeft });",
  expectedOutput: "{\"fullCount\":1,\"seatsLeft\":2}",
  tracePrompt: "ก่อนรัน: เขียน output ที่คาดไว้ แล้วอธิบายว่าทำไม seatsLeft ใช้ Math.max(0, ...) ข้อมูลแบบไหนจะทำให้ค่าติดลบถ้าไม่ใส่",
  traceAnswer: "{\"fullCount\":1,\"seatsLeft\":2} — Hiking เต็ม (8 ≥ 8) ที่นั่งเหลือ 0 + 2 = 2 Math.max(0, ...) กันกรณีข้อมูลผิดที่ joined มากกว่า capacity เช่น joined 10 capacity 8 จะได้ −2 และทำให้ยอดรวมน้อยกว่าความจริง",
  practicePrompt: "เขียน summarizePlanner(activities) ที่คืน { total, open, full, seatsLeft, topTitle } โดย open/full คือจำนวนกิจกรรมที่ยังรับคน/เต็มแล้ว seatsLeft คือที่นั่งว่างรวม (ไม่ติดลบ) และ topTitle คือชื่อกิจกรรมคะแนนโหวตสูงสุด (เท่ากันเลือกชื่อตามตัวอักษร) ถ้าไม่มีกิจกรรมให้ topTitle เป็น null",
  starter: "function isFull(activity) {\n  // กิจกรรมเต็มเมื่อไร? (ระวังข้อมูลที่ joined เกิน capacity)\n  return false;\n}\n\nfunction summarizePlanner(activities) {\n  // แตกเป็น helper ทีละ field แล้วประกอบ\n  return { total: activities.length, open: 0, full: 0, seatsLeft: 0, topTitle: null };\n}",
  solution: "function isFull(activity) {\n  return activity.joined >= activity.capacity;\n}\n\nfunction topActivityTitle(activities) {\n  if (activities.length === 0) return null;\n  const ranked = [...activities].sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title));\n  return ranked[0].title;\n}\n\nfunction summarizePlanner(activities) {\n  const full = activities.filter(isFull).length;\n  const seatsLeft = activities.reduce((sum, activity) => sum + Math.max(0, activity.capacity - activity.joined), 0);\n  return {\n    total: activities.length,\n    open: activities.length - full,\n    full,\n    seatsLeft,\n    topTitle: topActivityTitle(activities),\n  };\n}",
  autoCheck: {
    functionName: "summarizePlanner",
    tests: [
      { name: "ข้อมูลปกติ", args: [[{ title: "Hiking", capacity: 8, joined: 8, votes: 5 }, { title: "Board game", capacity: 6, joined: 4, votes: 9 }, { title: "Cafe hop", capacity: 5, joined: 1, votes: 2 }]], expected: { total: 3, open: 2, full: 1, seatsLeft: 6, topTitle: "Board game" } },
      { name: "โหวตเท่ากันเลือกตามชื่อ", args: [[{ title: "Movie", capacity: 4, joined: 1, votes: 7 }, { title: "Karaoke", capacity: 4, joined: 2, votes: 7 }]], expected: { total: 2, open: 2, full: 0, seatsLeft: 5, topTitle: "Karaoke" } },
      { name: "joined เกิน capacity ไม่ทำให้ที่นั่งติดลบ", args: [[{ title: "Hiking", capacity: 8, joined: 10, votes: 1 }, { title: "Board game", capacity: 6, joined: 4, votes: 0 }]], expected: { total: 2, open: 1, full: 1, seatsLeft: 2, topTitle: "Hiking" } },
      { name: "ไม่มีกิจกรรม", args: [[]], expected: { total: 0, open: 0, full: 0, seatsLeft: 0, topTitle: null } },
    ],
    wrongAnswers: [
      "function summarizePlanner(activities) { const full = activities.filter((a) => a.joined === a.capacity).length; const seatsLeft = activities.reduce((s, a) => s + Math.max(0, a.capacity - a.joined), 0); const top = [...activities].sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title))[0]; return { total: activities.length, open: activities.length - full, full, seatsLeft, topTitle: top ? top.title : null }; }",
      "function summarizePlanner(activities) { const full = activities.filter((a) => a.joined >= a.capacity).length; const seatsLeft = activities.reduce((s, a) => s + (a.capacity - a.joined), 0); const top = [...activities].sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title))[0]; return { total: activities.length, open: activities.length - full, full, seatsLeft, topTitle: top ? top.title : null }; }",
      "function summarizePlanner(activities) { const full = activities.filter((a) => a.joined >= a.capacity).length; const seatsLeft = activities.reduce((s, a) => s + Math.max(0, a.capacity - a.joined), 0); const top = [...activities].sort((a, b) => b.votes - a.votes)[0]; return { total: activities.length, open: activities.length - full, full, seatsLeft, topTitle: top ? top.title : null }; }",
    ],
  },
  buggy: "function topTitle(activities) {\n  return activities.sort((a, b) => b.votes - a.votes)[0].title;\n}\n\nconst list = [{ title: \"Hiking\", votes: 1 }, { title: \"Movie\", votes: 4 }];\nconsole.log(topTitle(list));\nconsole.log(list[0].title);",
  bugExplanation: "บรรทัดแรกถูก (Movie) แต่บรรทัดที่สองพิมพ์ Movie ทั้งที่รายการเดิมขึ้นต้นด้วย Hiking เพราะ sort แก้ array เดิม function ที่ควรแค่ “อ่าน” จึงไปสลับลำดับข้อมูลของคนเรียก แก้เป็น [...activities].sort(...) และถ้า array ว่าง [0] เป็น undefined ต้องคืน null ก่อน",
  vocabulary: [v("milestone", "เป้าหมายย่อยของโปรเจกต์ที่ส่งมอบได้"), v("helper function", "function เล็กที่ทำงานเดียวเพื่อประกอบเป็นงานใหญ่"), v("summary object", "object ที่รวบรวมผลสรุปไว้ให้ส่วนแสดงผล"), v("edge case", "กรณีขอบ เช่นรายการว่างหรือข้อมูลเกินขอบเขต")],
},
{
  id: "js-exceptions",
  courseId,
  unit: "Errors และ modules",
  title: "throw, try/catch และการออกแบบ error",
  objective: "โยน Error ที่มีข้อความชัดเจนเมื่อ input ใช้ไม่ได้ และจับด้วย try/catch ในจุดที่ตัดสินใจได้ว่าจะทำอะไรต่อ",
  why: "ข้อมูลจากผู้ใช้และระบบภายนอกผิดได้เสมอ การคืนค่าแปลก ๆ อย่าง -1 หรือ undefined ซ่อนปัญหา ส่วน error ที่บอกเหตุผลช่วยให้ทั้งผู้ใช้และนักพัฒนารู้ว่าต้องแก้อะไร",
  explanation: "throw new Error(\"ข้อความ\") หยุด function ทันทีและส่ง error ขึ้นไปหาผู้เรียกทีละชั้นจนกว่าจะมี try/catch จับ ถ้าไม่มีใครจับ โปรแกรมจะหยุดพร้อม error catch (error) ได้ object ที่มี name และ message finally ทำงานเสมอไม่ว่าจะ error หรือไม่ หลักออกแบบ: throw ในจุดที่รู้ว่าผิด catch ในจุดที่รู้ว่าจะแจ้งผู้ใช้อย่างไร ไม่ต้องครอบ try ทุกบรรทัด",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-functions", "js-errors"],
  example: "function parseSeats(text) {\n  const seats = Number(text);\n  if (!Number.isInteger(seats)) throw new Error(\"จำนวนที่นั่งต้องเป็นจำนวนเต็ม\");\n  if (seats < 2) throw new Error(\"ต้องมีอย่างน้อย 2 ที่นั่ง\");\n  return seats;\n}\n\nfor (const input of [\"6\", \"1\", \"สาม\"]) {\n  try {\n    console.log(\"รับได้\", parseSeats(input));\n  } catch (error) {\n    console.log(\"ปฏิเสธ:\", error.message);\n  } finally {\n    console.log(\"ตรวจ\", input, \"แล้ว\");\n  }\n}",
  expectedOutput: "รับได้ 6\nตรวจ 6 แล้ว\nปฏิเสธ: ต้องมีอย่างน้อย 2 ที่นั่ง\nตรวจ 1 แล้ว\nปฏิเสธ: จำนวนที่นั่งต้องเป็นจำนวนเต็ม\nตรวจ สาม แล้ว",
  tracePrompt: "ทำนาย output ทั้งหกบรรทัด แล้วอธิบายว่าเมื่อ input เป็น \"1\" บรรทัด return seats ถูกรันหรือไม่",
  traceAnswer: "รับได้ 6 / ตรวจ 6 แล้ว / ปฏิเสธ: ต้องมีอย่างน้อย 2 ที่นั่ง / ตรวจ 1 แล้ว / ปฏิเสธ: จำนวนที่นั่งต้องเป็นจำนวนเต็ม / ตรวจ สาม แล้ว — เมื่อ \"1\" ถึงบรรทัด throw การทำงานใน parseSeats หยุดทันที return ไม่ถูกรัน การควบคุมกระโดดไปที่ catch แล้ว finally ทำงานทุกรอบ",
  practicePrompt: "เขียน parseGuestCount(text) ที่ throw Error ข้อความ \"ต้องเป็นตัวเลข\" เมื่อแปลงไม่ได้หรือไม่ใช่จำนวนเต็ม และ \"ต้องอยู่ระหว่าง 1–9\" เมื่อนอกช่วง ไม่งั้นคืนจำนวน (อย่าแก้ tryParse ที่ใช้ตรวจ)",
  starter: "function parseGuestCount(text) {\n  const count = Number(text);\n  // throw new Error(\"...\") เมื่อ input ใช้ไม่ได้\n  return count;\n}\n\n// ใช้ตรวจคำตอบ — อย่าแก้\nfunction tryParse(text) {\n  try {\n    return { ok: true, value: parseGuestCount(text) };\n  } catch (error) {\n    return { ok: false, message: error.message };\n  }\n}",
  solution: "function parseGuestCount(text) {\n  const count = Number(text);\n  if (text.trim() === \"\" || !Number.isInteger(count)) throw new Error(\"ต้องเป็นตัวเลข\");\n  if (count < 1 || count > 9) throw new Error(\"ต้องอยู่ระหว่าง 1–9\");\n  return count;\n}\n\nfunction tryParse(text) {\n  try {\n    return { ok: true, value: parseGuestCount(text) };\n  } catch (error) {\n    return { ok: false, message: error.message };\n  }\n}",
  autoCheck: {
    functionName: "tryParse",
    tests: [
      { name: "ตัวเลขในช่วง", args: ["4"], expected: { ok: true, value: 4 } },
      { name: "ไม่ใช่ตัวเลข", args: ["สี่"], expected: { ok: false, message: "ต้องเป็นตัวเลข" } },
      { name: "ทศนิยม", args: ["2.5"], expected: { ok: false, message: "ต้องเป็นตัวเลข" } },
      { name: "ช่องว่าง", args: ["  "], expected: { ok: false, message: "ต้องเป็นตัวเลข" } },
      { name: "เกินช่วง", args: ["10"], expected: { ok: false, message: "ต้องอยู่ระหว่าง 1–9" } },
      { name: "ศูนย์", args: ["0"], expected: { ok: false, message: "ต้องอยู่ระหว่าง 1–9" } },
    ],
    wrongAnswers: [
      "function parseGuestCount(text) { const count = Number(text); if (Number.isNaN(count)) throw new Error(\"ต้องเป็นตัวเลข\"); if (count < 1 || count > 9) throw new Error(\"ต้องอยู่ระหว่าง 1–9\"); return count; }\nfunction tryParse(text) { try { return { ok: true, value: parseGuestCount(text) }; } catch (error) { return { ok: false, message: error.message }; } }",
      "function parseGuestCount(text) { const count = Number(text); if (!Number.isInteger(count)) return null; if (count < 1 || count > 9) return null; return count; }\nfunction tryParse(text) { try { return { ok: true, value: parseGuestCount(text) }; } catch (error) { return { ok: false, message: error.message }; } }",
    ],
  },
  buggy: "function loadSettings(text) {\n  try {\n    return JSON.parse(text);\n  } catch (error) {\n  }\n}\n\nconst settings = loadSettings(\"{ theme: dark }\");\nconsole.log(settings.theme);",
  bugExplanation: "เกิด TypeError ที่บรรทัดสุดท้าย ห่างจากต้นเหตุจริง เพราะ catch ว่างกลืน SyntaxError ของ JSON.parse แล้ว function คืน undefined แก้โดยไม่กลืน error เงียบ ๆ: คืนค่า default ที่ตั้งใจ เช่น return { theme: \"light\" } พร้อม console.warn หรือ throw new Error(\"settings ไม่ใช่ JSON ที่ถูกต้อง\") ให้ผู้เรียกตัดสินใจ",
  vocabulary: [v("throw", "ส่ง error ออกจาก function ทันที"), v("try / catch", "ลองทำ และจับ error ที่เกิดระหว่างนั้น"), v("finally", "ส่วนที่ทำงานเสมอไม่ว่าจะเกิด error หรือไม่"), v("Error.message", "ข้อความอธิบายสาเหตุของ error"), v("swallow an error", "จับ error แล้วไม่ทำอะไร ทำให้ปัญหาถูกซ่อน")],
},
{
  id: "js-modules-json",
  courseId,
  unit: "Errors และ modules",
  title: "ES modules และ JSON",
  objective: "แยกโค้ดเป็นไฟล์ด้วย export/import และแปลงข้อมูลไป–กลับด้วย JSON.stringify/JSON.parse พร้อมจัดการ JSON ที่เสีย",
  why: "โปรเจกต์จริงมีหลายไฟล์ และข้อมูลที่ส่งระหว่าง browser กับ server หรือเก็บใน localStorage อยู่ในรูป JSON ทุกครั้ง",
  explanation: "ES module คือไฟล์ที่มี scope ของตัวเอง ใช้ export เพื่อให้ไฟล์อื่น import ได้ named export ต้อง import ด้วยชื่อตรงกันใน { } default export มีได้ไฟล์ละหนึ่ง JSON เป็นรูปแบบข้อความของข้อมูล: key ต้องอยู่ในเครื่องหมายคำพูดคู่ รองรับ string, number, boolean, null, array, object เท่านั้น JSON.stringify แปลงค่าเป็นข้อความ (field ที่เป็น undefined หรือ function หายไป) JSON.parse แปลงกลับและ throw SyntaxError ถ้าข้อความผิดรูปแบบ",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-objects", "js-exceptions"],
  example: "const activity = { title: \"Hiking\", joined: 3, note: undefined, tags: [\"outdoor\"] };\n\nconst text = JSON.stringify(activity);\nconsole.log(text);\nconsole.log(typeof text);\n\nconst back = JSON.parse(text);\nconsole.log(back.tags[0], \"note\" in back);\n\ntry {\n  JSON.parse(\"{ title: 'Hiking' }\");\n} catch (error) {\n  console.log(error.name);\n}",
  expectedOutput: "{\"title\":\"Hiking\",\"joined\":3,\"tags\":[\"outdoor\"]}\nstring\noutdoor false\nSyntaxError",
  tracePrompt: "ทำนายผลของ JSON.stringify ก่อนรัน field ไหนหายไป และทำไม JSON.parse(\"{ title: 'Hiking' }\") จึงผิด",
  traceAnswer: "note หายไปเพราะ JSON ไม่มีค่า undefined ผลจึงเป็น {\"title\":\"Hiking\",\"joined\":3,\"tags\":[\"outdoor\"]} ส่วน \"{ title: 'Hiking' }\" ผิดเพราะ JSON บังคับให้ key อยู่ในเครื่องหมายคำพูดคู่และ string ต้องใช้คำพูดคู่ ไม่ใช่ single quote",
  practicePrompt: "เขียน safeParse(text) ที่คืน { ok: true, data } เมื่อ parse สำเร็จ และ { ok: false, error: \"JSON ไม่ถูกต้อง\" } เมื่อ parse ไม่ได้ โดยไม่ปล่อยให้ error หลุดออกไป",
  starter: "function safeParse(text) {\n  // ใช้ try/catch ครอบ JSON.parse\n  return { ok: true, data: JSON.parse(text) };\n}",
  solution: "function safeParse(text) {\n  try {\n    return { ok: true, data: JSON.parse(text) };\n  } catch {\n    return { ok: false, error: \"JSON ไม่ถูกต้อง\" };\n  }\n}",
  autoCheck: {
    functionName: "safeParse",
    tests: [
      { name: "object ถูกต้อง", args: ["{\"title\":\"Hiking\",\"joined\":3}"], expected: { ok: true, data: { title: "Hiking", joined: 3 } } },
      { name: "array ถูกต้อง", args: ["[1,2,3]"], expected: { ok: true, data: [1, 2, 3] } },
      { name: "single quote", args: ["{'title':'Hiking'}"], expected: { ok: false, error: "JSON ไม่ถูกต้อง" } },
      { name: "ข้อความว่าง", args: [""], expected: { ok: false, error: "JSON ไม่ถูกต้อง" } },
    ],
    wrongAnswers: [
      "function safeParse(text) { if (text === \"\") return { ok: false, error: \"JSON ไม่ถูกต้อง\" }; return { ok: true, data: JSON.parse(text) }; }",
      "function safeParse(text) { try { return { ok: true, data: JSON.parse(text) }; } catch { return { ok: false }; } }",
    ],
  },
  buggy: "// file: format.js\nfunction formatTitle(title) {\n  return title.trim();\n}\n\n// file: main.js\nimport { formatTitle } from \"./format.js\";\nconsole.log(formatTitle(\"  Hiking \"));",
  bugExplanation: "เมื่อรันในเครื่อง (Node หรือ browser แบบ module) จะได้ SyntaxError ว่า format.js ไม่มี export ชื่อ formatTitle เพราะลืม export แก้เป็น export function formatTitle(title) { ... } ในไฟล์ format.js (ตัวอย่างนี้มีสองไฟล์ จึงต้องรันในเครื่อง runner บนเว็บรันได้เฉพาะไฟล์เดียว)",
  vocabulary: [v("module", "ไฟล์ที่มี scope ของตัวเองและเลือก export สิ่งที่ให้ไฟล์อื่นใช้"), v("export / import", "เปิดให้ใช้ / นำเข้ามาใช้"), v("named export", "export ด้วยชื่อ ต้อง import ด้วยชื่อเดียวกัน"), v("JSON", "รูปแบบข้อความสำหรับส่งและเก็บข้อมูล"), v("serialize / parse", "แปลงค่าเป็นข้อความ / แปลงข้อความกลับเป็นค่า")],
},
{
  id: "js-promises",
  courseId,
  unit: "Asynchronous",
  title: "Promise และลำดับงานที่ไม่รอกัน",
  objective: "ทำนายลำดับ output ของโค้ดที่ผสม synchronous, Promise และ setTimeout และอธิบายสถานะ pending/fulfilled/rejected",
  why: "การโหลดข้อมูลจาก API อ่านไฟล์ หรือรอ timer ใช้เวลา JavaScript ไม่หยุดรอแต่ทำงานอื่นต่อ ถ้าทำนายลำดับไม่ได้จะเจอข้อมูลที่ “ยังไม่มา” ตอนที่โค้ดพยายามใช้",
  explanation: "Promise คือ object ที่แทน “ผลที่จะมาในอนาคต” เริ่มที่ pending แล้วจบเป็น fulfilled (สำเร็จพร้อมค่า) หรือ rejected (ล้มเหลวพร้อมเหตุผล) ครั้งเดียว .then(callback) ลงทะเบียนสิ่งที่จะทำเมื่อสำเร็จ .catch สำหรับล้มเหลว callback เหล่านี้ไม่ทำทันที แต่เข้าคิวรอให้โค้ด synchronous ปัจจุบันจบก่อน เมื่อถึงจุดนั้น callback ของ Promise ที่พร้อมแล้ว (microtask) จะถูกทำจนหมดก่อนหยิบงาน timer ถัดไป",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-callbacks", "js-exceptions"],
  example: "console.log(\"1) สั่งอาหาร\");\n\nsetTimeout(() => console.log(\"4) timer 0 ms\"), 0);\n\nPromise.resolve(\"ข้าวผัด\").then((dish) => console.log(\"3) ได้\", dish));\n\nconst late = new Promise((resolve) => {\n  setTimeout(() => resolve(\"ชาไทย\"), 20);\n});\nlate.then((drink) => console.log(\"5) ได้\", drink));\n\nconsole.log(\"2) ระหว่างรอ คุยกับเพื่อน\");",
  expectedOutput: "1) สั่งอาหาร\n2) ระหว่างรอ คุยกับเพื่อน\n3) ได้ ข้าวผัด\n4) timer 0 ms\n5) ได้ ชาไทย",
  tracePrompt: "ก่อนรัน เขียนสามคอลัมน์: โค้ด synchronous · คิว Promise · คิว timer แล้วย้ายแต่ละ callback ลงคิวที่ถูก ทำไม timer 0 ms จึงมาหลัง “3)”",
  traceAnswer: "synchronous รันก่อนทั้งหมด: 1) แล้ว 2) ระหว่างนั้น then ของ Promise.resolve เข้าคิว Promise และ callback ของ setTimeout 0 เข้าคิว timer เมื่อ synchronous จบ คิว Promise ถูกทำก่อน (3) แล้วจึงคิว timer (4) ส่วน late จะ resolve หลัง timer 20 ms จึงได้ 5) ทีหลังสุด — 0 ms แปลว่า “ไม่เร็วกว่าคิวถัดไป” ไม่ใช่ “ทันที”",
  practicePrompt: "เขียน delay(ms, value) ที่คืน Promise ซึ่ง resolve เป็น value หลังเวลาผ่านไป ms มิลลิวินาที แล้วใช้มันพิมพ์ “โหลดเสร็จ” หลัง 30 ms โดยมีข้อความ “กำลังโหลด…” พิมพ์ก่อน กด Run แล้วตรวจลำดับใน Terminal",
  starter: "function delay(ms, value) {\n  // return new Promise((resolve) => { ... });\n}\n\nconsole.log(\"กำลังโหลด…\");\n// เรียก delay(30, \"โหลดเสร็จ\") แล้วพิมพ์ค่าที่ได้",
  solution: "function delay(ms, value) {\n  return new Promise((resolve) => {\n    setTimeout(() => resolve(value), ms);\n  });\n}\n\nconsole.log(\"กำลังโหลด…\");\ndelay(30, \"โหลดเสร็จ\").then((message) => console.log(message));",
  buggy: "function getTitle() {\n  let title = \"ยังไม่มี\";\n  setTimeout(() => {\n    title = \"Hiking\";\n  }, 10);\n  return title;\n}\n\nconsole.log(getTitle());",
  bugExplanation: "พิมพ์ “ยังไม่มี” เพราะ return title ทำงานทันทีใน synchronous code ก่อนที่ timer จะเปลี่ยนค่า ค่าที่มาทีหลังต้องส่งผ่าน Promise แก้เป็น function getTitle() { return new Promise((resolve) => setTimeout(() => resolve(\"Hiking\"), 10)); } แล้ว getTitle().then(console.log)",
  vocabulary: [v("asynchronous", "งานที่เริ่มตอนนี้แต่เสร็จทีหลัง โดยโปรแกรมไม่หยุดรอ"), v("Promise", "object แทนผลลัพธ์ในอนาคต"), v("pending / fulfilled / rejected", "กำลังรอ / สำเร็จ / ล้มเหลว"), v("then / catch", "ลงทะเบียน callback เมื่อสำเร็จ / ล้มเหลว"), v("microtask queue", "คิวของ Promise ที่ถูกทำก่อนคิว timer")],
},
{
  id: "js-async",
  courseId,
  unit: "Asynchronous",
  title: "async/await และ error path",
  objective: "เขียน async function ที่รอผลด้วย await จัดการทั้ง error จาก network และ response ที่ไม่สำเร็จ และไม่ลืม await",
  why: "การเชื่อม front-end กับ API ล้มเหลวได้หลายจุด fetch ไม่ throw เมื่อ server ตอบ 400/500 ถ้าไม่ตรวจ response.ok หน้าเว็บจะถือว่าสำเร็จทั้งที่ไม่ใช่",
  explanation: "async function คืน Promise เสมอ ข้างในใช้ await เพื่อพัก “เฉพาะ function นี้” จน Promise จบ แล้วได้ค่าออกมาเหมือนโค้ดธรรมดา ถ้า Promise rejected บรรทัด await จะ throw จึงใช้ try/catch ได้ fetch reject เมื่อส่ง request ไม่สำเร็จ (เครือข่ายล่ม, URL ไม่ถูกต้อง, ถูกยกเลิก) ส่วน status 4xx/5xx ยัง resolve ตามปกติ ต้องตรวจ response.ok เอง ลืม await = ได้ Promise แทนค่า",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-promises"],
  example: "// fakeFetch จำลอง API เพราะ runner ปิด network\nfunction fakeFetch(path) {\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      if (path === \"/offline\") reject(new Error(\"Network error\"));\n      else if (path === \"/activities\") resolve({ ok: true, status: 200, json: async () => [{ title: \"Hiking\" }] });\n      else resolve({ ok: false, status: 404, json: async () => ({ error: \"Not found\" }) });\n    }, 10);\n  });\n}\n\nasync function loadTitles(path) {\n  try {\n    const response = await fakeFetch(path);\n    if (!response.ok) return \"ผิดพลาด \" + response.status;\n    const data = await response.json();\n    return data.map((item) => item.title).join(\", \");\n  } catch (error) {\n    return \"เชื่อมต่อไม่ได้: \" + error.message;\n  }\n}\n\nconsole.log(await loadTitles(\"/activities\"));\nconsole.log(await loadTitles(\"/missing\"));\nconsole.log(await loadTitles(\"/offline\"));\nconsole.log(loadTitles(\"/activities\") instanceof Promise);",
  expectedOutput: "Hiking\nผิดพลาด 404\nเชื่อมต่อไม่ได้: Network error\ntrue",
  tracePrompt: "ไล่ทีละ path ว่าเข้ากิ่งไหนของ loadTitles และอธิบายว่าทำไมบรรทัดสุดท้ายได้ true แทนชื่อกิจกรรม",
  traceAnswer: "/activities → ok true → json → \"Hiking\" · /missing → resolve แต่ ok false → \"ผิดพลาด 404\" (ไม่เข้า catch เพราะไม่ได้ reject) · /offline → reject → await throw → catch → \"เชื่อมต่อไม่ได้: Network error\" · บรรทัดสุดท้ายไม่มี await จึงได้ Promise ที่ยังไม่จบ (instanceof Promise เป็น true) — async function คืน Promise เสมอ",
  practicePrompt: "เขียน async function loadSummary(fetcher) ที่เรียก fetcher(\"/activities\") ถ้า ok ให้คืน “มี N กิจกรรม” ถ้าไม่ ok คืน “โหลดไม่สำเร็จ (status)” และถ้า fetcher reject คืน “ออฟไลน์” — starter มี fetcher จำลองให้ครบทั้งสามกรณีแล้ว กด Run แล้วตรวจสามบรรทัดใน Terminal",
  starter: "// fetcher จำลองสามแบบ (runner ปิด network จริง)\nconst okFetch = async () => ({ ok: true, status: 200, json: async () => [{ title: \"Hiking\" }, { title: \"Movie\" }] });\nconst serverError = async () => ({ ok: false, status: 500, json: async () => ({ error: \"boom\" }) });\nconst offline = async () => { throw new Error(\"Network error\"); };\n\nasync function loadSummary(fetcher) {\n  // await fetcher(\"/activities\"), ตรวจ response.ok, await response.json()\n}\n\nconsole.log(await loadSummary(okFetch));\nconsole.log(await loadSummary(serverError));\nconsole.log(await loadSummary(offline));",
  solution: "const okFetch = async () => ({ ok: true, status: 200, json: async () => [{ title: \"Hiking\" }, { title: \"Movie\" }] });\nconst serverError = async () => ({ ok: false, status: 500, json: async () => ({ error: \"boom\" }) });\nconst offline = async () => { throw new Error(\"Network error\"); };\n\nasync function loadSummary(fetcher) {\n  try {\n    const response = await fetcher(\"/activities\");\n    if (!response.ok) return \"โหลดไม่สำเร็จ (\" + response.status + \")\";\n    const activities = await response.json();\n    return \"มี \" + activities.length + \" กิจกรรม\";\n  } catch {\n    return \"ออฟไลน์\";\n  }\n}\n\nconsole.log(await loadSummary(okFetch));\nconsole.log(await loadSummary(serverError));\nconsole.log(await loadSummary(offline));",
  buggy: "async function save(activity) {\n  if (!activity.title) throw new Error(\"ต้องมีชื่อ\");\n  return \"บันทึก \" + activity.title;\n}\n\ntry {\n  save({ title: \"\" });\n  console.log(\"บันทึกแล้ว\");\n} catch (error) {\n  console.log(\"ผิดพลาด:\", error.message);\n}",
  bugExplanation: "พิมพ์ “บันทึกแล้ว” ทั้งที่ข้อมูลผิด เพราะไม่ได้ await: save คืน Promise ที่ rejected ทีหลัง try/catch แบบ synchronous จึงจับไม่ได้ (ใน browser จะเห็น unhandled rejection) แก้เป็น await save({ title: \"\" }); ภายใน try แล้ว catch จะทำงานและพิมพ์ “ผิดพลาด: ต้องมีชื่อ”",
  vocabulary: [v("async function", "function ที่คืน Promise เสมอและใช้ await ข้างในได้"), v("await", "รอ Promise จบแล้วเอาค่าออกมา หรือ throw ถ้า rejected"), v("response.ok", "true เมื่อ status อยู่ในช่วง 200–299"), v("network error", "ความล้มเหลวที่ไปไม่ถึง server ทำให้ fetch reject"), v("unhandled rejection", "Promise ที่ล้มเหลวแต่ไม่มีใครจับ")],
},
{
  id: "js-project-planner-2",
  courseId,
  unit: "Asynchronous",
  title: "Mini project: Friends Activity Planner M2 — ตรวจข้อมูลและจัดตารางสัปดาห์",
  objective: "ประกอบ validation, object grouping และการเรียงลำดับเป็น pipeline ที่แยกข้อมูลถูก/ผิดก่อนแสดงผล",
  why: "ข้อมูลที่ได้จาก API หรือฟอร์มมักปนข้อมูลที่ไม่ครบ หน้าเว็บที่ดีแยกข้อมูลที่ใช้ได้ออกมาแสดง และรายงานรายการที่มีปัญหาแทนการพังทั้งหน้า",
  explanation: "M2 ต่อจาก M1: รับรายการกิจกรรมดิบ (เช่นที่โหลดจาก API ด้วย async/await) แล้วผ่าน pipeline สามขั้นที่เป็น pure function: validate แต่ละรายการ → จัดกลุ่มรายการที่ถูกต้องตามวัน → เรียงในแต่ละวัน ส่วน async อยู่แค่ขอบนอก (โหลดข้อมูล) แกนกลางเป็น function ธรรมดาที่ทดสอบได้ง่าย",
  language: "javascript",
  standard: "v3",
  prerequisites: ["js-project-planner-1", "js-async", "js-modules-json"],
  example: "const raw = [\n  { title: \"Hiking\", day: \"sat\", time: \"07:00\" },\n  { title: \"\", day: \"sat\", time: \"09:00\" },\n  { title: \"Movie\", day: \"fri\", time: \"19:30\" },\n];\n\nconst problems = raw.filter((item) => item.title.trim() === \"\").length;\nconst byDay = {};\nfor (const item of raw) {\n  if (item.title.trim() === \"\") continue;\n  byDay[item.day] = [...(byDay[item.day] ?? []), item.title];\n}\nconsole.log(byDay, problems);",
  expectedOutput: "{\"sat\":[\"Hiking\"],\"fri\":[\"Movie\"]} 1",
  tracePrompt: "ไล่ลูปทีละรอบว่า byDay เปลี่ยนอย่างไร และอธิบายว่า byDay[item.day] ?? [] ทำหน้าที่อะไรในรอบแรกของแต่ละวัน",
  traceAnswer: "รอบ Hiking: byDay.sat ยังไม่มี (undefined) จึงใช้ [] แล้วได้ [\"Hiking\"] · รอบชื่อว่าง: continue ข้าม · รอบ Movie: สร้าง fri = [\"Movie\"] ผล {\"sat\":[\"Hiking\"],\"fri\":[\"Movie\"]} และ problems 1 ตัวดำเนินการ ?? ให้ค่าทางขวาเมื่อทางซ้ายเป็น null/undefined จึงเริ่ม array ใหม่ได้โดยไม่ต้อง if",
  practicePrompt: "เขียน planWeek(activities) ที่คืน { schedule, invalid } โดยกิจกรรมถูกต้องเมื่อ ชื่อไม่ว่างหลัง trim, day เป็นหนึ่งใน mon tue wed thu fri sat sun และ time อยู่ในรูป HH:MM (00–23 : 00–59) schedule จัดกลุ่มตาม day และเรียงตาม time ในแต่ละวัน เก็บเป็น \"HH:MM ชื่อ\" ส่วน invalid เก็บ index ของรายการที่ผิดตามลำดับเดิม",
  starter: "const DAYS = [\"mon\", \"tue\", \"wed\", \"thu\", \"fri\", \"sat\", \"sun\"];\n\nfunction isValidTime(time) {\n  // ตรวจรูปแบบ HH:MM และช่วงชั่วโมง/นาที\n  return true;\n}\n\nfunction planWeek(activities) {\n  const schedule = {};\n  const invalid = [];\n  // validate (ชื่อ, day, time) → group by day → sort by time\n  return { schedule, invalid };\n}",
  solution: "const DAYS = [\"mon\", \"tue\", \"wed\", \"thu\", \"fri\", \"sat\", \"sun\"];\n\nfunction isValidTime(time) {\n  if (!/^\\d{2}:\\d{2}$/.test(time)) return false;\n  const [hours, minutes] = time.split(\":\").map(Number);\n  return hours <= 23 && minutes <= 59;\n}\n\nfunction planWeek(activities) {\n  const schedule = {};\n  const invalid = [];\n  activities.forEach((activity, index) => {\n    if (activity.title.trim() === \"\" || !DAYS.includes(activity.day) || !isValidTime(activity.time)) {\n      invalid.push(index);\n      return;\n    }\n    schedule[activity.day] = [...(schedule[activity.day] ?? []), activity];\n  });\n  for (const day of Object.keys(schedule)) {\n    schedule[day] = [...schedule[day]]\n      .sort((a, b) => a.time.localeCompare(b.time))\n      .map((activity) => activity.time + \" \" + activity.title.trim());\n  }\n  return { schedule, invalid };\n}",
  autoCheck: {
    functionName: "planWeek",
    tests: [
      { name: "จัดกลุ่มและเรียงเวลา", args: [[{ title: "Movie", day: "sat", time: "19:30" }, { title: "Hiking", day: "sat", time: "07:00" }, { title: "Cafe", day: "sun", time: "10:00" }]], expected: { schedule: { sat: ["07:00 Hiking", "19:30 Movie"], sun: ["10:00 Cafe"] }, invalid: [] } },
      { name: "แยกรายการผิด", args: [[{ title: " ", day: "sat", time: "09:00" }, { title: "Karaoke", day: "fri", time: "25:00" }, { title: "Run", day: "fri", time: "6:00" }, { title: "Lunch", day: "fri", time: "12:00" }]], expected: { schedule: { fri: ["12:00 Lunch"] }, invalid: [0, 1, 2] } },
      { name: "วันที่ไม่รู้จักถือว่าผิด", args: [[{ title: "Brunch", day: "funday", time: "10:00" }, { title: "Quiz", day: "constructor", time: "20:00" }, { title: "Run", day: "mon", time: "06:00" }]], expected: { schedule: { mon: ["06:00 Run"] }, invalid: [0, 1] } },
      { name: "ตัดช่องว่างในชื่อ", args: [[{ title: "  Board game ", day: "wed", time: "18:00" }]], expected: { schedule: { wed: ["18:00 Board game"] }, invalid: [] } },
      { name: "ไม่มีข้อมูล", args: [[]], expected: { schedule: {}, invalid: [] } },
    ],
    wrongAnswers: [
      "const DAYS = [\"mon\", \"tue\", \"wed\", \"thu\", \"fri\", \"sat\", \"sun\"];\nfunction planWeek(activities) { const schedule = {}; const invalid = []; activities.forEach((a, i) => { if (a.title.trim() === \"\" || !DAYS.includes(a.day)) { invalid.push(i); return; } schedule[a.day] = [...(schedule[a.day] ?? []), a]; }); for (const d of Object.keys(schedule)) schedule[d] = schedule[d].sort((x, y) => x.time.localeCompare(y.time)).map((a) => a.time + \" \" + a.title.trim()); return { schedule, invalid }; }",
      "const DAYS = [\"mon\", \"tue\", \"wed\", \"thu\", \"fri\", \"sat\", \"sun\"];\nfunction planWeek(activities) { const schedule = {}; const invalid = []; activities.forEach((a, i) => { if (a.title.trim() === \"\" || !DAYS.includes(a.day) || !/^\\d{2}:\\d{2}$/.test(a.time)) { invalid.push(i); return; } schedule[a.day] = [...(schedule[a.day] ?? []), a.time + \" \" + a.title.trim()]; }); return { schedule, invalid }; }",
      "function planWeek(activities) { const schedule = {}; const invalid = []; activities.forEach((a, i) => { const ok = /^\\d{2}:\\d{2}$/.test(a.time) && Number(a.time.slice(0, 2)) <= 23 && Number(a.time.slice(3)) <= 59; if (a.title.trim() === \"\" || !ok) { invalid.push(i); return; } schedule[a.day] = [...(schedule[a.day] ?? []), a]; }); for (const d of Object.keys(schedule)) schedule[d] = [...schedule[d]].sort((x, y) => x.time.localeCompare(y.time)).map((a) => a.time + \" \" + a.title.trim()); return { schedule, invalid }; }",
    ],
  },
  buggy: "function groupByDay(activities) {\n  const groups = {};\n  for (const activity of activities) {\n    groups[activity.day].push(activity.title);\n  }\n  return groups;\n}\n\nconsole.log(groupByDay([{ title: \"Hiking\", day: \"sat\" }]));",
  bugExplanation: "TypeError: Cannot read properties of undefined (reading 'push') เพราะครั้งแรกที่เจอ sat ยังไม่มี groups.sat (undefined) แก้โดยสร้าง array ก่อนใช้: groups[activity.day] = groups[activity.day] ?? []; แล้วค่อย push หรือใช้แบบ immutable ตามตัวอย่าง",
  vocabulary: [v("pipeline", "ลำดับขั้นการแปลงข้อมูลที่ผลของขั้นหนึ่งเป็น input ของขั้นถัดไป"), v("validation", "การตรวจว่าข้อมูลถูกต้องก่อนใช้"), v("grouping", "จัดรายการเป็นกลุ่มตาม key"), v("?? (nullish coalescing)", "ใช้ค่าทางขวาเมื่อทางซ้ายเป็น null หรือ undefined"), v("regular expression", "รูปแบบสำหรับตรวจข้อความ เช่น /^\\d{2}:\\d{2}$/")],
},
];

const order = ["js-start", "js-values", "js-variables", "js-strings", "js-numbers", "js-conditions", "js-function-basics", "js-functions", "js-runtime", "js-loop-basics", "js-accumulator", "js-array-basics", "js-function-values", "js-scope", "js-objects", "js-loop-control", "js-loops", "js-nested-loops", "js-arrays", "js-errors", "js-references", "js-callbacks", "js-project-planner-1", "js-exceptions", "js-modules-json", "js-promises", "js-async", "js-project-planner-2"];
const byId = new Map([...originalTopics, javascriptStartTopic, ...javascriptBridgeTopics].map(topic => [topic.id, topic]));
export const javascriptFoundationTopics: TopicSource[] = order.map(id => {
  const topic = byId.get(id)!;
  return javascriptCheckpoints[id] ? { ...topic, checkpoint: javascriptCheckpoints[id] } : topic;
});
