import type { TopicSource } from "@/types/curriculum";

const courseId = "typescript";
const v = (a: string, b: string): [string, string] => [a, b];
const local = "ทดลองในเครื่อง: บันทึกเป็น index.ts แล้วรัน npx tsc --noEmit index.ts เพื่อตรวจ type (Node 22.18+ รัน node index.ts ได้ แต่ Node ไม่ตรวจ type)";

// Order is the learning order. Topic IDs are stored in learner progress: never rename them.
export const typescriptTopics: TopicSource[] = [
{
  id: "ts-why",
  courseId,
  unit: "ทำไมต้องมี type",
  title: "TypeScript คืออะไร: ตรวจ type ก่อนรัน",
  objective: "อธิบายความต่างระหว่าง error ตอน compile กับตอน runtime และใช้ tsc ตรวจโค้ดก่อนรัน",
  why: "บั๊กอย่างสะกดชื่อ field ผิดหรือส่ง string แทน number ใน JavaScript จะโผล่ตอนผู้ใช้กดปุ่ม TypeScript จับได้ตั้งแต่ตอนเขียน ทำให้ refactor โปรเจกต์ใหญ่ได้อย่างมั่นใจ",
  explanation: "TypeScript คือ JavaScript ที่เพิ่มการบอกชนิด (type annotation) compiler ชื่อ tsc อ่านโค้ด ตรวจว่าใช้ค่าถูกชนิด แล้วลบ type ทิ้งเหลือ JavaScript ธรรมดาให้ browser/Node รัน type จึงมีผลตอน compile เท่านั้น ไม่มีอยู่ตอน runtime ถ้าข้อมูลจากภายนอกผิดชนิด TypeScript ไม่รู้ ต้องตรวจเอง",
  language: "typescript",
  standard: "v3",
  prerequisites: ["js-functions", "js-objects"],
  example: "function totalSeats(capacity: number, extra: number): number {\n  return capacity + extra;\n}\n\nconst seats = totalSeats(8, 2);\nconsole.log(seats);\n\n// totalSeats(\"8\", 2);\n// ถ้าเอา comment ออก tsc จะแจ้ง: Argument of type 'string' is not assignable to parameter of type 'number'.",
  expectedOutput: "10",
  tracePrompt: "ถ้าเอา comment ของบรรทัด totalSeats(\"8\", 2) ออกแล้วรันด้วย JavaScript ธรรมดา (ไม่มี tsc) จะได้อะไร และ tsc จะทำอะไรกับบรรทัดนั้น",
  traceAnswer: "JavaScript จะต่อข้อความได้ \"82\" แบบเงียบ ๆ (เพราะ \"8\" + 2) ส่วน tsc จะปฏิเสธก่อนรันด้วย error ว่า string ใช้แทน number ไม่ได้ — TypeScript ย้ายบั๊กจาก runtime มาเป็นตอน compile",
  practicePrompt: "เขียน function formatPrice(amount: number, currency: string): string ที่คืนข้อความเช่น \"120 THB\" แล้วลองเรียกด้วย argument ผิดชนิดหนึ่งครั้งเพื่อดู error จาก tsc (จากนั้นลบบรรทัดที่ผิดออก) " + local,
  starter: "function formatPrice(amount, currency) {\n  return amount + \" \" + currency;\n}\n\nconsole.log(formatPrice(120, \"THB\"));",
  solution: "function formatPrice(amount: number, currency: string): string {\n  return amount + \" \" + currency;\n}\n\nconsole.log(formatPrice(120, \"THB\"));",
  buggy: "function seatsLeft(capacity: number, joined: number): number {\n  return capacity - joined;\n}\n\nconst fromForm = \"9\";\nconsole.log(seatsLeft(fromForm, 4));",
  bugExplanation: "tsc แจ้ง Argument of type 'string' is not assignable to parameter of type 'number' ที่ seatsLeft(fromForm, 4) ค่าจากฟอร์มเป็น string แก้ด้วยการแปลงและตรวจก่อนส่ง: const capacity = Number(fromForm); แล้วเช็ก Number.isNaN — TypeScript บังคับให้คิดเรื่องนี้ตั้งแต่ตอนเขียน",
  vocabulary: [v("TypeScript", "JavaScript ที่เพิ่ม type และมี compiler ตรวจก่อนรัน"), v("type annotation", "การเขียนชนิดกำกับ เช่น amount: number"), v("compile time", "ช่วงที่ tsc ตรวจและแปลงโค้ด ก่อนรันจริง"), v("runtime", "ช่วงที่โปรแกรมทำงานจริง type ไม่มีอยู่แล้ว"), v("tsc", "TypeScript compiler")],
},
{
  id: "ts-basic-types",
  courseId,
  unit: "ทำไมต้องมี type",
  title: "basic types, type inference และ any vs unknown",
  objective: "ปล่อยให้ TypeScript infer type เมื่อชัดเจน เขียน annotation เมื่อจำเป็น และเลือก unknown แทน any สำหรับข้อมูลที่ยังไม่รู้ชนิด",
  why: "เขียน type ทุกบรรทัดทำให้โค้ดรกโดยไม่จำเป็น แต่ใช้ any ทำให้ TypeScript หยุดช่วยทันที การรู้ว่าเมื่อไรควรเขียนอะไรคือทักษะหลักของการใช้ TS ในงานจริง",
  explanation: "type พื้นฐานคือ string, number, boolean, null, undefined TypeScript infer type จากค่าเริ่มต้นได้ (const count = 3 ก็รู้ว่าเป็น number) จึงเขียน annotation เฉพาะ parameter และจุดที่ค่าเริ่มต้นไม่บอกชนิด any ปิดการตรวจทั้งหมด ส่วน unknown บอกว่า “ยังไม่รู้ชนิด” และบังคับให้ตรวจก่อนใช้",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-why"],
  example: "const title = \"Hiking\";\nlet joined = 3;\njoined = joined + 1;\n\nlet note: string | null = null;\nnote = \"เอาน้ำไปด้วย\";\n\nconst fromApi: unknown = JSON.parse(\"42\");\nif (typeof fromApi === \"number\") {\n  console.log(fromApi + 1);\n}\nconsole.log(title.toUpperCase(), joined, note);",
  expectedOutput: "43\nHIKING 4 เอาน้ำไปด้วย",
  tracePrompt: "TypeScript infer type ของ title, joined และ fromApi เป็นอะไร และทำไม fromApi + 1 ต้องอยู่ใน if",
  traceAnswer: "title เป็น string (const จึงแคบลงเป็นค่าตายตัว \"Hiking\" ด้วย), joined เป็น number, fromApi เราประกาศเป็น unknown เอง — ใช้ + 1 กับ unknown ไม่ได้จนกว่าจะพิสูจน์ชนิด if (typeof fromApi === \"number\") ทำให้ TypeScript รู้ว่าข้างใน if เป็น number (narrowing)",
  practicePrompt: "รับค่า input: unknown แล้วเขียน toCount(input: unknown): number ที่คืนตัวเลขเมื่อ input เป็น number ที่ไม่ติดลบ เมื่อเป็น string ที่แปลงได้ให้แปลง และนอกนั้นคืน 0 โดยห้ามใช้ any " + local,
  starter: "function toCount(input: any): number {\n  return input;\n}",
  solution: "function toCount(input: unknown): number {\n  if (typeof input === \"number\" && input >= 0) return input;\n  if (typeof input === \"string\") {\n    const parsed = Number(input);\n    if (!Number.isNaN(parsed) && parsed >= 0) return parsed;\n  }\n  return 0;\n}\n\nconsole.log(toCount(5), toCount(\"7\"), toCount(\"abc\"), toCount(null));",
  buggy: "function shout(value: any) {\n  return value.toUpperCase();\n}\n\nconsole.log(shout(42));",
  bugExplanation: "tsc ไม่เตือนเพราะ any ปิดการตรวจ แต่ตอนรันได้ TypeError: value.toUpperCase is not a function เปลี่ยนเป็น value: unknown แล้ว tsc จะบังคับให้ตรวจ if (typeof value === \"string\") ก่อนเรียก toUpperCase — หรือถ้าตั้งใจรับแค่ string ก็เขียน value: string ตรง ๆ",
  vocabulary: [v("type inference", "TypeScript เดาชนิดจากค่าให้เอง"), v("union type", "ชนิดที่เป็นได้หลายแบบ เช่น string | null"), v("any", "ปิดการตรวจ type ของค่านั้น"), v("unknown", "ชนิดที่ยังไม่รู้ ต้องตรวจก่อนใช้"), v("narrowing", "การทำให้ชนิดแคบลงด้วยการตรวจ เช่น typeof")],
},
{
  id: "ts-functions",
  courseId,
  unit: "Functions และ objects",
  title: "type ของ function: parameter, return, optional และ default",
  objective: "กำหนด type ให้ parameter และค่าที่ return ใช้ optional/default parameter และเลือก void เมื่อ function ไม่คืนค่า",
  why: "function คือสัญญาระหว่างคนเขียนกับคนเรียก type ของ parameter และ return ทำให้สัญญานั้นถูกตรวจทุกครั้งที่เรียก โดยเฉพาะเมื่อ function ถูกใช้หลายที่ในโปรเจกต์",
  explanation: "เขียน type ให้ parameter ทุกตัว ส่วน return type infer ได้แต่ควรเขียนให้ function ที่ export หรือซับซ้อน เพื่อให้ tsc เตือนเมื่อเรา return ผิดชนิดเอง parameter ที่ตามด้วย ? เป็น optional (ค่าอาจเป็น undefined) default parameter ใส่ค่าเริ่มต้นให้ void ใช้กับ function ที่ไม่ return ค่า type ของ function เองเขียนได้เป็น (a: number) => string",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-basic-types"],
  example: "function greet(name: string, title?: string): string {\n  return title ? title + \" \" + name : name;\n}\n\nfunction perPerson(total: number, people: number = 2): number {\n  return Math.ceil(total / people);\n}\n\nfunction logLine(message: string): void {\n  console.log(\"> \" + message);\n}\n\nconst format: (amount: number) => string = (amount) => amount + \" บาท\";\n\nlogLine(greet(\"ซี\"));\nlogLine(greet(\"ซี\", \"คุณ\"));\nlogLine(format(perPerson(450)));\nlogLine(format(perPerson(450, 4)));",
  expectedOutput: "> ซี\n> คุณ ซี\n> 225 บาท\n> 113 บาท",
  tracePrompt: "ในการเรียก greet(\"ซี\") ค่า title คืออะไร และ perPerson(450) ใช้ people เท่าไร",
  traceAnswer: "title เป็น undefined เพราะไม่ได้ส่ง (optional) จึงเข้ากิ่งที่คืน name อย่างเดียว perPerson(450) ใช้ค่า default 2 ได้ Math.ceil(225) = 225 ส่วน perPerson(450, 4) ได้ Math.ceil(112.5) = 113",
  practicePrompt: "เขียน applyDiscount(price: number, percent?: number): number ที่ถ้าไม่ส่ง percent ให้ลด 0% คืนราคาหลังลดแบบปัดลงเป็นจำนวนเต็ม และเขียน type ของตัวแปร calc ให้เป็น function ที่รับ number คืน number แล้ว assign applyDiscount ให้ calc ได้ " + local,
  starter: "function applyDiscount(price, percent) {\n  return price;\n}\n\nconst calc = applyDiscount;\nconsole.log(calc(1000));",
  solution: "function applyDiscount(price: number, percent: number = 0): number {\n  return Math.floor(price * (100 - percent) / 100);\n}\n\nconst calc: (price: number) => number = applyDiscount;\nconsole.log(calc(1000), applyDiscount(999, 15));",
  buggy: "function average(scores: number[]): number {\n  if (scores.length === 0) {\n    console.log(\"ไม่มีคะแนน\");\n    return;\n  }\n  return scores.reduce((sum, s) => sum + s, 0) / scores.length;\n}",
  bugExplanation: "tsc แจ้ง Type 'undefined' is not assignable to type 'number' ที่ return; เพราะ return ว่างคืน undefined แต่สัญญาบอกว่าคืน number แก้โดยตัดสินสัญญาให้ชัด: คืน 0 สำหรับรายการว่าง หรือเปลี่ยน return type เป็น number | null แล้ว return null; — การเขียน return type ทำให้ tsc จับกรณีที่ลืมนี้ได้",
  vocabulary: [v("return type", "ชนิดของค่าที่ function คืน"), v("optional parameter", "parameter ที่ไม่ส่งก็ได้ เขียนด้วย ?"), v("default parameter", "parameter ที่มีค่าเริ่มต้น"), v("void", "บอกว่า function ไม่คืนค่าที่ใช้ได้"), v("function type", "ชนิดของ function เช่น (a: number) => string")],
},
{
  id: "ts-object-types",
  courseId,
  unit: "Functions และ objects",
  title: "type alias, interface, optional และ readonly property",
  objective: "อธิบายรูปร่างของ object ด้วย type alias หรือ interface กำหนด property ที่ optional/readonly และให้ tsc จับ field ที่สะกดผิดหรือขาด",
  why: "ข้อมูลกิจกรรม สมาชิก และ response จาก API ล้วนเป็น object ที่ต้องมี field ครบและถูกชนิด การนิยามรูปร่างครั้งเดียวแล้วใช้ทั้งโปรเจกต์ทำให้แก้ field ทีเดียวแล้ว tsc บอกทุกจุดที่ต้องตามแก้",
  explanation: "type Activity = { title: string; capacity: number } หรือ interface Activity { ... } ใช้อธิบายรูปร่าง object ได้เหมือนกันในกรณีทั่วไป property ที่ตามด้วย ? อาจไม่มี readonly ห้าม assign ใหม่ (ตอน compile) TypeScript ตรวจแบบ structural: object ไหนมี field ที่ต้องการครบก็ใช้ได้ แต่ object literal ที่มี field เกิน (excess property) จะถูกเตือนเพราะมักเป็นการสะกดผิด",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-functions", "js-objects"],
  example: "type Activity = {\n  readonly id: number;\n  title: string;\n  capacity: number;\n  joined: number;\n  place?: string;\n};\n\nfunction describe(activity: Activity): string {\n  const where = activity.place ?? \"ยังไม่กำหนดสถานที่\";\n  return activity.title + \" (\" + activity.joined + \"/\" + activity.capacity + \") \" + where;\n}\n\nconst hiking: Activity = { id: 1, title: \"Hiking\", capacity: 8, joined: 3 };\nconst cafe: Activity = { id: 2, title: \"Cafe hop\", capacity: 5, joined: 5, place: \"นิมมาน\" };\n\nconsole.log(describe(hiking));\nconsole.log(describe(cafe));",
  expectedOutput: "Hiking (3/8) ยังไม่กำหนดสถานที่\nCafe hop (5/5) นิมมาน",
  tracePrompt: "ถ้าเพิ่มบรรทัด hiking.id = 5; และสร้าง { id: 3, title: \"Movie\", capacity: 4, joind: 1 } เป็น Activity tsc จะแจ้งอะไรบ้าง",
  traceAnswer: "hiking.id = 5 ผิดเพราะ id เป็น readonly ส่วน object ที่สะกด joind ผิดจะได้สอง error: ขาด joined (required) และ joind เป็น property เกินที่ Activity ไม่มี — tsc จับคำสะกดผิดได้ก่อนรัน",
  practicePrompt: "นิยาม type Member ที่มี id (readonly number), name (string), age (number) และ nickname (optional string) แล้วเขียน displayName(member: Member): string ที่คืน nickname ถ้ามี ไม่งั้นคืน name ลองสร้าง Member ที่สะกด field ผิดหนึ่งครั้งเพื่อดู error " + local,
  starter: "// นิยาม type Member ที่นี่\n\nfunction displayName(member) {\n  return member.name;\n}\n\nconsole.log(displayName({ id: 1, name: \"Sea\", age: 20, nickname: \"ซี\" }));",
  solution: "type Member = {\n  readonly id: number;\n  name: string;\n  age: number;\n  nickname?: string;\n};\n\nfunction displayName(member: Member): string {\n  return member.nickname ?? member.name;\n}\n\nconsole.log(displayName({ id: 1, name: \"Sea\", age: 20, nickname: \"ซี\" }));\nconsole.log(displayName({ id: 2, name: \"Ton\", age: 21 }));",
  buggy: "interface Activity {\n  title: string;\n  capacity: number;\n}\n\nfunction isFull(activity: Activity): boolean {\n  return activity.joined >= activity.capacity;\n}",
  bugExplanation: "tsc แจ้ง Property 'joined' does not exist on type 'Activity' เพราะ interface ไม่ได้ประกาศ joined แก้ที่ต้นทางโดยเพิ่ม joined: number ลงใน interface (ไม่ใช่ใช้ any หรือ as เพื่อเงียบ error) — type คือสัญญา ถ้าโค้ดต้องใช้ field ไหน สัญญาต้องมี field นั้น",
  vocabulary: [v("type alias", "ตั้งชื่อให้ type ด้วยคำว่า type"), v("interface", "ประกาศรูปร่างของ object ขยายด้วย extends ได้"), v("optional property", "field ที่อาจไม่มี เขียนด้วย ?"), v("readonly", "ห้าม assign field นั้นใหม่หลังสร้าง"), v("structural typing", "ตัดสินว่าใช้ได้จากรูปร่าง ไม่ใช่ชื่อ type"), v("excess property check", "การเตือนเมื่อ object literal มี field ที่ type ไม่มี")],
},
{
  id: "ts-arrays-tuples",
  courseId,
  unit: "Functions และ objects",
  title: "array, readonly array และ tuple",
  objective: "กำหนด type ของ array ใช้ readonly array เพื่อกันการแก้ input และใช้ tuple เมื่อตำแหน่งมีความหมายตายตัว",
  why: "function ที่รับรายการแล้วเผลอ sort หรือ push ทำให้ข้อมูลของคนเรียกเปลี่ยน readonly array ให้ tsc จับเรื่องนี้ได้ และ tuple ใช้กับค่าที่มาเป็นคู่ เช่น [ชื่อ, คะแนน] จาก library หลายตัว",
  explanation: "number[] หรือ Array<number> คือ array ของ number readonly number[] ห้ามเรียก method ที่แก้ array (push, sort, splice) ตอน compile tuple เช่น [string, number] กำหนดจำนวนสมาชิกและชนิดตามตำแหน่ง destructure ได้: const [name, score] = pair; map/filter บน array ที่มี type ให้ผลที่มี type ตามมาเอง",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-object-types", "js-references"],
  example: "type Vote = [title: string, count: number];\n\nfunction topVote(votes: readonly Vote[]): Vote | undefined {\n  return [...votes].sort((a, b) => b[1] - a[1])[0];\n}\n\nconst votes: Vote[] = [[\"Hiking\", 5], [\"Board game\", 9], [\"Movie\", 7]];\nconst best = topVote(votes);\nif (best) {\n  const [title, count] = best;\n  console.log(title, count);\n}\nconsole.log(votes[0][0]);\nconst counts: number[] = votes.map((vote) => vote[1]);\nconsole.log(counts);",
  expectedOutput: "Board game 9\nHiking\n[5,9,7]",
  tracePrompt: "ถ้าใน topVote เขียน votes.sort(...) ตรง ๆ แทน [...votes].sort(...) tsc จะแจ้งอะไร และทำไม votes[0][0] ยังเป็น Hiking",
  traceAnswer: "tsc แจ้งว่า Property 'sort' does not exist on type 'readonly Vote[]' เพราะ readonly array ห้ามเรียก method ที่แก้ array ส่วน votes[0][0] ยังเป็น Hiking เพราะ sort ทำกับสำเนา [...votes] — readonly ช่วยบังคับนิสัยที่เรียนในบท reference",
  practicePrompt: "เขียน summarize(scores: readonly number[]): [min: number, max: number] ที่คืน tuple ของค่าน้อยสุดและมากสุด (ถ้า array ว่างคืน [0, 0]) โดยไม่แก้ array ที่รับเข้ามา แล้ว destructure ผลลัพธ์มาพิมพ์ " + local,
  starter: "function summarize(scores) {\n  scores.sort((a, b) => a - b);\n  return [scores[0], scores[scores.length - 1]];\n}\n\nconsole.log(summarize([70, 92, 55]));",
  solution: "function summarize(scores: readonly number[]): [min: number, max: number] {\n  if (scores.length === 0) return [0, 0];\n  return [Math.min(...scores), Math.max(...scores)];\n}\n\nconst [low, high] = summarize([70, 92, 55]);\nconsole.log(low, high);",
  buggy: "const pair: [string, number] = [\"Hiking\", 5];\nconst [count, title] = pair;\nconsole.log(title.toUpperCase(), count + 1);",
  bugExplanation: "tsc แจ้ง Property 'toUpperCase' does not exist on type 'number' เพราะ destructure สลับตำแหน่ง: count ได้ \"Hiking\" (string) และ title ได้ 5 (number) แก้เป็น const [title, count] = pair; — tuple ทำให้ลำดับมีความหมาย และ tsc ตรวจลำดับให้",
  vocabulary: [v("array type", "ชนิดของ array เช่น number[]"), v("readonly array", "array ที่ห้ามแก้ผ่าน type นี้"), v("tuple", "array ที่จำนวนและชนิดแต่ละตำแหน่งตายตัว"), v("labeled tuple", "tuple ที่ตั้งชื่อตำแหน่ง เช่น [title: string, count: number]")],
},
{
  id: "ts-unions-literals",
  courseId,
  unit: "Unions และ narrowing",
  title: "union types และ literal types",
  objective: "ใช้ union และ literal types จำกัดค่าที่เป็นไปได้ เช่นสถานะหรือประเภทกิจกรรม แทนการใช้ string อิสระ",
  why: "status: string ยอมรับ \"pendng\" ที่สะกดผิดได้ ส่วน status: \"pending\" | \"confirmed\" | \"cancelled\" ให้ tsc จับคำผิด และ editor แนะนำค่าที่ถูกได้ทันที",
  explanation: "union A | B หมายถึงเป็น A หรือ B ก็ได้ literal type คือ type ที่เป็นค่าตายตัว เช่น \"online\" รวมกันได้เป็นชุดตัวเลือก: type Kind = \"online\" | \"onsite\" เมื่อเป็น union จะใช้ได้เฉพาะสิ่งที่ทุกสมาชิกมีร่วมกัน จนกว่าจะ narrowing ใช้ union ของ literal แทน enum ได้ในกรณีส่วนใหญ่ และรันใน Node แบบ type stripping ได้",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-basic-types", "ts-object-types"],
  example: "type Status = \"pending\" | \"confirmed\" | \"cancelled\";\n\nfunction label(status: Status): string {\n  if (status === \"pending\") return \"รอยืนยัน\";\n  if (status === \"confirmed\") return \"ยืนยันแล้ว\";\n  return \"ยกเลิก\";\n}\n\nfunction formatId(id: number | string): string {\n  return \"#\" + String(id).padStart(4, \"0\");\n}\n\nconsole.log(label(\"pending\"), label(\"cancelled\"));\nconsole.log(formatId(42), formatId(\"7\"));",
  expectedOutput: "รอยืนยัน ยกเลิก\n#0042 #0007",
  tracePrompt: "label(\"pendng\") จะผ่าน tsc ไหม และใน formatId ทำไมต้องใช้ String(id) ก่อน padStart",
  traceAnswer: "ไม่ผ่าน: \"pendng\" ไม่อยู่ใน Status tsc แจ้งทันที ส่วน id เป็น number | string และ padStart มีเฉพาะ string — ใช้ method ของสมาชิกตัวใดตัวหนึ่งตรง ๆ ไม่ได้ จึงแปลงเป็น string ทั้งหมดก่อน",
  practicePrompt: "นิยาม type Role = \"owner\" | \"member\" | \"guest\" แล้วเขียน canEdit(role: Role): boolean ที่ให้แก้ได้เฉพาะ owner และ member จากนั้นลองเรียกด้วย \"admin\" เพื่อดู error " + local,
  starter: "function canEdit(role: string): boolean {\n  return role !== \"guest\";\n}\n\nconsole.log(canEdit(\"owner\"), canEdit(\"guest\"));",
  solution: "type Role = \"owner\" | \"member\" | \"guest\";\n\nfunction canEdit(role: Role): boolean {\n  return role === \"owner\" || role === \"member\";\n}\n\nconsole.log(canEdit(\"owner\"), canEdit(\"guest\"));",
  buggy: "type Kind = \"online\" | \"onsite\";\n\nlet kind = \"online\";\nfunction show(k: Kind) {\n  console.log(k);\n}\nshow(kind);",
  bugExplanation: "tsc แจ้ง Argument of type 'string' is not assignable to parameter of type 'Kind' เพราะ let kind = \"online\" ถูก infer เป็น string (let เปลี่ยนค่าได้) แก้ด้วย let kind: Kind = \"online\"; หรือใช้ const kind = \"online\" ซึ่ง infer เป็น literal \"online\"",
  vocabulary: [v("union type", "ชนิดที่เป็นได้หลายแบบ A | B"), v("literal type", "type ที่เป็นค่าตายตัว เช่น \"online\" หรือ 3"), v("widening", "การที่ let ถูก infer เป็นชนิดกว้าง เช่น string แทน \"online\""), v("enum", "ชุดค่าคงที่แบบมี runtime code ใน TS (Node type stripping ไม่รองรับ)")],
},
{
  id: "ts-narrowing",
  courseId,
  unit: "Unions และ narrowing",
  title: "narrowing, discriminated union และ exhaustive check",
  objective: "ทำให้ union แคบลงด้วย typeof, in, การเทียบค่า และ field discriminant เขียน type predicate และใช้ never ตรวจว่าจัดการครบทุกกรณี",
  why: "ข้อมูลจริงมีหลายรูปแบบ เช่นกิจกรรมออนไลน์มีลิงก์ แต่กิจกรรมในสถานที่มีห้อง narrowing ทำให้ใช้ field ของแต่ละแบบได้อย่างปลอดภัย และ exhaustive check บอกทุกจุดที่ต้องแก้เมื่อเพิ่มรูปแบบใหม่",
  explanation: "narrowing คือการตรวจที่ TypeScript เข้าใจ แล้วจำกัด type ในกิ่งนั้น: typeof x === \"string\", \"url\" in x, x === null discriminated union คือ union ของ object ที่มี field ร่วม (เช่น kind) เป็น literal ต่างกัน ตรวจ kind แล้วได้ type ของแบบนั้นทันที type predicate (value is T) ให้ function ตรวจของเรา narrow ได้ ในกิ่งสุดท้ายถ้าทุกกรณีถูกจัดการแล้ว ค่าจะเป็น never — assign ให้ตัวแปร never เพื่อให้ tsc เตือนเมื่อมีกรณีใหม่ที่ลืม",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-unions-literals"],
  example: "type Online = { kind: \"online\"; title: string; url: string };\ntype Onsite = { kind: \"onsite\"; title: string; room: string };\ntype Activity = Online | Onsite;\n\nfunction where(activity: Activity): string {\n  switch (activity.kind) {\n    case \"online\":\n      return activity.title + \" — \" + activity.url;\n    case \"onsite\":\n      return activity.title + \" — ห้อง \" + activity.room;\n    default: {\n      const unreachable: never = activity;\n      return unreachable;\n    }\n  }\n}\n\nfunction isOnline(activity: Activity): activity is Online {\n  return activity.kind === \"online\";\n}\n\nconst list: Activity[] = [\n  { kind: \"online\", title: \"Code review\", url: \"meet.example/abc\" },\n  { kind: \"onsite\", title: \"Board game\", room: \"DII-201\" },\n];\nlist.forEach((activity) => console.log(where(activity)));\nconsole.log(list.filter(isOnline).map((activity) => activity.url));",
  expectedOutput: "Code review — meet.example/abc\nBoard game — ห้อง DII-201\n[\"meet.example/abc\"]",
  tracePrompt: "ถ้าเพิ่ม type Hybrid = { kind: \"hybrid\"; title: string; url: string; room: string } เข้าไปใน Activity แต่ไม่แก้ where tsc จะแจ้งที่บรรทัดไหน เพราะอะไร",
  traceAnswer: "แจ้งที่ const unreachable: never = activity; เพราะเมื่อมี hybrid กิ่ง default จะไม่ใช่ never อีกต่อไป (activity เป็น Hybrid) tsc จึงชี้ว่ายังไม่ได้จัดการกรณีใหม่ — นี่คือ exhaustive check",
  practicePrompt: "เพิ่ม Hybrid เข้าไปใน union แล้วแก้ where ให้คืน \"title — url + ห้อง room\" จากนั้นเขียน type predicate hasRoom(activity): activity is Onsite | Hybrid และใช้กับ filter " + local,
  starter: "type Online = { kind: \"online\"; title: string; url: string };\ntype Onsite = { kind: \"onsite\"; title: string; room: string };\n// เพิ่ม Hybrid\ntype Activity = Online | Onsite;\n\nfunction where(activity: Activity): string {\n  switch (activity.kind) {\n    case \"online\":\n      return activity.title + \" — \" + activity.url;\n    case \"onsite\":\n      return activity.title + \" — ห้อง \" + activity.room;\n    default: {\n      const unreachable: never = activity;\n      return unreachable;\n    }\n  }\n}",
  solution: "type Online = { kind: \"online\"; title: string; url: string };\ntype Onsite = { kind: \"onsite\"; title: string; room: string };\ntype Hybrid = { kind: \"hybrid\"; title: string; url: string; room: string };\ntype Activity = Online | Onsite | Hybrid;\n\nfunction where(activity: Activity): string {\n  switch (activity.kind) {\n    case \"online\":\n      return activity.title + \" — \" + activity.url;\n    case \"onsite\":\n      return activity.title + \" — ห้อง \" + activity.room;\n    case \"hybrid\":\n      return activity.title + \" — \" + activity.url + \" + ห้อง \" + activity.room;\n    default: {\n      const unreachable: never = activity;\n      return unreachable;\n    }\n  }\n}\n\nfunction hasRoom(activity: Activity): activity is Onsite | Hybrid {\n  return activity.kind === \"onsite\" || activity.kind === \"hybrid\";\n}\n\nconst list: Activity[] = [\n  { kind: \"hybrid\", title: \"Demo day\", url: \"meet.example/demo\", room: \"DII-101\" },\n  { kind: \"online\", title: \"Code review\", url: \"meet.example/abc\" },\n];\nconsole.log(list.map(where));\nconsole.log(list.filter(hasRoom).map((activity) => activity.room));",
  buggy: "type Member = { name: string; tags: string[] | null };\n\nfunction label(member: Member): string {\n  if (typeof member.tags === \"object\") {\n    return member.name + \" มี \" + member.tags.length + \" แท็ก\";\n  }\n  return member.name;\n}",
  bugExplanation: "tsc แจ้ง 'member.tags' is possibly 'null' เพราะ typeof null ก็คือ \"object\" การตรวจ typeof === \"object\" จึงไม่ได้ตัด null ออก ถ้า tsc ไม่เตือน (เช่นใช้ any) โค้ดนี้จะพังตอนรันเมื่อ tags เป็น null แก้ด้วยการตรวจที่ตรงความหมาย: if (member.tags !== null) หรือ if (Array.isArray(member.tags)) ซึ่ง TypeScript narrow ให้ถูกต้อง",
  vocabulary: [v("narrowing", "การจำกัด type ในกิ่งหลังจากตรวจ"), v("discriminated union", "union ของ object ที่แยกกันด้วย field literal ร่วม เช่น kind"), v("type predicate", "return type แบบ value is T ที่บอก tsc ว่าการตรวจนี้ narrow อย่างไร"), v("never", "type ที่ไม่มีค่าใดเป็นได้ ใช้ตรวจว่าครบทุกกรณี"), v("exhaustive check", "การให้ tsc ยืนยันว่าทุกกรณีของ union ถูกจัดการ")],
},
{
  id: "ts-null-safety",
  courseId,
  unit: "Unions และ narrowing",
  title: "null safety: strictNullChecks, ?. และ ??",
  objective: "จัดการค่าที่อาจเป็น null/undefined ด้วยการตรวจ, optional chaining และ nullish coalescing และหลีกเลี่ยง non-null assertion ที่ซ่อนบั๊ก",
  why: "TypeError: Cannot read properties of undefined คือ error ที่พบบ่อยที่สุดใน JavaScript โหมด strict ของ TypeScript บังคับให้จัดการกรณีที่ค่าอาจไม่มีตั้งแต่ตอนเขียน",
  explanation: "เมื่อเปิด strict (รวม strictNullChecks) type string ไม่รวม null/undefined ต้องเขียน string | null เองเมื่อค่าอาจไม่มี และต้องตรวจก่อนใช้ ?. อ่าน field ต่อเมื่อค่าทางซ้ายไม่ใช่ null/undefined (ไม่งั้นได้ undefined) ?? ให้ค่าแทนเมื่อทางซ้ายเป็น null/undefined เท่านั้น (ต่างจาก || ที่แทนทุก falsy รวม 0 และ \"\") ! ท้ายค่า (non-null assertion) บอก tsc ให้เชื่อว่าไม่ใช่ null โดยไม่ตรวจจริง ใช้เมื่อพิสูจน์ได้เท่านั้น",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-narrowing"],
  example: "type Member = { name: string; contact?: { line?: string }; seats: number | null };\n\nconst members: Member[] = [\n  { name: \"ซี\", contact: { line: \"sea.k\" }, seats: 2 },\n  { name: \"ต้น\", seats: 0 },\n  { name: \"ฝน\", contact: {}, seats: null },\n];\n\nfor (const member of members) {\n  const line = member.contact?.line ?? \"ไม่มี LINE\";\n  const seats = member.seats ?? 1;\n  const withOr = member.seats || 1;\n  console.log(member.name, line, seats, withOr);\n}\n\nconst found = members.find((member) => member.name === \"บี\");\nconsole.log(found?.name ?? \"ไม่พบสมาชิก\");",
  expectedOutput: "ซี sea.k 2 2\nต้น ไม่มี LINE 0 1\nฝน ไม่มี LINE 1 1\nไม่พบสมาชิก",
  tracePrompt: "ทำไมแถวของ “ต้น” ได้ seats = 0 แต่ withOr = 1 และถ้าเขียน found.name โดยไม่มี ?. tsc จะแจ้งอะไร",
  traceAnswer: "?? แทนค่าเฉพาะ null/undefined ส่วน 0 ไม่ใช่ จึงคง 0 ไว้ แต่ || มองว่า 0 เป็น falsy จึงแทนเป็น 1 ซึ่งผิดความหมาย find คืน Member | undefined การเขียน found.name ตรง ๆ tsc จะแจ้ง 'found' is possibly 'undefined'",
  practicePrompt: "เขียน contactLabel(member: Member): string ที่คืน \"LINE: …\" ถ้ามี line, \"ไม่มีข้อมูลติดต่อ\" ถ้าไม่มี contact เลย และ \"ยังไม่ใส่ LINE\" ถ้ามี contact แต่ไม่มี line โดยไม่ใช้ ! เลย " + local,
  starter: "type Member = { name: string; contact?: { line?: string } };\n\nfunction contactLabel(member: Member): string {\n  return \"LINE: \" + member.contact!.line!;\n}",
  solution: "type Member = { name: string; contact?: { line?: string } };\n\nfunction contactLabel(member: Member): string {\n  if (!member.contact) return \"ไม่มีข้อมูลติดต่อ\";\n  return member.contact.line ? \"LINE: \" + member.contact.line : \"ยังไม่ใส่ LINE\";\n}\n\nconsole.log(contactLabel({ name: \"ซี\", contact: { line: \"sea.k\" } }));\nconsole.log(contactLabel({ name: \"ต้น\" }));\nconsole.log(contactLabel({ name: \"ฝน\", contact: {} }));",
  buggy: "const params = new Map<string, string>([[\"page\", \"2\"]]);\nconst limit = Number(params.get(\"limit\")!);\nconsole.log(\"แสดง\", limit, \"รายการ\");",
  bugExplanation: "tsc ผ่านเพราะ ! บอกให้เชื่อว่ามีค่า แต่ตอนรัน params.get(\"limit\") เป็น undefined แล้ว Number(undefined) ได้ NaN จึงพิมพ์ “แสดง NaN รายการ” แก้โดยจัดการกรณีไม่มีค่าจริง: const limit = Number(params.get(\"limit\") ?? \"20\"); — ! เงียบ error ได้ แต่ไม่ทำให้ค่ามีอยู่จริง",
  vocabulary: [v("strictNullChecks", "โหมดที่ทำให้ null/undefined ต้องประกาศและตรวจเอง"), v("optional chaining ?.", "อ่านต่อเมื่อค่าทางซ้ายไม่ใช่ null/undefined"), v("nullish coalescing ??", "ใช้ค่าทางขวาเมื่อทางซ้ายเป็น null/undefined"), v("non-null assertion !", "บอก tsc ว่าไม่ใช่ null โดยไม่ตรวจจริง"), v("possibly undefined", "ข้อความเตือนว่าค่าอาจไม่มี ต้องตรวจก่อนใช้")],
},
{
  id: "ts-generics",
  courseId,
  unit: "Reuse",
  title: "generics และ generic constraints",
  objective: "เขียน function ที่ใช้ได้กับหลายชนิดโดยไม่เสีย type ด้วย type parameter <T> และจำกัดด้วย extends เมื่อ function ต้องใช้ field บางตัว",
  why: "function อย่าง “เอาตัวแรก”, “จัดกลุ่มตาม key” หรือ response wrapper ของ API ใช้กับข้อมูลหลายชนิด ถ้าใช้ any จะเสีย type ทันที generics ให้ทั้งความยืดหยุ่นและความปลอดภัย",
  explanation: "type parameter <T> เป็นตัวแปรของ type ที่ถูกกำหนดตอนเรียก มักถูก infer จาก argument function first<T>(items: T[]): T | undefined คืนชนิดเดียวกับสมาชิก constraint <T extends { id: number }> บังคับว่า T ต้องมีอย่างน้อย field id ทำให้ใช้ item.id ข้างในได้ keyof T คือ union ของชื่อ field ใน T ใช้กับ <K extends keyof T> เพื่อรับชื่อ field ที่มีจริง",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-arrays-tuples", "ts-narrowing"],
  example: "function first<T>(items: readonly T[]): T | undefined {\n  return items[0];\n}\n\nfunction byId<T extends { id: number }>(items: readonly T[], id: number): T | undefined {\n  return items.find((item) => item.id === id);\n}\n\nfunction pluck<T, K extends keyof T>(items: readonly T[], key: K): T[K][] {\n  return items.map((item) => item[key]);\n}\n\nconst activities = [\n  { id: 1, title: \"Hiking\", capacity: 8 },\n  { id: 2, title: \"Movie\", capacity: 4 },\n];\n\nconsole.log(first([\"a\", \"b\"]), first<number>([]));\nconsole.log(byId(activities, 2)?.title);\nconsole.log(pluck(activities, \"capacity\"));",
  expectedOutput: "a undefined\nMovie\n[8,4]",
  tracePrompt: "TypeScript infer T ของ first([\"a\", \"b\"]) เป็นอะไร และ pluck(activities, \"capacity\") มี type ผลลัพธ์เป็นอะไร ถ้าส่ง \"price\" แทนจะเกิดอะไร",
  traceAnswer: "T เป็น string ผลจึงเป็น string | undefined ส่วน pluck ได้ number[] (T[\"capacity\"] คือ number) ถ้าส่ง \"price\" tsc แจ้งว่า \"price\" ไม่อยู่ใน keyof ของ activity (\"id\" | \"title\" | \"capacity\")",
  practicePrompt: "เขียน groupBy<T, K extends keyof T>(items: readonly T[], key: K): Record<string, T[]> ที่จัดกลุ่มตามค่า String(item[key]) แล้วลองใช้กับรายการกิจกรรมที่มี field kind " + local,
  starter: "function groupBy(items: any[], key: string): any {\n  const groups: any = {};\n  for (const item of items) {\n    groups[item[key]] = [...(groups[item[key]] ?? []), item];\n  }\n  return groups;\n}",
  solution: "function groupBy<T, K extends keyof T>(items: readonly T[], key: K): Record<string, T[]> {\n  const groups: Record<string, T[]> = {};\n  for (const item of items) {\n    const groupKey = String(item[key]);\n    groups[groupKey] = [...(groups[groupKey] ?? []), item];\n  }\n  return groups;\n}\n\nconst grouped = groupBy([\n  { title: \"Hiking\", kind: \"onsite\" },\n  { title: \"Code review\", kind: \"online\" },\n  { title: \"Movie\", kind: \"onsite\" },\n], \"kind\");\nconsole.log(Object.keys(grouped), grouped.onsite.length);",
  buggy: "function longest<T>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}",
  bugExplanation: "tsc แจ้ง Property 'length' does not exist on type 'T' เพราะ T เป็นอะไรก็ได้ (รวม number) แก้ด้วย constraint: function longest<T extends { length: number }>(a: T, b: T): T ซึ่งรับได้ทั้ง string และ array แต่ไม่รับ number",
  vocabulary: [v("generic", "function/type ที่รับ type เป็น parameter"), v("type parameter", "ตัวแปรของ type เช่น T"), v("constraint", "เงื่อนไข T extends ... ที่จำกัด type ที่รับได้"), v("keyof", "union ของชื่อ field ใน type"), v("indexed access type", "T[K] คือ type ของ field K ใน T"), v("Record<K, V>", "object ที่ key เป็น K และค่าเป็น V")],
},
{
  id: "ts-utility-types",
  courseId,
  unit: "Reuse",
  title: "utility types: Partial, Pick, Omit, Record และ ReturnType",
  objective: "สร้าง type ใหม่จาก type เดิมด้วย utility types เพื่อให้ type ของ input ฟอร์ม, การอัปเดต และ response สอดคล้องกับ model หลัก",
  why: "ถ้าเขียน type ของ “ข้อมูลสำหรับสร้าง” และ “ข้อมูลสำหรับแก้” แยกด้วยมือ วันหนึ่งเพิ่ม field ใน model แล้วลืมแก้อีกที่ utility types ทำให้ทุก type ผูกกับต้นฉบับเดียว",
  explanation: "Partial<T> ทำให้ทุก field optional (เหมาะกับข้อมูลอัปเดต) Pick<T, \"a\" | \"b\"> เลือกบาง field Omit<T, \"id\"> ตัดบาง field (เหมาะกับข้อมูลสร้างใหม่ที่ยังไม่มี id) Record<K, V> สร้าง object type จาก key และค่า ReturnType<typeof fn> ดึง type ของค่าที่ function คืน utility types มีผลเฉพาะตอน compile เหมือน type อื่น ๆ",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-generics"],
  example: "type Activity = { id: number; title: string; capacity: number; joined: number };\n\ntype NewActivity = Omit<Activity, \"id\" | \"joined\">;\ntype ActivityPatch = Partial<Omit<Activity, \"id\">>;\ntype Preview = Pick<Activity, \"title\" | \"capacity\">;\n\nlet nextId = 1;\nfunction create(input: NewActivity): Activity {\n  return { ...input, id: nextId++, joined: 0 };\n}\n\nfunction update(activity: Activity, patch: ActivityPatch): Activity {\n  return { ...activity, ...patch };\n}\n\nconst hiking = create({ title: \"Hiking\", capacity: 8 });\nconst changed = update(hiking, { capacity: 10 });\nconst preview: Preview = { title: changed.title, capacity: changed.capacity };\nconst countsByKind: Record<\"online\" | \"onsite\", number> = { online: 0, onsite: 1 };\n\nconsole.log(changed);\nconsole.log(preview, countsByKind.onsite);",
  expectedOutput: "{\"title\":\"Hiking\",\"capacity\":10,\"id\":1,\"joined\":0}\n{\"title\":\"Hiking\",\"capacity\":10} 1",
  tracePrompt: "ถ้าเพิ่ม field date: string ลงใน Activity type ไหนบ้างต้องแก้ด้วยมือ และบรรทัด create({ title: \"Hiking\", capacity: 8 }) จะเป็นอย่างไร",
  traceAnswer: "ไม่ต้องแก้ type ไหนด้วยมือ เพราะทั้งหมดสร้างจาก Activity แต่ create(...) จะ error ว่าขาด date เพราะ NewActivity ได้ field date มาด้วยอัตโนมัติ — tsc ชี้ทุกจุดที่ต้องส่งค่าใหม่",
  practicePrompt: "จาก type Member = { id: number; name: string; age: number; email: string } เขียน type MemberForm (ไม่มี id) และ type PublicMember (มีแค่ id กับ name) ด้วย utility types แล้วเขียน toPublic(member: Member): PublicMember " + local,
  starter: "type Member = { id: number; name: string; age: number; email: string };\n\ntype MemberForm = { name: string; age: number; email: string };\ntype PublicMember = { id: number; name: string };\n\nfunction toPublic(member: Member): PublicMember {\n  return member;\n}",
  solution: "type Member = { id: number; name: string; age: number; email: string };\n\ntype MemberForm = Omit<Member, \"id\">;\ntype PublicMember = Pick<Member, \"id\" | \"name\">;\n\nfunction toPublic(member: Member): PublicMember {\n  return { id: member.id, name: member.name };\n}\n\nconst form: MemberForm = { name: \"ซี\", age: 20, email: \"sea@example.com\" };\nconsole.log(toPublic({ id: 1, ...form }));",
  buggy: "type Activity = { id: number; title: string; capacity: number };\n\nfunction toCard(activity: Activity): Pick<Activity, \"title\"> {\n  return activity;\n}\n\nconsole.log(toCard({ id: 1, title: \"Hiking\", capacity: 8 }));",
  bugExplanation: "tsc ผ่านเพราะ object ที่มี field มากกว่าใช้แทน Pick ได้ (structural typing) แต่ตอนรันยังส่ง id และ capacity ออกไปด้วย ถ้าเป็น API response อาจรั่วข้อมูลที่ไม่อยากเปิด type ไม่ได้ตัด field ตอน runtime ต้องสร้าง object ใหม่เอง: return { title: activity.title };",
  vocabulary: [v("utility type", "type สำเร็จรูปที่แปลง type เดิมเป็น type ใหม่"), v("Partial<T>", "ทุก field เป็น optional"), v("Pick<T, K> / Omit<T, K>", "เลือก / ตัด field"), v("Record<K, V>", "object type จาก key และค่า"), v("ReturnType<F>", "type ของค่าที่ function คืน")],
},
{
  id: "ts-classes",
  courseId,
  unit: "Reuse",
  title: "class ใน TypeScript: private, readonly และ implements",
  objective: "เขียน class ที่มี field ระบุ type ปกป้อง state ด้วย private/readonly และใช้ implements ตรวจว่า class ทำตาม interface",
  why: "Back-end และ library จำนวนมากเขียนเป็น class การรู้ว่า TypeScript ตรวจอะไรให้ได้ (และอะไรไม่ได้ตรวจตอน runtime) ช่วยให้อ่านโค้ดเหล่านั้นและออกแบบ object ที่รักษากติกาของตัวเองได้",
  explanation: "class ประกาศ field พร้อม type และกำหนดค่าใน constructor private ห้ามเข้าถึงจากนอก class (ตรวจตอน compile; ถ้าต้องการซ่อนจริงตอน runtime ใช้ #field ของ JavaScript) readonly ห้าม assign หลัง constructor implements Interface ให้ tsc ตรวจว่า class มี method/field ตามสัญญา parameter properties (constructor(private x: number)) เป็น syntax ที่ Node type stripping ไม่รองรับ บทนี้จึงประกาศ field แยก",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-object-types", "ts-null-safety"],
  example: "interface Joinable {\n  join(name: string): boolean;\n  readonly seatsLeft: number;\n}\n\nclass Activity implements Joinable {\n  readonly title: string;\n  private readonly capacity: number;\n  private members: string[] = [];\n\n  constructor(title: string, capacity: number) {\n    this.title = title;\n    this.capacity = capacity;\n  }\n\n  get seatsLeft(): number {\n    return this.capacity - this.members.length;\n  }\n\n  join(name: string): boolean {\n    if (this.seatsLeft === 0 || this.members.includes(name)) return false;\n    this.members.push(name);\n    return true;\n  }\n}\n\nconst game = new Activity(\"Board game\", 2);\nconsole.log(game.join(\"ซี\"), game.join(\"ซี\"), game.join(\"ต้น\"), game.join(\"ฝน\"));\nconsole.log(game.title, game.seatsLeft);",
  expectedOutput: "true false true false\nBoard game 0",
  tracePrompt: "ไล่ผลของ join ทั้งสี่ครั้ง และบอกว่าถ้าเขียน game.members.push(\"บี\") นอก class tsc จะแจ้งอะไร",
  traceAnswer: "true (ซีเข้าได้), false (ซีซ้ำ), true (ต้นเข้าได้ ที่นั่งเหลือ 0), false (เต็ม) ส่วน game.members.push(...) tsc แจ้ง Property 'members' is private — ต้องเพิ่มคนผ่าน join ซึ่งตรวจกติกาเสมอ",
  practicePrompt: "เขียน class Wallet ที่มี private balance เริ่มจาก 0, method deposit(amount: number): void (ปฏิเสธจำนวน ≤ 0 ด้วย throw), withdraw(amount: number): boolean (คืน false ถ้าเงินไม่พอ) และ getter balanceText ที่คืน \"เหลือ N บาท\" " + local,
  starter: "class Wallet {\n  balance = 0;\n\n  deposit(amount) {\n    this.balance += amount;\n  }\n}",
  solution: "class Wallet {\n  private balance = 0;\n\n  deposit(amount: number): void {\n    if (amount <= 0) throw new Error(\"จำนวนเงินต้องมากกว่า 0\");\n    this.balance += amount;\n  }\n\n  withdraw(amount: number): boolean {\n    if (amount <= 0 || amount > this.balance) return false;\n    this.balance -= amount;\n    return true;\n  }\n\n  get balanceText(): string {\n    return \"เหลือ \" + this.balance + \" บาท\";\n  }\n}\n\nconst wallet = new Wallet();\nwallet.deposit(500);\nconsole.log(wallet.withdraw(200), wallet.withdraw(400), wallet.balanceText);",
  buggy: "class Counter {\n  private count = 0;\n  increase() {\n    this.count++;\n  }\n}\n\nconst counter = new Counter();\nconst increase = counter.increase;\nincrease();",
  bugExplanation: "tsc ผ่าน แต่ตอนรันได้ TypeError เพราะ this หายเมื่อดึง method ออกมาเป็น function เดี่ยว (this เป็น undefined ใน strict mode) แก้โดยเรียกผ่าน object (counter.increase()) หรือผูก this: const increase = () => counter.increase(); — TypeScript ตรวจ type แต่ไม่ได้ป้องกันทุกปัญหาของ this",
  vocabulary: [v("class", "แม่แบบสำหรับสร้าง object ที่มี state และ method"), v("private", "เข้าถึงได้เฉพาะใน class (ตรวจตอน compile)"), v("#field", "private field ของ JavaScript ที่ซ่อนจริงตอน runtime"), v("implements", "ให้ tsc ตรวจว่า class ทำตาม interface"), v("getter", "method ที่อ่านเหมือน property ด้วย get"), v("parameter property", "syntax ย่อ constructor(private x) ที่ต้อง transpile")],
},
{
  id: "ts-config",
  courseId,
  unit: "ใช้ในโปรเจกต์จริง",
  title: "tsconfig, strict mode และวิธีรัน TypeScript",
  objective: "ตั้งค่า tsconfig.json แบบ strict ตรวจโปรเจกต์ด้วย tsc --noEmit และเลือกวิธีรัน TypeScript ใน Node ให้เหมาะกับงาน",
  why: "โปรเจกต์จริงมีหลายไฟล์และต้องตรวจซ้ำทุกครั้งก่อน commit/deploy การรู้ว่า tsc, Node และ bundler แบ่งหน้าที่กันอย่างไรช่วยไม่ให้เชื่อผิดว่า “รันได้ = type ถูก”",
  explanation: "tsconfig.json บอก tsc ว่าตรวจไฟล์ไหนและใช้กติกาไหน strict: true เปิดชุดการตรวจที่สำคัญ (รวม strictNullChecks และ noImplicitAny) tsc --noEmit ตรวจ type โดยไม่สร้างไฟล์ JS เหมาะกับใส่ใน script ของ npm และ CI Node 22.18 ขึ้นไปรัน .ts ได้ตรงด้วยการลบ type (type stripping) แต่ไม่ตรวจ type และไม่รองรับ syntax ที่ต้องแปลงโค้ด เช่น enum หรือ parameter properties เฟรมเวิร์กอย่าง Next.js แปลง TS ให้เองแต่ก็ควรรัน tsc แยก",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-classes", "js-modules-json"],
  example: "// tsconfig.json (ตัวอย่างขั้นต่ำสำหรับโปรเจกต์ Node แบบ ESM)\n// {\n//   \"compilerOptions\": {\n//     \"target\": \"ES2022\",\n//     \"module\": \"NodeNext\",\n//     \"strict\": true,\n//     \"noEmit\": true\n//   },\n//   \"include\": [\"src\"]\n// }\n\nfunction parsePort(value: string | undefined): number {\n  const port = Number(value ?? \"3000\");\n  return Number.isInteger(port) && port > 0 ? port : 3000;\n}\n\nconsole.log(parsePort(undefined), parsePort(\"8080\"), parsePort(\"abc\"));",
  expectedOutput: "3000 8080 3000",
  tracePrompt: "ถ้าลบ | undefined ออกจาก type ของ value แล้วเรียก parsePort(process.env.PORT) ในโปรเจกต์ Node จริงที่เปิด strict tsc จะแจ้งอะไร และถ้ารันด้วย node index.ts ตรง ๆ จะเห็น error นั้นไหม",
  traceAnswer: "tsc แจ้งว่า string | undefined ใช้แทน string ไม่ได้ เพราะ process.env.PORT อาจไม่มี ส่วน node index.ts จะไม่เห็น error นี้เลยเพราะ Node แค่ลบ type แล้วรัน — ต้องรัน tsc --noEmit แยกเพื่อตรวจ",
  practicePrompt: "ในเครื่อง: สร้างโฟลเดอร์ใหม่ รัน npm init -y และ npm install --save-dev typescript สร้าง tsconfig.json แบบ strict + noEmit และไฟล์ src/index.ts ที่มี parsePort เพิ่ม script \"check\": \"tsc\" แล้วรัน npm run check ให้ผ่าน จากนั้นจงใจทำให้ผิดหนึ่งจุดแล้วดู error",
  starter: "// package.json (บางส่วน)\n// \"scripts\": { \"check\": \"???\" }\n\n// tsconfig.json\n// { \"compilerOptions\": { \"strict\": ???, \"noEmit\": ??? }, \"include\": [\"src\"] }\n\nfunction parsePort(value) {\n  return Number(value);\n}",
  solution: "// package.json (บางส่วน)\n// \"scripts\": { \"check\": \"tsc\" }\n\n// tsconfig.json\n// { \"compilerOptions\": { \"target\": \"ES2022\", \"module\": \"NodeNext\", \"strict\": true, \"noEmit\": true }, \"include\": [\"src\"] }\n\nfunction parsePort(value: string | undefined): number {\n  const port = Number(value ?? \"3000\");\n  return Number.isInteger(port) && port > 0 ? port : 3000;\n}\n\nconsole.log(parsePort(\"4000\"));",
  buggy: "enum Kind {\n  Online,\n  Onsite,\n}\n\nconst kind: Kind = Kind.Online;\nconsole.log(kind);",
  bugExplanation: "tsc ตรวจผ่าน แต่ถ้ารันด้วย node index.ts (type stripping) จะได้ error ว่า syntax นี้ไม่รองรับ เพราะ enum สร้างโค้ด runtime ที่ต้องแปลง ไม่ใช่แค่ลบ type ทางเลือก: ใช้ union ของ literal (type Kind = \"online\" | \"onsite\") หรือรันผ่านเครื่องมือที่ transpile ได้",
  vocabulary: [v("tsconfig.json", "ไฟล์ตั้งค่าของ tsc ว่าตรวจไฟล์ไหนด้วยกติกาอะไร"), v("strict", "เปิดการตรวจที่เข้มงวดทั้งชุด"), v("--noEmit", "ตรวจ type โดยไม่สร้างไฟล์ผลลัพธ์"), v("type stripping", "การลบ type ออกแล้วรัน โดยไม่ตรวจ type (Node 22.18+)"), v("transpile", "แปลงโค้ดจากภาษา/เวอร์ชันหนึ่งเป็นอีกแบบ")],
},
{
  id: "ts-async-types",
  courseId,
  unit: "ใช้ในโปรเจกต์จริง",
  title: "Promise<T> และข้อมูลจาก API เป็น unknown",
  objective: "กำหนด type ให้ async function ด้วย Promise<T> และตรวจข้อมูล JSON จากภายนอกด้วย type guard ก่อนเชื่อว่าเป็น type ของเรา",
  why: "การเขียน const data = await response.json() as Activity[] แค่บอก tsc ให้เชื่อ ถ้า API ส่ง field ผิด หน้าเว็บจะพังตอน runtime ทั้งที่ tsc ผ่าน ขอบเขตระหว่างโลกภายนอกกับโค้ดของเราต้องมีการตรวจจริง",
  explanation: "async function ที่คืน T มี return type เป็น Promise<T> await ของ Promise<T> ได้ T ข้อมูลที่มาจากภายนอก (JSON, request body, localStorage) ควรถือเป็น unknown แล้วตรวจด้วย type guard ที่เขียนเอง (function isActivity(value: unknown): value is Activity) การใช้ as เป็นการยืนยันด้วยตัวเราเอง ไม่ใช่การตรวจ ใช้ได้เมื่อมั่นใจจากการตรวจก่อนหน้าแล้วเท่านั้น",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-config", "js-async"],
  example: "type Activity = { title: string; capacity: number };\n\nfunction isActivity(value: unknown): value is Activity {\n  if (typeof value !== \"object\" || value === null) return false;\n  const record = value as Record<string, unknown>;\n  return typeof record.title === \"string\" && typeof record.capacity === \"number\";\n}\n\nasync function loadActivities(text: string): Promise<Activity[]> {\n  const data: unknown = JSON.parse(text);\n  if (!Array.isArray(data)) throw new Error(\"ต้องเป็น array\");\n  return data.filter(isActivity);\n}\n\nconst good = await loadActivities('[{\"title\":\"Hiking\",\"capacity\":8},{\"title\":\"Bad\",\"capacity\":\"8\"}]');\nconsole.log(good.map((activity) => activity.title));\n\ntry {\n  await loadActivities('{\"title\":\"Hiking\"}');\n} catch (error) {\n  console.log(error instanceof Error ? error.message : \"unknown\");\n}",
  expectedOutput: "[\"Hiking\"]\nต้องเป็น array",
  tracePrompt: "ทำไมรายการ “Bad” ถูกกรองทิ้ง และถ้าเปลี่ยนเป็น return data as Activity[] จะเกิดอะไรกับ “Bad”",
  traceAnswer: "capacity ของ Bad เป็น string \"8\" isActivity จึงคืน false และ filter ทิ้ง ถ้าใช้ as Activity[] tsc จะผ่าน แต่ Bad จะหลุดเข้าไปพร้อม capacity ที่เป็น string และไปพังตอนคำนวณที่นั่ง — as ไม่ได้ตรวจอะไรเลย",
  practicePrompt: "เขียน isMember(value: unknown): value is Member สำหรับ type Member = { id: number; name: string; email?: string } (email ถ้ามีต้องเป็น string) และ async function parseMembers(text: string): Promise<Member[]> ที่คืนเฉพาะรายการที่ถูกต้อง " + local,
  starter: "type Member = { id: number; name: string; email?: string };\n\nasync function parseMembers(text: string): Promise<Member[]> {\n  return JSON.parse(text) as Member[];\n}",
  solution: "type Member = { id: number; name: string; email?: string };\n\nfunction isMember(value: unknown): value is Member {\n  if (typeof value !== \"object\" || value === null) return false;\n  const record = value as Record<string, unknown>;\n  return typeof record.id === \"number\"\n    && typeof record.name === \"string\"\n    && (record.email === undefined || typeof record.email === \"string\");\n}\n\nasync function parseMembers(text: string): Promise<Member[]> {\n  const data: unknown = JSON.parse(text);\n  return Array.isArray(data) ? data.filter(isMember) : [];\n}\n\nconsole.log(await parseMembers('[{\"id\":1,\"name\":\"ซี\"},{\"id\":\"2\",\"name\":\"ต้น\"},{\"id\":3,\"name\":\"ฝน\",\"email\":5}]'));",
  buggy: "type Activity = { title: string; capacity: number };\n\nasync function load(): Promise<Activity> {\n  const data = JSON.parse('{\"title\":\"Hiking\"}');\n  return data;\n}\n\nconst activity = await load();\nconsole.log(activity.capacity.toFixed(0));",
  bugExplanation: "tsc ผ่านเพราะ JSON.parse คืน any ซึ่งถูกปล่อยผ่านเป็น Activity โดยไม่ตรวจ แต่ตอนรัน capacity เป็น undefined จึง TypeError แก้โดยประกาศ const data: unknown = JSON.parse(...) แล้วตรวจด้วย type guard ก่อน return — any จาก JSON.parse คือช่องโหว่ที่ต้องปิดเอง",
  vocabulary: [v("Promise<T>", "type ของ Promise ที่ให้ค่า T เมื่อสำเร็จ"), v("type guard", "function ตรวจที่บอก tsc ว่าค่าเป็น type ไหน"), v("type assertion (as)", "การบอก tsc ให้เชื่อ ไม่ใช่การตรวจ"), v("trust boundary", "ขอบเขตที่ข้อมูลจากภายนอกเข้ามา ต้องตรวจจริง")],
},
{
  id: "ts-project-planner",
  courseId,
  unit: "ใช้ในโปรเจกต์จริง",
  title: "Mini project: Friends Activity Planner M3 — ใส่ type ให้ model และ logic",
  objective: "แปลงโค้ด Planner M1–M2 เป็น TypeScript: นิยาม model ด้วย discriminated union, ใช้ utility types สำหรับ input และให้ tsc --noEmit ผ่านแบบ strict",
  why: "การย้ายโค้ด JavaScript ที่ทำงานอยู่แล้วมาเป็น TypeScript เป็นงานที่เจอบ่อยในทีมจริง type ที่ดีจะเผยบั๊กที่ซ่อนอยู่ และเตรียม model ให้ API ในคอร์ส Back-end ใช้ร่วมกัน",
  explanation: "M3 ไม่ได้เพิ่มฟีเจอร์ แต่ทำให้สัญญาชัด: Activity เป็น union ของกิจกรรมออนไลน์และในสถานที่ (แยกด้วย kind), NewActivity สร้างจาก Omit, summarizePlanner และ planWeek มี type ของ input/output ชัดเจน ทุก function ที่รับข้อมูลภายนอกรับเป็น unknown แล้วตรวจก่อน เกณฑ์สำเร็จคือ tsc --noEmit ผ่านด้วย strict: true และไม่มี any",
  language: "typescript",
  standard: "v3",
  prerequisites: ["ts-async-types", "ts-utility-types", "js-project-planner-2"],
  example: "type BaseActivity = { id: number; title: string; capacity: number; joined: number; votes: number; day: string; time: string };\ntype Activity = (BaseActivity & { kind: \"online\"; url: string }) | (BaseActivity & { kind: \"onsite\"; room: string });\ntype NewActivity = Omit<BaseActivity, \"id\" | \"joined\" | \"votes\"> & ({ kind: \"online\"; url: string } | { kind: \"onsite\"; room: string });\n\ntype Summary = { total: number; open: number; full: number; seatsLeft: number; topTitle: string | null };\n\nconst isFull = (activity: Activity): boolean => activity.joined >= activity.capacity;\n\nfunction summarizePlanner(activities: readonly Activity[]): Summary {\n  const full = activities.filter(isFull).length;\n  const ranked = [...activities].sort((a, b) => b.votes - a.votes || a.title.localeCompare(b.title));\n  return {\n    total: activities.length,\n    open: activities.length - full,\n    full,\n    seatsLeft: activities.reduce((sum, activity) => sum + Math.max(0, activity.capacity - activity.joined), 0),\n    topTitle: ranked[0]?.title ?? null,\n  };\n}\n\nlet nextId = 1;\nfunction create(input: NewActivity): Activity {\n  return { ...input, id: nextId++, joined: 0, votes: 0 };\n}\n\nconst list: Activity[] = [\n  create({ kind: \"onsite\", title: \"Board game\", capacity: 6, day: \"sat\", time: \"18:00\", room: \"DII-201\" }),\n  create({ kind: \"online\", title: \"Code review\", capacity: 10, day: \"fri\", time: \"20:00\", url: \"meet.example/cr\" }),\n];\nconsole.log(summarizePlanner(list));",
  expectedOutput: "{\"total\":2,\"open\":2,\"full\":0,\"seatsLeft\":16,\"topTitle\":\"Board game\"}",
  tracePrompt: "ถ้าเรียก create({ kind: \"online\", title: \"Movie\", capacity: 4, day: \"sun\", time: \"19:00\", room: \"A\" }) tsc จะแจ้งอะไร และทำไม topTitle ใช้ ranked[0]?.title ?? null",
  traceAnswer: "แจ้งว่ากิจกรรม online ต้องมี url และไม่มี room (excess property/ขาด field) เพราะ union แยกตาม kind ส่วน ranked[0] อาจเป็น undefined เมื่อรายการว่าง ?. กับ ?? ทำให้คืน null ตามที่ Summary ประกาศไว้ — strict mode บังคับให้จัดการกรณีนี้",
  practicePrompt: "ในเครื่อง: คัดลอก isValidTime และ planWeek จาก M2 มาไว้ไฟล์ planner.ts เพิ่ม type ให้ครบ (รับ readonly Activity[] คืน { schedule: Record<string, string[]>; invalid: number[] }) และเพิ่ม parseActivities(text: string): Activity[] ที่รับ JSON เป็น unknown แล้วตรวจด้วย type guard จากนั้นให้ npx tsc --noEmit --strict planner.ts ผ่านโดยไม่มี any",
  starter: "// planner.ts — เริ่มจากโค้ด M2 (JavaScript)\nfunction isValidTime(time) {\n  if (!/^\\d{2}:\\d{2}$/.test(time)) return false;\n  const [hours, minutes] = time.split(\":\").map(Number);\n  return hours <= 23 && minutes <= 59;\n}\n\nfunction planWeek(activities) {\n  // ... โค้ดจาก M2\n}\n\nfunction parseActivities(text) {\n  return JSON.parse(text);\n}",
  solution: "type BaseActivity = { id: number; title: string; capacity: number; joined: number; votes: number; day: string; time: string };\ntype Activity = (BaseActivity & { kind: \"online\"; url: string }) | (BaseActivity & { kind: \"onsite\"; room: string });\ntype WeekPlan = { schedule: Record<string, string[]>; invalid: number[] };\n\nfunction isValidTime(time: string): boolean {\n  if (!/^\\d{2}:\\d{2}$/.test(time)) return false;\n  const [hours, minutes] = time.split(\":\").map(Number);\n  return hours <= 23 && minutes <= 59;\n}\n\nfunction planWeek(activities: readonly Activity[]): WeekPlan {\n  const grouped: Record<string, Activity[]> = {};\n  const invalid: number[] = [];\n  activities.forEach((activity, index) => {\n    if (activity.title.trim() === \"\" || !isValidTime(activity.time)) {\n      invalid.push(index);\n      return;\n    }\n    grouped[activity.day] = [...(grouped[activity.day] ?? []), activity];\n  });\n  const schedule: Record<string, string[]> = {};\n  for (const [day, items] of Object.entries(grouped)) {\n    schedule[day] = [...items].sort((a, b) => a.time.localeCompare(b.time)).map((a) => a.time + \" \" + a.title.trim());\n  }\n  return { schedule, invalid };\n}\n\nfunction isActivity(value: unknown): value is Activity {\n  if (typeof value !== \"object\" || value === null) return false;\n  const r = value as Record<string, unknown>;\n  const base = typeof r.id === \"number\" && typeof r.title === \"string\" && typeof r.capacity === \"number\" && typeof r.joined === \"number\" && typeof r.votes === \"number\" && typeof r.day === \"string\" && typeof r.time === \"string\";\n  if (!base) return false;\n  return (r.kind === \"online\" && typeof r.url === \"string\") || (r.kind === \"onsite\" && typeof r.room === \"string\");\n}\n\nfunction parseActivities(text: string): Activity[] {\n  const data: unknown = JSON.parse(text);\n  return Array.isArray(data) ? data.filter(isActivity) : [];\n}\n\nconst parsed = parseActivities('[{\"id\":1,\"kind\":\"onsite\",\"title\":\"Hiking\",\"capacity\":8,\"joined\":2,\"votes\":3,\"day\":\"sat\",\"time\":\"07:00\",\"room\":\"Doi Suthep\"}]');\nconsole.log(planWeek(parsed));",
  buggy: "type Activity = { kind: \"online\"; url: string } | { kind: \"onsite\"; room: string };\n\nfunction where(activity: Activity): string {\n  if (activity.kind === \"online\") return activity.url;\n  return activity.url ?? activity.room;\n}",
  bugExplanation: "tsc แจ้ง Property 'url' does not exist on type '{ kind: \"onsite\"; room: string }' ในบรรทัดสุดท้าย เพราะหลัง if แรก activity ถูก narrow เหลือแบบ onsite แล้ว ซึ่งไม่มี url แก้เป็น return activity.room; — discriminated union ทำให้แต่ละกิ่งใช้ได้เฉพาะ field ของแบบนั้น",
  vocabulary: [v("migration", "การย้ายโค้ดจาก JavaScript มาเป็น TypeScript ทีละส่วน"), v("intersection type", "A & B คือมีทุก field ของทั้ง A และ B"), v("domain model", "type ที่อธิบายข้อมูลหลักของระบบ เช่น Activity"), v("Object.entries", "แปลง object เป็น array ของ [key, value]")],
},
];
