import type { TopicSource } from "@/types/curriculum";

const courseId = "web-platform-foundations";
const v = (term: string, meaning: string): [string, string] => [term, meaning];

export const webPlatformFoundationTopics: TopicSource[] = [
  {
    id: "web-request", courseId, unit: "เว็บทำงานอย่างไร", title: "Browser, server และ HTTP response",
    objective: "อธิบายได้ว่า browser ขอหน้าเว็บจาก server แล้วนำ HTML, CSS และ JavaScript ไปใช้อย่างไร",
    why: "เมื่อหน้าเว็บไม่ขึ้น ต้องแยกให้ออกว่า request, response, resource หรือ rendering ขั้นใดผิดพลาด",
    explanation: "Browser ส่ง HTTP request ไปยัง URL; server ตอบ status, headers และ body. Browser อ่าน HTML เพื่อสร้างหน้า แล้วขอ CSS, รูป และ JavaScript ที่ HTML อ้างถึงเพิ่มเติม. HTTP 404 หมายถึงไม่พบ resource ที่ขอ ไม่ได้แปลว่า CSS ผิดเสมอไป",
    example: `GET /index.html → 200 text/html\nHTML: <link rel="stylesheet" href="/style.css">\nGET /style.css → 200 text/css`,
    tracePrompt: "ถ้า /index.html ได้ 200 แต่ /style.css ได้ 404 จะเห็นอะไร?",
    traceAnswer: "HTML อาจยังแสดง แต่ไม่มี style จากไฟล์นั้น; ตรวจ path ของ CSS ใน Network panel",
    starter: `หน้า HTML แสดงข้อความได้ แต่ไม่มีสีและระยะห่าง\n/index.html → 200\n/style.css → 404`,
    practicePrompt: "เขียนสมมติฐานหนึ่งข้อและขั้นตอนตรวจใน DevTools ก่อนแก้ไฟล์",
    solution: `สมมติฐาน: href ของ stylesheet ชี้ผิด path\nเปิด Network → เลือก style.css → ดู Request URL → เทียบกับที่อยู่ไฟล์จริง`,
    buggy: `<link rel="stylesheet" href="style.css">\n<!-- ไฟล์จริงอยู่ /assets/style.css -->`,
    bugExplanation: "href ชี้ผิดตำแหน่ง เปลี่ยนเป็น /assets/style.css และตรวจ Network ว่า response เป็น 200",
    vocabulary: [v("request", "คำขอ resource จาก client"), v("response", "คำตอบพร้อม status และเนื้อหา"), v("resource", "ไฟล์หรือข้อมูลที่ URL ชี้ถึง")],
  },
  {
    id: "web-url", courseId, unit: "เว็บทำงานอย่างไร", title: "ส่วนประกอบของ URL และ relative path",
    objective: "แยก origin, path, query และ fragment พร้อมคำนวณ URL จาก relative link ได้",
    why: "ลิงก์และรูปที่หายมักเกิดจากเข้าใจฐานของ relative URL ผิด",
    explanation: "URL มี scheme, host, path, query และ fragment. ลิงก์ที่ขึ้นต้น / อ้างจากรากของ origin; ลิงก์ที่ไม่มี / อ้างจาก directory ของหน้าปัจจุบัน. Query ส่งค่ามากับ request ส่วน fragment ใช้ชี้ส่วนในเอกสารและไม่ถูกส่งใน HTTP request ปกติ",
    example: `https://example.test/events/today?city=cnx#list\norigin: https://example.test\npath: /events/today\nquery: city=cnx\nfragment: list`,
    tracePrompt: "อยู่ที่ /events/today แล้ว href=details และ href=/details ไปที่ใด?",
    traceAnswer: "details ไป /events/details; /details ไปที่รากของเว็บ",
    starter: `<a href="____">ดูรายการทั้งหมด</a>\n<!-- ปลายทางคือ /events จากทุกหน้า -->`,
    practicePrompt: "เติม href ให้ปลายทางไม่เปลี่ยนตาม path ของหน้าปัจจุบัน",
    solution: `<a href="/events">ดูรายการทั้งหมด</a>`,
    buggy: `<img src="images/logo.png" alt="">\n<!-- หน้าอยู่ /events/today; รูปจริงอยู่ /images/logo.png -->`,
    bugExplanation: "relative path จะกลายเป็น /events/images/logo.png ให้ใช้ /images/logo.png",
    vocabulary: [v("origin", "scheme, host และ port ของเว็บ"), v("query", "ข้อมูลหลัง ? ใน URL"), v("fragment", "ตำแหน่งหลัง # ในเอกสาร")],
  },
  {
    id: "web-semantics", courseId, unit: "HTML ที่สื่อความหมาย", title: "โครงสร้างเอกสารและ semantic elements",
    objective: "เลือก heading, nav, main และ article ตามความหมายของเนื้อหาได้",
    why: "ความหมายของ HTML ช่วยทั้งคนใช้ screen reader, การนำทางด้วย keyboard และเครื่องมือค้นหา",
    explanation: "HTML อธิบายโครงสร้างและความหมาย ไม่ใช่แค่รูปร่าง. หน้าหนึ่งควรมี main สำหรับเนื้อหาหลัก, nav สำหรับชุดลิงก์นำทาง และ heading ที่เรียงตามลำดับหัวข้อ. ใช้ article กับเนื้อหาที่อยู่ได้ด้วยตัวเอง",
    example: `<header><nav aria-label="หลัก"><a href="/">หน้าแรก</a></nav></header>\n<main><h1>กิจกรรมเพื่อน</h1><article><h2>ปั่นจักรยาน</h2></article></main>`,
    tracePrompt: "ในตัวอย่างนี้ heading ใดเป็นชื่อหน้า และ heading ใดเป็นชื่อรายการ?",
    traceAnswer: "h1 เป็นชื่อหน้า; h2 เป็นชื่อ article ใต้หัวข้อหลัก",
    starter: `<div class="title">กิจกรรมเพื่อน</div>\n<div class="activity">ปั่นจักรยาน</div>`,
    practicePrompt: "เปลี่ยนโครงสร้างให้มี main, h1 และ article ที่มี h2",
    solution: `<main><h1>กิจกรรมเพื่อน</h1><article><h2>ปั่นจักรยาน</h2></article></main>`,
    buggy: `<main><h3>กิจกรรมเพื่อน</h3><h1>ปั่นจักรยาน</h1></main>`,
    bugExplanation: "ลำดับหัวข้อกลับด้าน ให้ชื่อหน้าเป็น h1 แล้วชื่อรายการเป็น h2",
    vocabulary: [v("semantic HTML", "element ที่สื่อหน้าที่ของเนื้อหา"), v("landmark", "บริเวณหลักของหน้าเพื่อการนำทาง"), v("heading", "หัวข้อที่จัดลำดับเนื้อหา")],
  },
  {
    id: "web-forms", courseId, unit: "HTML ที่สื่อความหมาย", title: "Form, label และ browser validation",
    objective: "สร้าง form ที่ระบุชื่อช่องกรอกและใช้ชนิด input ตรงกับข้อมูลได้",
    why: "ฟอร์มที่ label ไม่สัมพันธ์กับ input ใช้งานยากและทำให้ผู้ใช้เครื่องมือช่วยอ่านไม่รู้ว่าต้องกรอกอะไร",
    explanation: "label ที่มี htmlFor ตรงกับ id ของ input สร้างชื่อที่อ่านได้และกด label เพื่อ focus ได้. name คือชื่อ field เมื่อส่ง form. ใช้ required และ type เพื่อรับ browser validation ขั้นต้น แต่ server ยังต้องตรวจข้อมูลซ้ำเสมอ",
    example: `<form><label for="email">อีเมล</label><input id="email" name="email" type="email" required><button type="submit">บันทึก</button></form>`,
    tracePrompt: "เมื่อกดคำว่า อีเมล ในตัวอย่าง browser จะทำอะไร?",
    traceAnswer: "focus ไปที่ input id=email เพราะ for ของ label ตรงกับ id",
    starter: `<form><input id="activity" name="activity"><button>เพิ่ม</button></form>`,
    practicePrompt: "เพิ่ม label และกำหนดว่าชื่อกิจกรรมต้องไม่ว่าง",
    solution: `<form><label for="activity">ชื่อกิจกรรม</label><input id="activity" name="activity" required><button type="submit">เพิ่ม</button></form>`,
    buggy: `<label for="title">ชื่อกิจกรรม</label><input id="activity" name="activity">`,
    bugExplanation: "for ไม่ตรง id จึงไม่เชื่อม label กับ input; เปลี่ยน for เป็น activity",
    vocabulary: [v("label", "ชื่อที่ผูกกับช่องกรอก"), v("name", "ชื่อ field เมื่อส่ง form"), v("required", "เงื่อนไขว่า input ต้องมีค่า")],
  },
  {
    id: "web-selector", courseId, unit: "CSS พื้นฐาน", title: "Selectors, specificity และ cascade",
    objective: "ทำนายได้ว่ากฎ CSS ใดกำหนดค่าจริงเมื่อหลายกฎเลือก element เดียวกัน",
    why: "การเติม !important ไปเรื่อย ๆ มักซ่อนปัญหาลำดับและความเฉพาะของ selector",
    explanation: "CSS เลือก element ด้วย type, class หรือ id. เมื่อ declaration ระดับเดียวกันขัดกัน specificity ที่สูงกว่าชนะ; ถ้าเท่ากันกฎที่มาทีหลังชนะ. ดู Computed และ Styles ใน DevTools เพื่อหากฎที่ใช้จริง",
    example: `.card { color: blue; }\n.card { color: green; }\n<!-- <p class="card">...</p> มีสี green -->`,
    tracePrompt: "ถ้ามี p { color: red } เพิ่มก่อน .card สุดท้ายข้อความสีอะไร?",
    traceAnswer: "green เพราะ class selector เจาะจงกว่า type selector",
    starter: `.notice { color: black; }\n.notice { color: ____; }`,
    practicePrompt: "เติมให้ข้อความ notice เป็นสีน้ำเงิน และอธิบายว่ากฎใดชนะ",
    solution: `.notice { color: black; }\n.notice { color: blue; }\n/* specificity เท่ากัน กฎหลังชนะ */`,
    buggy: `.card { color: blue; }\n#summary { color: red; }\n<!-- id=summary class=card; ผู้เขียนคาดว่าสีน้ำเงิน -->`,
    bugExplanation: "id selector มี specificity สูงกว่า class จึงเป็นสีแดง; ลด selector ที่เจาะจงเกินไปหรือเปลี่ยน style ที่ตั้งใจ",
    vocabulary: [v("selector", "รูปแบบเลือก element"), v("specificity", "น้ำหนักความเฉพาะของ selector"), v("cascade", "กฎตัดสิน style เมื่อมีหลาย declaration")],
  },
  {
    id: "web-box", courseId, unit: "CSS พื้นฐาน", title: "Box model และระยะห่าง",
    objective: "แยก content, padding, border และ margin เมื่อคำนวณพื้นที่ของ element ได้",
    why: "layout ที่ล้นหรือชิดผิดมักเกิดจากสับสน padding ภายในกับ margin ภายนอก",
    explanation: "ทุก element มี content box ล้อมด้วย padding, border และ margin. box-sizing: border-box ทำให้ width ที่ตั้งครอบ content, padding และ border; margin ยังคงอยู่นอก width. ใช้ Box Model ใน DevTools ดูค่าจริง",
    example: `.card { box-sizing: border-box; width: 200px; padding: 20px; border: 2px solid; }`,
    tracePrompt: "ในตัวอย่าง content box กว้างกี่ px เมื่อไม่มีข้อจำกัดอื่น?",
    traceAnswer: "156px เพราะ 200 - padding ซ้ายขวา 40 - border ซ้ายขวา 4",
    starter: `.card { width: 100%; padding: 16px; }`,
    practicePrompt: "แก้ไม่ให้ card กว้างเกิน container เพราะ padding ใน box model ปกติ",
    solution: `.card { box-sizing: border-box; width: 100%; padding: 16px; }`,
    buggy: `.card { margin: 24px; }\n/* ผู้เขียนคาดว่าข้อความจะห่างจากกรอบภายใน 24px */`,
    bugExplanation: "margin เว้นระยะภายนอก element; ถ้าต้องการระยะจากกรอบถึงข้อความให้ใช้ padding",
    vocabulary: [v("padding", "ช่องว่างด้านในกรอบ"), v("margin", "ช่องว่างด้านนอกกรอบ"), v("border-box", "วิธีนับ width รวม padding และ border")],
  },
  {
    id: "web-flex", courseId, unit: "CSS Layout", title: "Flexbox สำหรับแถวและการกระจายพื้นที่",
    objective: "วางรายการเป็นแถวและอธิบาย main axis กับ cross axis ของ flex container ได้",
    why: "เมนูและแถบเครื่องมือควรจัดด้วย layout ไม่ใช่เว้นช่องด้วย space ในข้อความ",
    explanation: "display:flex จัดลูกตาม main axis ซึ่งค่าเริ่มต้นคือแนวนอน. gap กำหนดระยะระหว่างลูก; justify-content จัดตาม main axis และ align-items จัดตาม cross axis. เมื่อเปลี่ยน flex-direction เป็น column แกนทั้งสองสลับหน้าที่",
    example: `.toolbar { display: flex; gap: 12px; justify-content: space-between; align-items: center; }`,
    tracePrompt: "ถ้า flex-direction เป็น column, justify-content จัดลูกตามแนวใด?",
    traceAnswer: "แนวตั้ง เพราะ main axis เปลี่ยนเป็นแนวตั้ง",
    starter: `<nav class="menu"><a href="/">Home</a><a href="/events">Events</a></nav>`,
    practicePrompt: "เขียน CSS ให้ลิงก์วางเรียงเป็นแถวและเว้น 16px โดยไม่เพิ่ม space ใน HTML",
    solution: `.menu { display: flex; gap: 16px; }`,
    buggy: `.menu { display: flex; justify-content: center; }\n/* ต้องการช่องว่าง 16px ระหว่างลิงก์ */`,
    bugExplanation: "justify-content:center ย้ายกลุ่มไปกลาง ไม่ได้สร้างช่องว่าง 16px; เพิ่ม gap:16px",
    vocabulary: [v("main axis", "แกนหลักของ flex container"), v("cross axis", "แกนตั้งฉากกับแกนหลัก"), v("gap", "ระยะระหว่างลูกใน layout")],
  },
  {
    id: "web-grid", courseId, unit: "CSS Layout", title: "Grid สำหรับคอลัมน์ที่ยืดได้",
    objective: "สร้าง grid ที่จำนวนคอลัมน์ปรับตามพื้นที่และอธิบาย minmax ได้",
    why: "รายการการ์ดหลายแถวต้องรักษาความกว้างขั้นต่ำโดยไม่ล็อกจำนวนคอลัมน์ทุกขนาดจอ",
    explanation: "CSS Grid วางลูกในแถวและคอลัมน์. repeat(auto-fit, minmax(220px, 1fr)) สร้างคอลัมน์เท่าที่พื้นที่รองรับ โดยแต่ละคอลัมน์ไม่ต่ำกว่า 220px และแบ่งพื้นที่ที่เหลือ. Container ที่แคบกว่า minimum ยังต้องจัดการความกว้างของตัวเอง",
    example: `.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }`,
    tracePrompt: "ถ้าพื้นที่ไม่พอสำหรับสองคอลัมน์กว้างอย่างน้อย 220px พร้อม gap จะเกิดอะไร?",
    traceAnswer: "auto-fit เหลือหนึ่งคอลัมน์ตามพื้นที่ที่มี",
    starter: `.cards { display: grid; /* เติมคอลัมน์ที่ยืดตามพื้นที่ */ }`,
    practicePrompt: "สร้างคอลัมน์กว้างขั้นต่ำ 220px และช่องว่าง 16px",
    solution: `.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }`,
    buggy: `.cards { display: grid; grid-template-columns: 300px 300px 300px; }\n/* โทรศัพท์กว้าง 360px */`,
    bugExplanation: "สามคอลัมน์ตายตัวทำให้ overflow; ใช้ repeat(auto-fit, minmax(...)) หรือ media query ที่เหมาะสม",
    vocabulary: [v("grid", "layout แบบแถวและคอลัมน์"), v("minmax", "ขอบเขตความกว้างขั้นต่ำและสูงสุด"), v("auto-fit", "จำนวนคอลัมน์ที่ปรับตามพื้นที่")],
  },
  {
    id: "web-responsive", courseId, unit: "CSS Layout", title: "Responsive viewport และ media query",
    objective: "ออกแบบ layout จากพื้นที่เล็กก่อน แล้วเพิ่มกฎเมื่อมีพื้นที่มากขึ้น",
    why: "หน้าเว็บต้องอ่านและกดได้บนมือถือโดยไม่เลื่อนแนวนอนหรือซ่อนเนื้อหาสำคัญ",
    explanation: "เริ่มด้วยคอลัมน์เดียวและขนาดที่ยืดได้ แล้วใช้ min-width media query เมื่อพื้นที่พอ. ใส่ viewport meta เพื่อให้ browser มือถือใช้ความกว้างอุปกรณ์ตามจริง. ตรวจที่หลายความกว้างและ zoom ไม่ใช่ดูแค่ preset เดียว",
    example: `<meta name="viewport" content="width=device-width, initial-scale=1">\n<style>.layout { display: grid; gap: 1rem } @media (min-width: 48rem) { .layout { grid-template-columns: 1fr 2fr } }</style>`,
    tracePrompt: "ที่ viewport 40rem และ 60rem layout มีคอลัมน์กี่ช่อง?",
    traceAnswer: "40rem มีหนึ่งคอลัมน์; 60rem มีสองคอลัมน์ 1fr 2fr",
    starter: `.layout { display: grid; gap: 1rem; }`,
    practicePrompt: "เพิ่มสองคอลัมน์ขนาด 1fr 2fr เมื่อ viewport กว้างอย่างน้อย 48rem",
    solution: `@media (min-width: 48rem) { .layout { grid-template-columns: 1fr 2fr; } }`,
    buggy: `.layout { width: 1200px; }\n/* หน้าจอมือถือกว้าง 390px */`,
    bugExplanation: "ความกว้างตายตัวทำให้ overflow; ใช้ width:100% และ max-width:1200px พร้อมจัดการ padding/box sizing",
    vocabulary: [v("viewport", "พื้นที่แสดงผลหน้าเว็บ"), v("media query", "เงื่อนไขใช้ CSS ตามสภาพหน้าจอ"), v("responsive", "layout ที่ปรับตามพื้นที่และวิธีใช้")],
  },
  {
    id: "web-accessibility", courseId, unit: "เว็บสำหรับทุกคน", title: "Keyboard, focus และชื่อที่เข้าถึงได้",
    objective: "ใช้ปุ่มและลิงก์ตามหน้าที่ พร้อมตรวจการกด Tab และ focus ที่มองเห็นได้",
    why: "ผู้ใช้บางคนใช้ keyboard หรือ screen reader เป็นทางหลัก; control ที่ไม่มีชื่อหรือ focus จะขวางงานทันที",
    explanation: "ใช้ button สำหรับการกระทำและ a href สำหรับการนำทาง. Element มาตรฐานรองรับ keyboard อยู่แล้ว. ข้อความบนปุ่มหรือ label เป็น accessible name; icon-only button ต้องมีชื่อที่สื่อหน้าที่. อย่าลบ focus outline โดยไม่มีสิ่งทดแทน",
    example: `<a href="/events">ดูกิจกรรม</a>\n<button type="button" aria-label="ลบกิจกรรม">×</button>`,
    tracePrompt: "ถ้ากด Tab ไปยังปุ่มลบ ผู้ใช้ต้องทราบอะไรสองอย่าง?",
    traceAnswer: "รู้ว่าตอนนี้ focus อยู่ที่ปุ่มใดจากภาพ และรู้ชื่อ/หน้าที่ว่า ลบกิจกรรม จาก accessible name",
    starter: `<div onclick="save()">บันทึก</div>`,
    practicePrompt: "เปลี่ยนเป็น control มาตรฐานที่กดด้วย keyboard ได้โดยไม่เขียน key handler เอง",
    solution: `<button type="button" onclick="save()">บันทึก</button>`,
    buggy: `<button aria-label="ปุ่ม">×</button>\nbutton:focus { outline: none; }`,
    bugExplanation: "ชื่อ ปุ่ม ไม่บอกหน้าที่ และ focus หาย; ใช้ชื่อเช่น ลบกิจกรรม พร้อม focus indicator ที่เห็นชัด",
    vocabulary: [v("focus", "ตำแหน่งที่รับ keyboard input"), v("accessible name", "ชื่อ control ที่เครื่องมือช่วยอ่านรับรู้"), v("keyboard navigation", "การใช้งานโดยไม่พึ่ง mouse")],
  },
  {
    id: "web-devtools", courseId, unit: "ตรวจและแก้เว็บ", title: "Elements, Network และ Console ใน DevTools",
    objective: "เลือก DevTools panel ตามอาการและเก็บหลักฐานก่อนแก้โค้ด",
    why: "การเดาสาเหตุจากภาพหน้าเว็บอย่างเดียวทำให้แก้ผิดชั้นและเสียเวลา",
    explanation: "Elements แสดง DOM และ computed styles; Network แสดง request, status และ timing; Console แสดง JavaScript errors และ logs. Reload โดยเปิด Network แล้วเทียบ URL/status กับสิ่งที่คาดก่อนเปลี่ยนโค้ด",
    example: `รูปไม่ขึ้น → Network: GET /avatar.png 404\nสีผิด → Elements: ตรวจ computed color\nปุ่มไม่ทำงาน → Console: อ่าน error`,
    tracePrompt: "หน้าโหลดได้แต่รูปโปรไฟล์หาย ควรเปิด panel ใดก่อน และดูค่าใด?",
    traceAnswer: "Network; ดู Request URL และ HTTP status ของรูป",
    starter: `อาการ: กดบันทึกแล้วไม่มีผล\nหลักฐานจาก DevTools: ____`,
    practicePrompt: "เขียนลำดับตรวจ Console แล้ว Network และระบุสิ่งที่ต้องบันทึก",
    solution: `Console: ดู error และตำแหน่งบรรทัด\nNetwork: ดูว่ามี request หรือไม่, URL, method, status และ response`,
    buggy: `ปุ่มไม่ทำงาน → ติดตั้ง package ใหม่ทั้งหมดโดยยังไม่เปิด Console`,
    bugExplanation: "ยังไม่มีหลักฐานว่า dependency เสีย; ตรวจ Console/Network และลองสร้างกรณีเล็กก่อนเปลี่ยนระบบ",
    vocabulary: [v("DOM", "โครงสร้างเอกสารที่ browser ใช้"), v("computed style", "ค่า CSS สุดท้ายที่ browser ใช้"), v("Network panel", "รายการ request และ response")],
  },
  {
    id: "web-dom", courseId, unit: "ตรวจและแก้เว็บ", title: "DOM event และการเปลี่ยนข้อความ",
    objective: "เชื่อมปุ่มกับ event แล้วปรับข้อความใน DOM โดยไม่เขียน HTML string จาก input",
    why: "การเข้าใจ DOM ก่อน React ช่วยแยก state, event และ rendering รวมถึงเห็นจุดเสี่ยงของ untrusted input",
    explanation: "Browser สร้าง DOM จาก HTML. JavaScript เลือก element, รับ event และเปลี่ยน property ได้. textContent แสดง input เป็นข้อความ; innerHTML แปล input เป็น markup และไม่ควรใช้กับข้อมูลจากผู้ใช้โดยตรง",
    example: `<button id="add" type="button">เพิ่ม</button><p id="count">0</p>\n<script>let count = 0; document.querySelector('#add').addEventListener('click', () => { count += 1; document.querySelector('#count').textContent = String(count); });</script>`,
    tracePrompt: "เมื่อกดปุ่มสองครั้ง count variable และข้อความใน p เป็นอะไร?",
    traceAnswer: "count เป็น 2 และข้อความใน p เป็น 2 เพราะ handler เพิ่มค่าและ render ทุกครั้ง",
    starter: `<p id="message"></p>\n<script>const input = '<img src=x onerror=alert(1)>'; document.querySelector('#message').____ = input;</script>`,
    practicePrompt: "เติม property ที่แสดง input เป็นข้อความธรรมดา",
    solution: `document.querySelector('#message').textContent = input;`,
    buggy: `document.querySelector('#message').innerHTML = userInput;`,
    bugExplanation: "innerHTML แปล markup จากผู้ใช้และอาจรันโค้ดไม่พึงประสงค์ ใช้ textContent เมื่อจะแสดงข้อความ",
    vocabulary: [v("event", "เหตุการณ์จากการโต้ตอบหรือ browser"), v("textContent", "ข้อความของ element แบบไม่แปลเป็น HTML"), v("innerHTML", "HTML markup ภายใน element")],
  },
];
