import type { RichLesson } from "@/types/curriculum";

const local = "ตรวจเองในเครื่อง: บทนี้ต้องใช้ JDK 21 (javac/java) เว็บไซต์ไม่ได้ compile หรือรัน Java ให้";
const localJunit = "ตรวจเองในเครื่อง: ต้องใช้ JDK 21 และ junit-platform-console-standalone (บทเรียนตรวจกับ 6.1.3) เว็บไซต์ไม่ได้รัน Java หรือ JUnit ให้";

export const javaOopLessons: Record<string, RichLesson> = {
  "oop-responsibility": {
    hook: "Library CLI M0 ทำงานได้ แต่ทุกครั้งที่เพิ่มกติกา ซีต้องหาว่าจะใส่ไว้ใน static method ตัวไหน และแก้ ArrayList สามตัวให้ตรงกัน ก่อนจะเขียน class แรก ต้องตอบให้ได้ว่ากติกาแต่ละข้อเป็น “หน้าที่ของใคร”",
    analogy: {
      title: "แบ่งงานในห้องสมุดจริง",
      text: [
        "บรรณารักษ์ที่เคาน์เตอร์ไม่ได้จำว่าหนังสือทุกเล่มอยู่ที่ไหน แต่รู้ว่าต้องถามใคร สมาชิกถือบัตรที่บอกว่ายืมไปกี่เล่ม หนังสือแต่ละเล่มมีบัตรติดปกบอกว่าถูกยืมอยู่ไหม",
        "เมื่อมีคนมายืม บรรณารักษ์แค่ประสาน: ดูบัตรสมาชิก ดูบัตรหนังสือ แล้วจดลงทั้งสองใบ แต่ละคนรับผิดชอบข้อมูลที่ตัวเองถือ",
      ],
      mapping: [
        ["บัตรติดปกหนังสือ", "state และกติกาของ Book"],
        ["บัตรสมาชิก", "state และกติกาของ Member"],
        ["บรรณารักษ์ที่ประสาน", "Library (coordinator)"],
        ["การ์ดหน้าที่ของแต่ละคน", "CRC card"],
      ],
      limits: "คนจริงตัดสินใจนอกกติกาได้และจำบริบทได้เอง แต่ object ทำได้แค่สิ่งที่ method ของมันเขียนไว้ และในโปรแกรมไม่มีใครเห็นทั้งหมดถ้าเราไม่ออกแบบให้มีผู้ประสาน",
    },
    explain: [
      { heading: "1) จาก use case สู่หน้าที่", text: ["เขียนขั้นตอนของ use case เป็นประโยคสั้น ๆ แล้วถามทุกขั้นว่า ใครเป็นเจ้าของข้อมูลที่ใช้ตัดสินใจ", "คำนามที่ไม่มีหน้าที่อะไรเลยอาจไม่ต้องเป็น class (เช่น “ระบบ”)"] },
      { heading: "2) CRC card", text: ["หนึ่งการ์ดต่อหนึ่ง class: ชื่อ / รู้อะไร ทำอะไร / คุยกับใคร", "ถ้าการ์ดใบไหนมีหน้าที่เยอะเกิน แยก ถ้าใบไหนว่างเปล่า อาจรวมกับใบอื่น"] },
      { heading: "3) โครงก่อนรายละเอียด", text: ["เขียน class และ method signature ด้วย throw new UnsupportedOperationException(\"todo\") ก่อน compile ผ่านและเห็นภาพรวม", "ชื่อ method ใช้คำกริยาจากภาษาของงาน (checkOut, finishLoan) ไม่ใช่ setX"] },
    ],
    walkthrough: ["use case ยืมหนังสือแตกเป็น 5 ขั้น", "ขั้นตรวจและบันทึกสถานะหนังสือเป็นของ Book", "ขั้นที่เกี่ยวกับโควตาเป็นของ Member", "Library เป็นจุดเริ่มที่รับคำขอและประสาน"],
    pitfalls: ["ทำทุกคำนามเป็น class ที่มีแต่ field", "รวมทุกกติกาไว้ใน utility class เดียว", "ตั้งชื่อ method ตาม field (setBorrowed) แทนเหตุการณ์", "ลงรายละเอียดโค้ดก่อนเห็นภาพรวม"],
    checks: [
      { question: "กติกา “หนังสืออ้างอิงห้ามยืม” ควรอยู่ที่ไหน", answer: "Book เพราะ Book รู้ว่าตัวเองเป็นหนังสืออ้างอิงไหม (เช่น checkOut ปฏิเสธเอง) Library แค่ส่ง message" },
      { question: "ทำไม Library ไม่ควรเปลี่ยน field ของ Book โดยตรง", answer: "ถ้าทำได้ กติกาของ Book จะถูกข้ามและต้องตรวจซ้ำในทุกที่ที่แก้ field ทำให้กติกากระจาย" },
    ],
    recap: ["ถาม “ใครรู้ ใครตัดสินใจ” ทุกขั้นของ use case", "CRC: รู้ / ทำ / คุยกับใคร", "โครง class + signature ก่อนรายละเอียด"],
    traceHint: "เขียนกติกาออกมาเป็นข้อ แล้วชี้ว่าข้อมูลที่ต้องใช้ตัดสินใจอยู่ใน class ไหนตอนนี้",
    practiceHints: [
      "ไล่ use case คืนหนังสือเป็นขั้น: หา object → คำนวณวันช้า → ค่าปรับ → แจ้งทั้งสองฝ่าย",
      "วันครบกำหนดอยู่กับการยืมของหนังสือ จึงให้ Book (หรือ Loan ในบทหลัง) ตอบว่าช้ากี่วัน",
      "Library มี returnBook(bookId, memberId, today) ที่ประสาน ส่วน Member มี finishLoan(book, fine)",
    ],
    acceptance: [local, "ตรวจเอง: compile และพิมพ์ design ready", "ตรวจเอง: ทุก class มี // รู้ และ // ทำ และ method อย่างน้อยหนึ่งตัวที่ตรงกับหน้าที่นั้น"],
    solutionNotes: ["UnsupportedOperationException ทำให้โครง compile ได้และถ้าเผลอเรียกจะรู้ทันที", "อัตราค่าปรับวางไว้ที่ Library ในตอนนี้ บท interfaces จะแยกเป็น FinePolicy"],
    reflection: ["ใน M0 มีกติกาไหนที่ “ไม่มีเจ้าของ” ชัดเจน และควรย้ายไปไหน"],
    extension: "เขียน CRC card ของ use case “จองหนังสือที่ถูกยืมอยู่” แล้วดูว่าต้องมี class ใหม่หรือไม่",
  },
  "oop-class-object": {
    hook: "ใน M0 ชื่อหนังสืออยู่ใน list หนึ่ง สถานะอยู่อีก list ลบผิดตัวเดียวข้อมูลทั้งชุดเลื่อน object เก็บข้อมูลของสิ่งเดียวกันไว้ด้วยกันเสมอ",
    analogy: {
      title: "class เหมือนแม่พิมพ์ object เหมือนขนมแต่ละชิ้น",
      text: ["แม่พิมพ์บอกรูปร่าง ขนมแต่ละชิ้นที่กดออกมามีหน้าตาเหมือนกันแต่เป็นคนละชิ้น กินชิ้นหนึ่งอีกชิ้นยังอยู่", "class บอกว่ามี field อะไร new สร้าง object ใหม่ที่มี field ชุดของตัวเอง"],
      mapping: [["แม่พิมพ์", "class"], ["ขนมแต่ละชิ้น", "object/instance"], ["กดแม่พิมพ์หนึ่งครั้ง", "new Book()"], ["ป้ายชื่อที่ชี้ไปยังขนม", "ตัวแปรที่เก็บ reference"]],
      limits: "ขนมเปลี่ยนรูปไม่ได้หลังอบ แต่ object เปลี่ยน state ได้ และป้ายหลายอันชี้ขนมชิ้นเดียวกันได้ (b = a) ซึ่งขนมจริงไม่มี",
    },
    explain: [
      { heading: "1) ประกาศและสร้าง", text: ["class Book { int id; String title; boolean borrowed; }", "Book book = new Book(); ได้ object ใหม่ที่ field เป็นค่าเริ่มต้น 0 / null / false"] },
      { heading: "2) แต่ละ instance มี state ของตัวเอง", text: ["first.borrowed = true; ไม่กระทบ second", "ตัวแปรเก็บ reference: Book c = first; ทำให้ c กับ first เป็นตัวเดียวกัน"] },
      { heading: "3) object ใน collection", text: ["ArrayList<Book> เก็บ reference ดึงออกมาแก้ก็คือแก้ object ตัวเดิม", "ไฟล์เดียวมีหลาย class ได้ แต่ public class ได้ตัวเดียวและชื่อต้องตรงกับไฟล์"] },
    ],
    walkthrough: ["สร้างหนังสือสองเล่มและกำหนด field ทีละตัว", "second ถูกยืม first ไม่ถูก", "empty แสดงค่าเริ่มต้น 0 null false", "นับเล่มว่างจาก list ได้ 1/2"],
    pitfalls: ["ประกาศตัวแปรแต่ไม่ new", "คิดว่า b = a คือการคัดลอก object", "ใช้ field ที่เป็น null (title) แล้วเรียก method บนมัน", "ให้ field เปิดตลอดไป (บทต่อไปจะซ่อน)"],
    checks: [
      { question: "Book a = new Book(); Book b = a; b.title = \"X\"; a.title เป็นอะไร", answer: "X เพราะ a และ b ชี้ object เดียวกัน" },
      { question: "field int ที่ไม่ได้กำหนดค่ามีค่าอะไร และตัวแปร int ใน method ล่ะ", answer: "field ได้ 0 อัตโนมัติ ส่วนตัวแปรใน method ต้องกำหนดก่อนใช้ไม่งั้น compile error" },
    ],
    recap: ["class = แบบแปลน; new = object ใหม่", "แต่ละ object มี state ของตัวเอง", "ตัวแปรและ list เก็บ reference"],
    traceHint: "นับจำนวน new เพื่อรู้จำนวน object แล้วลากลูกศรจากตัวแปรแต่ละตัวไปที่ object",
    practiceHints: ["สร้าง Member สองตัวด้วย new แล้วกำหนด id/name", "ใส่ใน list แล้ว members.get(0) ได้ reference ของ Sea", "เพิ่ม loanCount ผ่าน reference ที่ดึงมา แล้ววนพิมพ์"],
    acceptance: [local, "ตรวจเอง: พิมพ์ #1 Sea ยืม 2 เล่ม และ #2 Ton ยืม 0 เล่ม", "ตรวจเอง: การเพิ่ม loanCount ทำผ่าน object ที่ดึงจาก list"],
    solutionNotes: ["fromList กับ sea เป็น object เดียวกัน การแก้ผ่านตัวใดจึงเห็นในทุกที่"],
    reflection: ["ใน M0 ถ้าแทน list สามตัวด้วย ArrayList<Book> ปัญหาไหนหายไปทันที"],
    extension: "เพิ่ม Member ตัวที่สามโดยคัดลอก reference (Member copy = sea;) แล้วเพิ่ม loanCount ของ copy สังเกตผลเมื่อพิมพ์ list",
  },
  "oop-fields-methods": {
    hook: "โค้ดสามที่ในโปรแกรมเขียน book.borrowed = true เอง และมีหนึ่งที่ลืมตรวจว่าถูกยืมอยู่แล้วหรือยัง ผลคือหนังสือเล่มเดียวถูกยืมสองครั้ง ถ้าการยืมเป็น method ของ Book กติกาจะอยู่ที่เดียว",
    explain: [
      { heading: "1) method ทำงานกับ state ของตัวเอง", text: ["boolean checkOut() ใน Book อ่านและแก้ borrowed ของหนังสือเล่มที่ถูกเรียก", "this คือ reference ของ object นั้น ใช้เมื่อชื่อชนกันหรือต้องส่งตัวเองต่อ"] },
      { heading: "2) ภาษาของโดเมน", text: ["checkOut/giveBack บอกเหตุการณ์ที่ผู้ใช้เข้าใจ setBorrowed(true) บอกแค่การเปลี่ยน field", "method ที่อาจไม่สำเร็จคืน boolean ตอนนี้ (บท encapsulation ใช้ exception)"] },
      { heading: "3) query vs command", text: ["isAvailable(), describe() แค่ถาม ไม่เปลี่ยน state", "checkOut() เปลี่ยน state แยกสองแบบให้ชัดทำให้เรียก query กี่ครั้งก็ปลอดภัย"] },
    ],
    walkthrough: ["describe ตอนแรกเป็น available", "checkOut ครั้งแรกสำเร็จ ครั้งที่สองปฏิเสธเพราะ isAvailable เป็นเท็จ", "giveBack ครั้งแรกสำเร็จ ครั้งที่สองปฏิเสธ", "timesBorrowed เพิ่มเฉพาะการยืมที่สำเร็จ"],
    pitfalls: ["parameter ชื่อซ้ำ field แล้วลืม this", "method ที่ทั้งถามและเปลี่ยน state โดยไม่บอกในชื่อ", "ให้ผู้อื่นแก้ field เองแทนเรียก method", "คืน void จากการกระทำที่อาจล้มเหลว"],
    checks: [
      { question: "ทำไม checkOut เรียก isAvailable() แทนการเขียน !borrowed ซ้ำ", answer: "ให้นิยามของ “ว่าง” อยู่ที่เดียว ถ้ากติกาเปลี่ยน (เช่นมีการจอง) แก้ isAvailable ที่เดียว" },
      { question: "void rename(String title) { title = title.strip(); } ทำไม field ไม่เปลี่ยน", answer: "title ใน method หมายถึง parameter ที่บัง field ต้องเขียน this.title = title.strip()" },
    ],
    recap: ["instance method ทำงานกับ this", "ชื่อตามเหตุการณ์ของโดเมน", "แยก query กับ command"],
    traceHint: "เขียนค่า borrowed และ timesBorrowed หลังทุกบรรทัดใน main และดูว่าบรรทัดไหนถูกปฏิเสธ",
    practiceHints: ["canBorrow คืน loanCount < MAX_LOANS", "borrowOne เรียก canBorrow ก่อน ถ้าไม่ได้คืน false", "รวมผลสี่ครั้งของ borrowOne กับหนึ่งครั้งของ returnOne ในข้อความบรรทัดเดียว"],
    acceptance: [local, "ตรวจเอง: พิมพ์ true true true false true และ Sea: 2/3"],
    solutionNotes: ["การต่อ boolean กับ String ด้วย + ได้ข้อความ true/false อัตโนมัติ"],
    reflection: ["มี field ไหนใน M0 ที่ควรถูกแก้ผ่าน method เท่านั้น"],
    extension: "เพิ่ม method boolean transferTo(Member other) ที่ย้ายการยืมหนึ่งรายการไปอีกคน โดยสำเร็จเฉพาะเมื่ออีกคนยืมเพิ่มได้",
  },
  "oop-constructor": {
    hook: "หนังสือที่ไม่มีชื่อโผล่ในรายการเพราะมีโค้ดสร้าง Book แล้วลืมกำหนด title constructor ที่ตรวจข้อมูลทำให้ object ผิดรูปไม่มีทางเกิดขึ้นตั้งแต่แรก",
    explain: [
      { heading: "1) constructor ทำงานครั้งเดียวตอน new", text: ["Book(int id, String title) { ... } ไม่มีชนิดที่คืน ชื่อเดียวกับ class", "เมื่อเขียน constructor เองแล้ว Java ไม่สร้าง constructor เปล่าให้"] },
      { heading: "2) ตรวจก่อนกำหนด", text: ["throw IllegalArgumentException พร้อมค่าที่ผิด แล้ว new จะไม่คืน object เลย", "final field ต้องได้ค่าในทุกเส้นทางของ constructor"] },
      { heading: "3) this(...) และ toString", text: ["this(id, title, true) เรียก constructor หลัก ให้การตรวจอยู่ที่เดียว", "toString ใช้แสดง object ใน println และ log"] },
    ],
    walkthrough: ["Clean Code ถูก strip ได้ #1 Clean Code", "constructor สองพารามิเตอร์เรียก this(...) ด้วย loanable = true", "ชื่อว่างและ id 0 ถูกปฏิเสธพร้อมข้อความ"],
    pitfalls: ["ตรวจหลังกำหนด field", "return ออกจาก constructor แทนการ throw", "เขียนการตรวจซ้ำในหลาย constructor", "ข้อความ exception ที่ไม่บอกค่าที่ผิด"],
    checks: [
      { question: "ถ้า constructor throw ตัวแปรที่รับ new จะได้อะไร", answer: "ไม่ได้อะไร การกำหนดค่าไม่เกิดขึ้น exception ส่งต่อไปยังผู้เรียก" },
      { question: "ทำไม this(...) ต้องเป็นบรรทัดแรก", answer: "Java บังคับให้การสร้าง object ผ่าน constructor หลักก่อนทำอย่างอื่น เพื่อไม่ให้ใช้ field ที่ยังไม่ถูกตั้งค่า" },
    ],
    recap: ["constructor รับข้อมูลจำเป็นทั้งหมด", "ตรวจแล้ว throw ก่อนกำหนด", "this(...) และ toString"],
    traceHint: "สำหรับแต่ละ new ไล่ว่าเข้า constructor ไหน ผ่าน/ไม่ผ่านการตรวจข้อไหน และพิมพ์อะไร",
    practiceHints: ["constructor หลักตรวจสามเงื่อนไขตามลำดับ id, name, maxLoans", "constructor สั้นเรียก this(id, name, 3)", "toString คืน #id name (max n) และ main จับ IllegalArgumentException ตอนสร้าง Fon"],
    acceptance: [local, "ตรวจเอง: พิมพ์ #1 Sea (max 3), #2 Ton (max 5) และ rejected: พร้อมค่า 0", "ตรวจเอง: ทั้งสาม field เป็น final"],
    solutionNotes: ["ข้อความระบุช่วงและค่าที่ผิด ทำให้ debug จาก log ได้โดยไม่ต้องเดา"],
    reflection: ["object ใดใน Library CLI ที่ไม่ควรมีอยู่ถ้าข้อมูลไม่ครบ"],
    extension: "เพิ่ม static factory Member.student(int id, String name) ที่คืน Member maxLoans 5 แล้วเทียบกับการใช้ constructor ตรง ๆ",
  },
  "oop-identity": {
    hook: "ซีโหลดรายชื่อสมาชิกจากไฟล์ใหม่ แล้ว members.contains(sea) ตอบ false ทั้งที่เป็นคนเดิม เพราะ Java ไม่รู้ว่าสมาชิกสองตัว “เป็นคนเดียวกัน” เมื่อไร จนกว่าเราจะบอก",
    explain: [
      { heading: "1) == vs equals", text: ["== กับ object เทียบว่าเป็นตัวเดียวกันในหน่วยความจำ", "equals ค่าเริ่มต้นก็เทียบแบบเดียวกัน ต้อง override เพื่อเทียบตามความหมาย"] },
      { heading: "2) entity เทียบด้วย id", text: ["สมาชิกที่เปลี่ยนชื่อหรือ loanCount ยังเป็นคนเดิม จึงเทียบแค่ id", "รูปแบบ: this == other → true; other instanceof Member m && id == m.id"] },
      { heading: "3) equals ต้องมาคู่ hashCode", text: ["HashSet/HashMap ใช้ hashCode หาช่องก่อนแล้วจึงเรียก equals", "ArrayList.contains/indexOf ใช้แค่ equals จึงอาจดูถูกทั้งที่ hashCode ผิด"] },
    ],
    walkthrough: ["loaded == same จริง แต่ loaded == loadedAgain เท็จ ส่วน equals จริง", "list.contains และ indexOf หาเจอแม้ชื่อเปลี่ยน", "HashSet เก็บแค่ 2 ตัว", "Note ไม่ override equals จึงเทียบ reference ได้ false"],
    pitfalls: ["เขียน equals(Member other) ซึ่งเป็น overload", "override equals แต่ไม่ override hashCode", "เทียบทุก field ของ entity ที่ state เปลี่ยนได้", "เปลี่ยน field ที่ใช้ใน hashCode หลังใส่ใน HashSet"],
    checks: [
      { question: "ทำไมควรใส่ @Override บน equals", answer: "ถ้าเขียน signature ผิด (เช่นรับ Member แทน Object) compiler จะแจ้งทันทีแทนที่จะได้ overload ที่ไม่มีใครเรียก" },
      { question: "สอง object ที่ equals กันต้องมี hashCode เท่ากันเสมอไหม แล้วกลับกันล่ะ", answer: "ต้องเท่ากันเสมอ แต่ hashCode เท่ากันไม่จำเป็นต้อง equals (ชนกันได้)" },
    ],
    recap: ["== identity; equals equality", "entity: equals/hashCode ตาม id", "override ทั้งคู่เสมอ"],
    traceHint: "ทุกครั้งที่ collection ค้นหา ให้ถามว่ามันใช้ equals อย่างเดียว (ArrayList) หรือ hashCode ก่อน (HashSet)",
    practiceHints: ["equals ใช้ other instanceof Member member && id == member.id", "hashCode คืน Integer.hashCode(id)", "indexOf(reloaded) ได้ 0 แล้ว set(0, reloaded)"],
    acceptance: [local, "ตรวจเอง: พิมพ์ 0 [Sea Wee, Ton] และ 2"],
    solutionNotes: ["loanCount ไม่ได้อยู่ใน equals/hashCode เพราะเปลี่ยนได้โดยที่ยังเป็นสมาชิกคนเดิม"],
    reflection: ["object ไหนใน Library ที่ควรเทียบด้วย id และอันไหนควรเทียบด้วยค่าทั้งหมด"],
    extension: "เพิ่ม field email ใน Member แล้วอธิบายว่าควรอยู่ใน equals/hashCode หรือไม่ ถ้าสมาชิกเปลี่ยนอีเมลได้ — ลองใส่ทั้งสองแบบแล้วทดสอบกับ HashSet หลังเปลี่ยนอีเมล",
  },
  "oop-static": {
    hook: "ซีเขียน test สอง test ที่สร้าง Catalog ใหม่ test แรกผ่าน test ที่สองได้ id เริ่มที่ 3 เพราะตัวนับเป็น static และค้างจาก test ก่อน",
    explain: [
      { heading: "1) ของ class vs ของ object", text: ["static field มีชุดเดียวต่อ class ทุก object ใช้ร่วมกัน", "static method ไม่มี this ใช้ instance field ตรง ๆ ไม่ได้"] },
      { heading: "2) static ที่ดี", text: ["ค่าคงที่ static final", "function บริสุทธิ์ที่คำนวณจาก parameter (LoanPolicy.fineFor)", "factory method ที่สร้าง object"] },
      { heading: "3) static ที่อันตราย", text: ["static field ที่เปลี่ยนค่าได้ = global state ผลขึ้นกับลำดับการทำงาน", "ย้ายไปเป็น instance field ของ object ที่เป็นเจ้าของ (Catalog ถือตัวนับเอง)"] },
    ],
    walkthrough: ["fineFor เรียกผ่านชื่อ class ได้ 15 และ 100", "GlobalIds ถูกเรียกไปแล้วสองครั้ง ครั้งถัดไปจึงได้ 3", "Catalog สองแห่งมีตัวนับของตัวเอง ต่างก็เริ่มที่ 1"],
    pitfalls: ["เติม static ให้ทุกอย่างเพื่อให้ main compile", "ตัวนับ id แบบ static", "static method ที่อ่าน static field ที่เปลี่ยนได้", "ใช้ static เพื่อ “แชร์ข้อมูล” แทนการส่ง object"],
    checks: [
      { question: "Math.max เป็น static ทำไมจึงเหมาะสม", answer: "ผลขึ้นกับ parameter เท่านั้น ไม่มี state ให้จำ จึงไม่ต้องมี object" },
      { question: "ถ้ามีห้องสมุดสองสาขาในโปรแกรมเดียว อะไรใน M0 ที่พัง", answer: "ทุก list และตัวนับเป็น static จึงมีได้ชุดเดียว สองสาขาจะใช้ข้อมูลเดียวกัน" },
    ],
    recap: ["static = ของ class; instance = ของ object", "static final และ function บริสุทธิ์ใช้ได้ดี", "หลีกเลี่ยง static ที่เปลี่ยนค่าได้"],
    traceHint: "แยกตารางสองส่วน: ค่า static (ชุดเดียว) และค่า instance ของแต่ละ object แล้วไล่แต่ละการเรียก",
    practiceHints: ["Catalog มี private int nextId = 1 และ ArrayList ของบรรทัด", "add ใส่บรรทัดแล้วคืน nextId++", "LoanPolicy มีแค่ static final และ static method"],
    acceptance: [local, "ตรวจเอง: catalog ที่สองเริ่มที่ #1", "ตรวจเอง: พิมพ์ true false จาก canBorrow"],
    solutionNotes: ["String.join(\"\\n\", titles) รวมบรรทัดโดยไม่มีบรรทัดว่างท้าย"],
    reflection: ["มีอะไรในโค้ดที่เคยเขียนที่เป็น static เพียงเพราะ main เป็น static"],
    extension: "เปลี่ยน main ให้สร้าง new App().run() แล้วย้ายทุก state ของโปรแกรมเป็น instance field ของ App",
  },
  "oop-encapsulation": {
    hook: "Member มี field เป็น private ครบทุกตัว แต่ getLoans() คืน list ตัวจริง มีโค้ดอีกไฟล์ add เล่มที่สี่เข้าไปตรง ๆ โควตาพังโดยไม่มีใครผ่านกติกา",
    analogy: {
      title: "encapsulation เหมือนตู้ ATM",
      text: ["ATM ไม่เปิดให้ลูกค้าหยิบเงินในตู้เอง ทุกการถอนต้องผ่านหน้าจอที่ตรวจยอดและวงเงิน", "ใบแจ้งยอดที่ได้เป็นแค่สำเนา ขีดเขียนบนกระดาษไม่ได้เปลี่ยนยอดในบัญชี"],
      mapping: [["เงินในตู้", "private field"], ["เมนูถอน/ฝาก", "method ที่ตรวจกติกา"], ["ปฏิเสธเมื่อเกินวงเงิน", "throw IllegalStateException"], ["ใบแจ้งยอด", "List.copyOf ที่คืนให้ผู้เรียก"]],
      limits: "ATM มีกลไกป้องกันทางกายภาพ แต่ private ป้องกันแค่ระดับโค้ด: ใครแก้ class เองหรือใช้ reflection ก็ข้ามได้ encapsulation จึงเป็นการออกแบบให้ใช้ถูกได้ง่าย ไม่ใช่ระบบความปลอดภัย",
    },
    explain: [
      { heading: "1) private + method ที่ตรวจกติกา", text: ["field เป็น private การเปลี่ยนทุกครั้งต้องผ่าน method", "ไม่สร้าง setter ให้ทุก field โดยอัตโนมัติ"] },
      { heading: "2) ปฏิเสธด้วย exception", text: ["IllegalStateException: สถานะตอนนี้ทำไม่ได้ (ยืมครบแล้ว)", "IllegalArgumentException: argument ผิด (คืนเล่มที่ไม่ได้ยืม)"] },
      { heading: "3) อย่าปล่อย reference ภายในออกไป", text: ["คืน List.copyOf(loans) (สำเนา) หรือ Collections.unmodifiableList(loans) (มุมมองที่แก้ไม่ได้)", "list ที่รับเข้ามาใน constructor ก็คัดลอกก่อนเก็บ"] },
    ],
    walkthrough: ["ยืมสองเล่มผ่าน borrow", "เล่มที่สามถูกปฏิเสธด้วยข้อความ", "view เป็นสำเนาที่แก้ไม่ได้ add จึงได้ UnsupportedOperationException", "คืน Clean Code แล้ว loans() ใหม่เหลือ [Java 21] แต่ view เดิมไม่เปลี่ยน"],
    pitfalls: ["getter คืน collection ตัวจริง", "setter สำหรับทุก field", "เงียบเมื่อทำไม่ได้แทนการ throw", "เก็บ list ที่ผู้อื่นส่งมาโดยไม่คัดลอก"],
    checks: [
      { question: "List.copyOf กับ Collections.unmodifiableList ต่างกันอย่างไร", answer: "copyOf เป็นสำเนา ณ ขณะนั้น ไม่เห็นการเปลี่ยนภายหลัง ส่วน unmodifiableList เป็นมุมมองของ list จริงที่แก้ผ่านมันไม่ได้แต่เห็นการเปลี่ยนแปลง" },
      { question: "ทำไม Book ไม่ควรมี setBorrowedBy", answer: "จะข้ามการตรวจว่าถูกยืมอยู่แล้วหรือไม่ การเปลี่ยนสถานะควรผ่าน checkOut/giveBack ที่ตรวจกติกา" },
    ],
    recap: ["private + method ที่บังคับกติกา", "throw เมื่อทำไม่ได้", "คืนสำเนา ไม่คืน reference ภายใน"],
    traceHint: "ไล่ทุกเส้นทางที่ field ถูกแก้ได้ ถ้ามีเส้นทางที่ไม่ผ่านการตรวจ encapsulation ยังรั่ว",
    practiceHints: ["isAvailable คือ borrowedBy == null", "checkOut ตรวจชื่อก่อน แล้วตรวจสถานะ แล้วจึงกำหนด", "main ใช้ try/catch รอบการยืมของ Ton และการคืนซ้ำ"],
    acceptance: [local, "ตรวจเอง: ผลห้าบรรทัดตรงตามลำดับในโจทย์", "ตรวจเอง: class Book ไม่มี setter"],
    solutionNotes: ["status() เป็น query ที่ประกอบข้อความจาก state โดยไม่เปิด field"],
    reflection: ["method ไหนของ M1 ที่ยังเปิดช่องให้ข้ามกติกาได้"],
    extension: "เพิ่ม history ใน Book ที่เก็บชื่อผู้ยืมทุกคน และ method history() ที่คืนสำเนาแบบแก้ไม่ได้",
  },
  "oop-project-library-1": {
    hook: "M0 ทำงานได้ แต่ทุกการแก้ต้องดูแล list สามตัว M1 แทนทั้งหมดด้วย object ที่รักษากติกาเอง แล้วพิสูจน์ด้วยไฟล์ทดสอบว่าพฤติกรรมยังชัดเจนทุกข้อความ",
    explain: [
      { heading: "1) เขียน fixture ก่อน", text: ["แปลงข้อกำหนดเป็น test-input.txt และ expected-output.txt ก่อนเขียนโค้ด", "ทุกข้อความตอบกลับต้องปรากฏอย่างน้อยหนึ่งครั้ง"] },
      { heading: "2) object ที่รู้หน้าที่", text: ["Book ตรวจการยืม/คืน Member ตรวจชื่อ Catalog ถือรายการและออก id", "Main เป็นที่เดียวที่อ่าน input และพิมพ์"] },
      { heading: "3) exception เป็นข้อความ", text: ["Book throw IllegalStateException(\"already borrowed\")", "Main catch แล้วพิมพ์ getMessage() จึงไม่ต้องมี if ซ้ำกับกติกา"] },
    ],
    walkthrough: ["สร้างหนังสือสองเล่มใน list", "ยืมเล่มแรกสำเร็จ ครั้งที่สอง throw already borrowed", "toString ของแต่ละเล่มแสดงสถานะ"],
    pitfalls: ["ใช้ static Catalog ต่อจาก M0", "เพิ่ม id ก่อนสร้าง object สำเร็จ", "ข้อความไม่ตรง expected", "Main ตรวจกติกาซ้ำกับ Book"],
    checks: [
      { question: "ทำไม Catalog เป็น instance ไม่ใช่ static", answer: "สร้างหลาย catalog ได้ (เช่นใน test) และไม่มี state ค้างข้ามการใช้งาน" },
      { question: "multi-catch IllegalArgumentException | IllegalStateException ช่วยอะไร", answer: "แปลง exception ของกติกาทั้งสองแบบเป็นข้อความในที่เดียว" },
    ],
    recap: ["fixture ก่อนโค้ด", "Book/Member/Catalog แบ่งหน้าที่", "Main แปลง exception เป็นข้อความ"],
    traceHint: "ไล่ test-input ทีละบรรทัด เขียนว่าเรียก method ไหนของ Catalog/Book และได้ข้อความหรือ exception อะไร",
    practiceHints: ["เขียน Book ให้ checkOut/giveBack throw ข้อความตรงข้อกำหนด", "Catalog สร้าง object ให้สำเร็จก่อนแล้วจึงเพิ่ม nextId", "Main.handle คืน String และ main พิมพ์เท่านั้น"],
    acceptance: [local, "ตรวจเอง: java -cp out library.Main < test-input.txt ตรงกับ expected-output.txt ทุกบรรทัด", "ตรวจเอง: ไม่มี static field ที่เปลี่ยนค่าได้"],
    solutionNotes: ["joinLines รับ ArrayList<?> เพื่อใช้ร่วมกับ Book และ Member โดยเรียก toString", "ข้อความ title required มาจาก constructor ของ Book จึงตรงกันทุกที่ที่สร้างหนังสือ"],
    reflection: ["เทียบกับ M0 การเพิ่มกติกาใหม่ตอนนี้แก้กี่ที่"],
    extension: "เพิ่มคำสั่ง rename <id> <title> ที่ใช้กติกาเดียวกับ constructor ในการตรวจชื่อ",
  },
  "oop-composition": {
    hook: "ซีเขียน class Shelf extends ArrayList<Book> เพราะอยากได้ add และ size มาฟรี วันต่อมามีคนเรียก add ที่สืบทอดมาจนชั้นเกินความจุ",
    explain: [
      { heading: "1) has-a", text: ["Loan มี Book, Member มีรายการ Loan — เก็บเป็น private field", "ทดสอบด้วยประโยค “X มี Y” vs “X เป็น Y”"] },
      { heading: "2) delegation", text: ["object ใหญ่ส่งงานให้ส่วนประกอบ: member.totalLateDays เรียก loan.lateDays", "กติกาอยู่กับส่วนประกอบที่มีข้อมูล"] },
      { heading: "3) เปิดเท่าที่จำเป็น", text: ["Shelf เปิดแค่ add ที่ตรวจความจุ size และ titles", "เปลี่ยน ArrayList ข้างในเป็นอย่างอื่นได้โดยผู้ใช้ไม่รู้"] },
    ],
    walkthrough: ["Sea มีสองการยืม ครบกำหนดวันที่ 10 และ 20", "วันที่ 15 Clean Code ช้า 5 วัน Java 21 ยังไม่ช้า", "Member รวมวันช้าโดยถาม Loan แต่ละตัว"],
    pitfalls: ["extends collection เพื่อได้ method", "เก็บข้อมูลซ้ำแทนการถามส่วนประกอบ", "คืนส่วนประกอบที่แก้ได้ออกไปตรง ๆ", "ใช้ inheritance เมื่อไม่ใช่ is-a"],
    checks: [
      { question: "ทำไม Loan ไม่เก็บชื่อหนังสือเป็น String", answer: "ถ้าชื่อหนังสือเปลี่ยน Loan จะเก็บค่าเก่า การอ้างถึง Book ทำให้มีแหล่งข้อมูลเดียว" },
      { question: "Shelf ที่ extends ArrayList มีปัญหาอะไรนอกจาก add", answer: "ได้ addAll, set, add(index, …) ฯลฯ ที่ข้ามกติกาได้ทั้งหมด และเปลี่ยนการเก็บข้อมูลภายหลังไม่ได้โดยไม่กระทบผู้ใช้" },
    ],
    recap: ["has-a → composition", "delegate งานให้เจ้าของข้อมูล", "เปิดเฉพาะ method ของโดเมน"],
    traceHint: "วาดกล่อง Member ที่มีกล่อง Loan อยู่ข้างใน และแต่ละ Loan ชี้ไปที่ Book แล้วไล่การเรียก method ตามลูกศร",
    practiceHints: ["Shelf มี private ArrayList<Book> และ capacity", "add ปฏิเสธเมื่อเต็มหรือ contains (ใช้ equals ตาม id)", "titles รวมชื่อด้วย String.join(\", \", ...)"],
    acceptance: [local, "ตรวจเอง: พิมพ์ true false true false และ 2: Clean Code, Java 21", "ตรวจเอง: Shelf ไม่ extends อะไร"],
    solutionNotes: ["การตรวจซ้ำใช้ equals ของ Book จากบท identity โดยไม่ต้องรู้ว่า Book เทียบอย่างไร"],
    reflection: ["มี class ไหนที่เคยเขียนด้วย inheritance แต่จริง ๆ ควรเป็น has-a"],
    extension: "เพิ่ม Library ที่มีหลาย Shelf และ method place(Book) ที่หาชั้นแรกที่ยังว่าง",
  },
  "oop-collaboration": {
    hook: "ระบบบอกว่า Sea ยืมครบโควตาแล้ว แต่หนังสือกลับถูกทำเครื่องหมายว่า Sea ยืมไป ข้อมูลสองที่ขัดกันเพราะเปลี่ยนฝ่ายหนึ่งก่อนตรวจอีกฝ่าย",
    analogy: {
      title: "ประสานงานแบบ “ตรวจครบแล้วค่อยลงมือ” เหมือนการจองตั๋วเครื่องบินพร้อมโรงแรม",
      text: ["เอเจนต์ตรวจว่ามีที่นั่งและมีห้องว่างก่อน แล้วจึงจองทั้งสองอย่าง ถ้าจองตั๋วไปแล้วจึงพบว่าโรงแรมเต็ม ลูกค้าจะมีตั๋วที่ไม่ต้องการ", "Library ตรวจโควตาสมาชิกและสถานะหนังสือก่อน แล้วจึงผูก Loan กับทั้งสองฝ่าย"],
      mapping: [["เอเจนต์", "Library (coordinator)"], ["สายการบิน / โรงแรม", "Book / Member"], ["ตรวจที่ว่างทั้งสองก่อนจอง", "check-then-act"], ["ใบยืนยันการจองใบเดียว", "Loan object ที่ทั้งสองฝ่ายอ้างถึง"]],
      limits: "ระบบจองจริงต้องรับมือคนจองพร้อมกันหลายคนและการล่มกลางทาง (ต้องใช้ transaction ในฐานข้อมูล) โปรแกรมนี้ทำงานทีละคำสั่งในหน่วยความจำ การตรวจครบก่อนจึงพอ",
    },
    explain: [
      { heading: "1) coordinator", text: ["Library หา object ถามเงื่อนไข แล้วสั่งเปลี่ยน", "ไม่ตัดสินแทน: ถาม member.canBorrow() และ book.isAvailable()"] },
      { heading: "2) ตรวจทั้งหมดก่อนเปลี่ยน", text: ["ถ้าเงื่อนไขใดไม่ผ่าน ยังไม่มีใครถูกแก้", "แต่ละฝ่ายยังป้องกันตัวเอง (attach/addLoan throw) เป็นด่านสุดท้าย"] },
      { heading: "3) ข้อมูลสองฝั่งจาก object เดียว", text: ["Loan หนึ่งตัวถูกเก็บทั้งใน Book และ Member", "การคืนต้องถอดออกทั้งสองฝั่งเสมอ"] },
    ],
    walkthrough: ["Sea ยืม Clean Code ได้ ครบกำหนดวันที่ 15", "Sea ยืม Java 21 ไม่ได้เพราะโควตา 1 และไม่มีอะไรเปลี่ยน", "Ton ยืม Clean Code ไม่ได้เพราะถูกยืมอยู่", "สถานะสุดท้ายสอดคล้องกันทั้งสามฝ่าย"],
    pitfalls: ["เปลี่ยน state ก่อนตรวจครบ", "ถอด Loan ออกจากฝั่งเดียว", "เก็บสำเนาข้อมูลแยกสองที่", "coordinator รู้รายละเอียดภายในของทุกฝ่าย"],
    checks: [
      { question: "ทำไม Book.attach ยัง throw แม้ Library ตรวจ isAvailable แล้ว", answer: "เป็นด่านป้องกันเมื่อมีโค้ดอื่นเรียก attach โดยไม่ผ่าน Library หรือ Library มีบั๊ก กติกาของ Book จึงยังเป็นจริงเสมอ" },
      { question: "ในการคืน ควรถอด Loan ออกจาก Book หรือ Member ก่อน", answer: "ลำดับไม่สำคัญเมื่อตรวจแล้วว่าทำได้ทั้งคู่ สิ่งสำคัญคือทำทั้งสองให้ครบใน method เดียว" },
    ],
    recap: ["coordinator ถามแล้วสั่ง", "ตรวจครบก่อนเปลี่ยน", "Loan เดียวเชื่อมสองฝั่ง"],
    traceHint: "ทำตารางสามคอลัมน์ (Book.currentLoan, Member.loans, ผลลัพธ์) หลังทุกการเรียก borrow/giveBack",
    practiceHints: ["giveBack ตรวจ isAvailable ก่อน ถ้าว่างคืนข้อความทันที", "อ่าน loan จาก book.currentLoan() คำนวณวันช้าและค่าปรับ", "detach ที่ Book และ removeLoan ที่ Member แล้วจึงคืนข้อความ"],
    acceptance: [local, "ตรวจเอง: ผลห้าบรรทัดตามโจทย์ รวม Sea ยืม Java 21 ได้หลังคืน", "ตรวจเอง: หลังคืน Clean Code ว่างและ Sea ไม่มี Loan ค้าง"],
    solutionNotes: ["FINE_PER_DAY เป็นค่าคงที่ของ Library ในตอนนี้ บท interfaces จะแยกเป็นนโยบายที่สลับได้"],
    reflection: ["use case ไหนของ Library ที่ต้องแก้สามฝ่ายพร้อมกัน และจะตรวจอย่างไรให้ครบ"],
    extension: "เพิ่ม transfer(Book, Member to) ที่ย้ายการยืมไปอีกคนโดยตรวจโควตาของผู้รับก่อน และถ้าไม่ผ่านไม่มีอะไรเปลี่ยน",
  },
  "oop-project-library-2": {
    hook: "ห้องสมุดชุมชนต้องรู้ว่าใครยืมเล่มไหน ครบกำหนดเมื่อไร และค้างค่าปรับเท่าไร M2 รวม composition กับ collaboration เป็นระบบที่ตอบคำถามเหล่านี้ได้ทุกครั้งอย่างสอดคล้อง",
    explain: [
      { heading: "1) ข้อกำหนดก่อน", text: ["ลำดับการตรวจของ borrow ถูกกำหนดไว้ จึงเขียน expected-output ได้ก่อนเขียนโค้ด", "วันเป็นตัวเลข (day 20) ทำให้ทดสอบค่าปรับได้แน่นอนโดยไม่พึ่งนาฬิกาจริง"] },
      { heading: "2) Loan เชื่อมสองฝ่าย", text: ["Book รู้ Loan ปัจจุบัน Member รู้รายการ Loan", "list แสดงผู้ยืมจาก loan.member() ไม่ใช่ข้อมูลซ้ำ"] },
      { heading: "3) Main แปลง input", text: ["Integer ที่เป็น null แทนการแปลงไม่ได้ ทำให้ตรวจ usage ได้ที่เดียว", "ข้อความ exception จาก Library ตรงตามข้อกำหนด Main แค่พิมพ์"] },
    ],
    walkthrough: ["ยืมวันที่ 1 ครบกำหนดวันที่ 15", "คืนวันที่ 15 ไม่ช้า วันที่ 20 ช้า 5 วันปรับ 25", "วันที่ 60 ช้า 45 วัน ค่าปรับถูกจำกัดที่ 100"],
    pitfalls: ["ลำดับการตรวจไม่ตรงข้อกำหนด", "คำนวณค่าปรับหลังถอด Loan แล้วอ่านวันครบกำหนดไม่ได้", "ให้วันย้อนกลับได้", "เก็บผู้ยืมสองที่แยกกัน"],
    checks: [
      { question: "ทำไม Main คำนวณ late ก่อนเรียก giveBack", answer: "หลัง giveBack หนังสือไม่มี Loan แล้ว จึงอ่านวันช้าไม่ได้ (เฉลยแยก lateDays ไว้ใน Library)" },
      { question: "วันที่ใช้คำนวณครบกำหนดคือวันไหน", answer: "วันปัจจุบันของ Library ตอนยืม + 14 ไม่ใช่วันที่ 1 เสมอ" },
    ],
    recap: ["ข้อกำหนด + fixture", "Loan เดียวเชื่อม Book กับ Member", "วันเป็นข้อมูล ทดสอบได้"],
    traceHint: "ทำตาราง: today, ผู้ยืมของแต่ละเล่ม, loans ของแต่ละคน แล้วไล่ test-input ทีละบรรทัด",
    practiceHints: ["เริ่มจาก Loan และ lateDays แล้วจึง Book/Member", "Library.borrow ตรวจตามลำดับ book → member → ว่าง → โควตา ก่อนเปลี่ยนอะไร", "Main แยกคำแรกเป็นคำสั่งและใช้ helper number() คืน null เมื่อแปลงไม่ได้"],
    acceptance: [local, "ตรวจเอง: java -cp out library.cli.Main < test-input.txt ได้ผลตรง expected-output ทุกบรรทัด", "ตรวจเอง: Main อยู่ใน library.cli และเรียก attach/detach ของ Book ไม่ได้ (compile error ถ้าลอง)", "ตรวจเอง: ไม่มี static field ที่เปลี่ยนค่าได้"],
    solutionNotes: ["findBook/findMember throw ข้อความตามข้อกำหนด ทำให้ทุกคำสั่งที่ต้องหา object ได้ข้อความเดียวกัน", "Member.loans() คืน List.copyOf ผู้อื่นแก้รายการยืมไม่ได้", "private field อย่างเดียวไม่พอเมื่อ Main อยู่ package เดียวกับ Book: Main จะเรียก detach ได้ตรง ๆ การแยก Main ไป library.cli ทำให้ทางเดียวที่เปลี่ยนการยืมคือผ่าน Library", "ค่าปรับคำนวณด้วย (long) ก่อน Math.min เพราะ lateDays × 5 อาจเกินช่วง int เมื่อวันมาก และ setDay จำกัดไม่เกิน 1000000"],
    reflection: ["ถ้าต้องเพิ่มการจองหนังสือ ส่วนไหนของโครงสร้างนี้ช่วย และส่วนไหนต้องปรับ"],
    extension: "เพิ่มคำสั่ง overdue ที่แสดงการยืมที่เลยกำหนดทั้งหมด เรียงตามวันครบกำหนด",
  },
  "oop-interfaces": {
    hook: "ห้องสมุดเพิ่มอัตราค่าปรับนักเรียน แล้วก็สัปดาห์งดค่าปรับ แล้วก็สมาชิกพรีเมียม Library เต็มไปด้วย if ตามประเภท interface ทำให้แต่ละกติกาเป็น class ของตัวเองและสลับได้",
    analogy: {
      title: "interface เหมือนเต้ารับไฟฟ้ามาตรฐาน",
      text: ["บ้านไม่สนว่าเครื่องใช้ไฟฟ้ายี่ห้ออะไร ขอแค่ปลั๊กตรงมาตรฐานก็เสียบใช้ได้ เปลี่ยนพัดลมเป็นเครื่องฟอกอากาศก็ไม่ต้องเดินสายใหม่", "Checkout ขอแค่ “อะไรก็ได้ที่ fineFor ได้” เปลี่ยนกติกาโดยไม่แก้ Checkout"],
      mapping: [["มาตรฐานเต้ารับ", "interface FinePolicy"], ["เครื่องใช้ไฟฟ้าแต่ละแบบ", "StandardFine, StudentFine"], ["เสียบปลั๊ก", "ส่ง policy เข้า constructor"], ["บ้าน", "Checkout ที่ใช้ policy"]],
      limits: "ปลั๊กตรงมาตรฐานไม่รับประกันว่าเครื่องทำงานถูก interface ก็บังคับแค่ signature ไม่ได้บังคับความหมาย (เช่นค่าปรับต้องไม่ติดลบ) ต้องเขียนในเอกสารและ test",
    },
    explain: [
      { heading: "1) ประกาศและ implements", text: ["interface มี method ที่ไม่มีตัว class ต้อง implements ครบทุกตัว", "method ใน interface เป็น public ฝั่ง class จึงต้อง public ด้วย"] },
      { heading: "2) ใช้ผ่านชนิด interface", text: ["FinePolicy policy = new StudentFine(); เรียกได้แค่ method ของ interface", "dependency injection: Checkout รับ policy ใน constructor"] },
      { heading: "3) lambda กับ functional interface", text: ["interface ที่มี abstract method เดียวสร้างด้วย lambda: lateDays -> 0", "default method ให้พฤติกรรมเริ่มต้นได้"] },
    ],
    walkthrough: ["สาม policy คำนวณ 0, 3, 30 วันต่างกัน", "bookWeek เป็น lambda คืน 0 เสมอ", "Checkout ใช้ StudentFine คิด 4 วันเป็น 8 บาท"],
    pitfalls: ["signature ไม่ตรง interface (int vs long)", "ลืม public ใน class", "new implementation เองภายใน object ที่ใช้", "interface ใหญ่ที่บังคับ method ไม่จำเป็น"],
    checks: [
      { question: "ถ้า Checkout สร้าง new StandardFine() เองใน constructor เสียอะไรไป", answer: "เปลี่ยนกติกาไม่ได้โดยไม่แก้ Checkout และ test ส่ง policy ง่าย ๆ เข้าไปไม่ได้" },
      { question: "class หนึ่ง implements หลาย interface ได้ไหม", answer: "ได้ เช่น class StudentFine implements FinePolicy, Describable" },
    ],
    recap: ["interface = สัญญา", "ใช้ผ่านชนิด interface + inject", "functional interface + lambda"],
    traceHint: "สำหรับแต่ละการเรียก fineFor ดูว่าตัวแปรชี้ object ของ class ไหน แล้วใช้สูตรของ class นั้น",
    practiceHints: ["LoanRule มี String check(int, int)", "MaxLoansRule รับ max ใน constructor ส่วน NoOverdueRule ไม่ต้องมี field", "BorrowGate.decide ถามกฎแรกก่อน ถ้าได้ null จึงถามกฎที่สอง"],
    acceptance: [local, "ตรวจเอง: พิมพ์ ok / loan limit reached / return overdue books first / loan limit reached", "ตรวจเอง: BorrowGate ไม่รู้จัก MaxLoansRule หรือ NoOverdueRule โดยตรง"],
    solutionNotes: ["กรณี (2,3) ผิดสองข้อ ได้เหตุผลของกฎแรกเพราะ BorrowGate ถามตามลำดับ", "บท polymorphism จะเปลี่ยนเป็น List<LoanRule> เพื่อรับกี่กฎก็ได้"],
    reflection: ["กติกาไหนในระบบที่เคยทำที่เปลี่ยนบ่อยและควรเป็น interface"],
    extension: "เขียน NoOverdueRule เป็น lambda แทน class แล้วเทียบความอ่านง่าย",
  },
  "oop-polymorphism": {
    hook: "ห้องสมุดเพิ่มนิตยสาร แล้วนิตยสารทุกเล่มต้องคืนวันเดียวกับที่ยืม เพราะ if ตามชนิดในโค้ดคำนวณวันครบกำหนดไม่มีกิ่งของนิตยสาร และไม่มีอะไรเตือน",
    explain: [
      { heading: "1) static type vs runtime type", text: ["compiler ดู static type ว่าเรียก method อะไรได้", "JVM ดู runtime type ว่าจะรันโค้ดของ class ไหน (dynamic dispatch)"] },
      { heading: "2) แทน if ตามชนิดด้วย method", text: ["ย้ายคำถาม “ยืมได้กี่วัน” เข้าไปเป็น loanDays() ของแต่ละชนิด", "ชนิดใหม่ต้อง implements interface compiler บังคับให้ตอบเอง"] },
      { heading: "3) instanceof เมื่อจำเป็น", text: ["ใช้เมื่อต้องเรียกสิ่งที่มีเฉพาะชนิดนั้น เช่น dvd.minutes()", "ถ้าใช้เพื่อเลือกพฤติกรรม ให้ถามว่าควรเป็น method ของ interface ไหม"] },
    ],
    walkthrough: ["loop เรียก describe และ loanDays ผ่าน LibraryItem", "Magazine override describe ส่วน Book/Dvd ใช้ default", "instanceof pattern ได้ตัวแปร dvd ที่เรียก minutes() ได้"],
    pitfalls: ["if/instanceof chain สำหรับพฤติกรรมที่ควรเป็น method", "List<Object> แทน List ของ interface", "cast โดยไม่ตรวจชนิด", "ลืม override default method ที่ไม่เหมาะกับชนิดใหม่"],
    checks: [
      { question: "default method ใน interface ถูกเรียกเมื่อไร", answer: "เมื่อ class ไม่ได้ override ถ้า override JVM เรียกของ class" },
      { question: "การเพิ่ม ReferenceBook ต้องแก้ loanablesDue ไหม", answer: "ไม่ต้อง loanablesDue ถาม isLoanable() ของ interface ชนิดใหม่ตอบเอง" },
    ],
    recap: ["dynamic dispatch ตาม runtime type", "พฤติกรรมตามชนิด → method ของ interface", "instanceof เฉพาะเมื่อจำเป็นจริง"],
    traceHint: "สำหรับแต่ละ item ใน list เขียน runtime type แล้วหาว่า method ที่เรียกถูกเขียนไว้ที่ class นั้นหรือเป็น default",
    practiceHints: ["ReferenceBook.loanDays() คืน 0 และ override describe", "isLoanable เป็น default method: loanDays() > 0", "loanablesDue วนทุก item ถาม isLoanable แล้วรวมบรรทัด"],
    acceptance: [local, "ตรวจเอง: describe ห้าบรรทัดแรกและ due สองบรรทัดตรงตามโจทย์", "ตรวจเอง: ไม่มี instanceof หรือ getClass ใน loanablesDue"],
    solutionNotes: ["isLoanable อยู่ใน interface ทุกชนิดจึงได้กติกาเดียวกันโดยไม่ต้องเขียนซ้ำ"],
    reflection: ["มี switch/if ตามชนิดในโค้ดที่เคยเขียนไหม ย้ายเป็น polymorphism ได้อย่างไร"],
    extension: "เปลี่ยน BorrowGate ในบท interfaces ให้รับ List<LoanRule> แล้วคืนเหตุผลแรกที่ไม่ผ่าน",
  },
  "oop-inheritance": {
    hook: "StudentMember เหมือน Member ทุกอย่าง ยกเว้นโควตาและข้อความแสดงผล การ copy ทั้ง class มาแก้ทำให้บั๊กต้องแก้สองที่ inheritance แชร์ส่วนที่เหมือนกันได้ — ถ้าใช้ถูกที่",
    analogy: {
      title: "subclass เหมือนบัตรสมาชิกประเภทพิเศษ",
      text: ["บัตรนักเรียนเป็นบัตรสมาชิกห้องสมุดที่ทุกเคาน์เตอร์รับได้ แค่มีสิทธิ์เพิ่ม เคาน์เตอร์ไม่ต้องมีขั้นตอนพิเศษสำหรับบัตรนักเรียน", "ถ้าบัตรแบบใหม่ “ยืมไม่ได้” ทั้งที่เป็นบัตรสมาชิก เคาน์เตอร์จะเจอเซอร์ไพรส์ — นั่นคือสัญญาณว่าไม่ใช่ is-a"],
      mapping: [["บัตรสมาชิกทั่วไป", "superclass Member"], ["บัตรนักเรียน", "subclass StudentMember"], ["สิทธิ์ที่ต่างไป", "method ที่ override"], ["ทุกเคาน์เตอร์รับได้", "Liskov substitution"]],
      limits: "บัตรจริงเพิ่มสิทธิ์ได้อิสระ แต่ใน Java subclass extends ได้ class เดียว และการเปลี่ยน superclass กระทบ subclass ทุกตัว (fragile base class) จึงใช้ inheritance เมื่อความสัมพันธ์มั่นคงจริง",
    },
    explain: [
      { heading: "1) extends และ super(...)", text: ["subclass ได้สมาชิกที่ไม่ private ของ superclass", "constructor ต้องเรียก super(...) เป็นบรรทัดแรก"] },
      { heading: "2) override", text: ["signature เดียวกัน + @Override", "super.describe() เรียกของเดิมแล้วต่อเติม"] },
      { heading: "3) ใช้เมื่อเป็น is-a จริง", text: ["subclass ต้องแทน superclass ได้โดยไม่เซอร์ไพรส์", "ถ้าแค่อยากได้โค้ดซ้ำ ใช้ composition"] },
    ],
    walkthrough: ["Sea เป็น Member ใช้ค่าเริ่มต้นทั้งหมด", "Ton เป็น StudentMember: maxLoans และ describe มาจาก subclass loanDays มาจาก Member", "loop เรียกผ่านชนิด Member ได้พฤติกรรมของแต่ละคน"],
    pitfalls: ["ลืม super(...)", "ไม่ใส่ @Override แล้ว signature ผิด", "subclass ปฏิเสธพฤติกรรมของแม่", "ใช้ protected field แทน method"],
    checks: [
      { question: "ทำไม StaffMember ไม่ควร override borrow ให้ throw เสมอ (เช่นเจ้าหน้าที่ใช้ระบบอื่น)", answer: "โค้ดที่ทำงานกับ Member จะพังเมื่อได้ StaffMember ผิดหลัก Liskov ควรออกแบบใหม่ เช่นไม่ให้ StaffMember เป็น Member" },
      { question: "private field ของ Member ใช้ใน StudentMember ได้ไหม", answer: "ไม่ได้โดยตรง ต้องผ่าน method ของ Member เช่น name() หรือ super.describe()" },
    ],
    recap: ["extends + super(...)", "@Override + super.method()", "is-a จริงและแทนกันได้"],
    traceHint: "สำหรับแต่ละ method ที่เรียก หาว่า class จริงของ object มี override ไหม ถ้าไม่มีให้ขึ้นไปหาที่ superclass",
    practiceHints: ["StaffMember เรียก super(name) แล้วเก็บ department", "override maxLoans, loanDays และ describe (เรียก super.describe())", "dueSummary ใช้แค่ method ของ Member"],
    acceptance: [local, "ตรวจเอง: สามบรรทัดตรงตามโจทย์ Fon ยืมได้ถึงวันที่ 29", "ตรวจเอง: ไม่มี instanceof ใน dueSummary"],
    solutionNotes: ["loanDays ของ StudentMember ไม่ได้ override จึงใช้ 14 ของ Member"],
    reflection: ["ถ้าโควตาเปลี่ยนตามวัน (เช่นช่วงสอบนักเรียนยืมได้มากขึ้น) inheritance ยังเหมาะไหม หรือควรใช้ interface กับ composition"],
    extension: "ลองออกแบบใหม่ด้วย composition: Member มี MembershipType (interface) ที่บอก maxLoans/loanDays แล้วเทียบกับ inheritance",
  },
  "oop-abstract": {
    hook: "จดหมายแจ้งเตือนสามแบบของห้องสมุดมีคำขึ้นต้นและลงท้ายเหมือนกัน แต่เขียนซ้ำในสาม class วันที่ต้องเปลี่ยนคำลงท้าย ซีแก้ครบแค่สองที่",
    explain: [
      { heading: "1) abstract class", text: ["มี state, constructor และ method ปกติได้ พร้อม abstract method ที่ subclass ต้องเขียน", "new ตรง ๆ ไม่ได้"] },
      { heading: "2) template method", text: ["final render() กำหนดลำดับ: หัว → body() → ท้าย", "subclass เติมแค่ body() ลำดับเปลี่ยนไม่ได้"] },
      { heading: "3) interface หรือ abstract class", text: ["interface: สัญญาความสามารถ หลาย class ที่ไม่เกี่ยวกันใช้ได้", "abstract class: ครอบครัวเดียวกันที่แชร์ state/ขั้นตอน และ extends ได้ตัวเดียว"] },
    ],
    walkthrough: ["Knight และ Slime เป็น Fighter ที่ต่างกันแค่ attackPower", "attack เป็น final: ทำความเสียหาย แล้วรายงาน hp ของเป้าหมาย", "hp ไม่ต่ำกว่า 0 เพราะ takeDamage ใช้ Math.max"],
    pitfalls: ["new abstract class", "ไม่ใส่ final ให้ template method", "ใส่ logic ร่วมซ้ำใน subclass", "abstract class ที่ไม่มีอะไรร่วมจริง (ควรเป็น interface)"],
    checks: [
      { question: "abstract class มี constructor ได้ไหม ทั้งที่ new ไม่ได้", answer: "ได้ subclass เรียกผ่าน super(...) เพื่อตั้งค่าและตรวจ state ร่วม" },
      { question: "ทำไม body() เป็น protected", answer: "เป็นส่วนเติมของ subclass ไม่ใช่ API ให้ผู้อื่นเรียก ผู้ใช้ควรเรียก render() เท่านั้น" },
    ],
    recap: ["abstract class = ฐานร่วม + ส่วนที่บังคับเติม", "template method เป็น final", "interface สำหรับสัญญา abstract class สำหรับครอบครัว"],
    traceHint: "ไล่ attack ทีละบรรทัดว่าเรียก attackPower ของ class ไหน และ hp ของใครเปลี่ยน",
    practiceHints: ["Notice เก็บชื่อและตรวจใน constructor protected", "render เป็น final ประกอบสามบรรทัดด้วย \\n", "subclass เรียก super(name) และเขียน body()"],
    acceptance: [local, "ตรวจเอง: หกบรรทัดตรงตามโจทย์ (ค่าปรับ 15 บาท)", "ตรวจเอง: render เป็น final และ body เป็น abstract"],
    solutionNotes: ["เปลี่ยนคำลงท้ายแก้ที่ render ที่เดียว ทุกจดหมายเปลี่ยนตาม"],
    reflection: ["มีโค้ดที่เคยเขียนซ้ำโครงเดียวกันหลายที่ไหม template method ช่วยได้หรือไม่"],
    extension: "เพิ่ม ReservationReadyNotice และ method static Notice of(String kind, ...) ที่เลือกชนิดจากชื่อ",
  },
  "oop-project-rpg": {
    hook: "เกมต่อสู้เป็นที่ที่ design พังเห็นชัด: ถ้าการเพิ่มอาวุธใหม่ต้องแก้ battle loop แปลว่า polymorphism ยังไม่ทำงาน โปรเจกต์นี้ใช้ interface, abstract class และ composition ร่วมกันในเกมที่ผลแน่นอนจนทดสอบด้วยไฟล์ได้",
    explain: [
      { heading: "1) Weapon เป็น strategy", text: ["Hero มี Weapon เปลี่ยนอาวุธคือเปลี่ยน object ไม่ใช่สร้าง subclass HeroWithBow", "damage(round) ทำให้อาวุธมีพฤติกรรมตามรอบได้"] },
      { heading: "2) Battle รู้จักแค่ Fighter", text: ["ใครตีใครเรียก attackDamage(round) ผ่าน abstract class", "ตรวจ isAlive ทันทีหลังทุกการโจมตี"] },
      { heading: "3) ผลแน่นอน = ทดสอบได้", text: ["ไม่ใช้ Random ผลจึงเขียน expected-output ได้", "ถ้าต้องสุ่มภายหลัง ให้ส่ง Random ที่กำหนด seed เข้าไป"] },
    ],
    walkthrough: ["sword ทำ 7 ทุกรอบ", "bow ทำ 10 รอบแรกแล้ว 5", "staff เพิ่มตามรอบ 5, 6, 7"],
    pitfalls: ["ตรวจการตายแค่ต้นรอบ", "สร้าง subclass ตามคู่ hero+weapon", "Battle รู้จักชนิดอาวุธ", "ใช้ Random ที่ทดสอบไม่ได้"],
    checks: [
      { question: "การเพิ่ม dagger ต้องแก้ Battle ไหม", answer: "ไม่ต้อง เพิ่ม class Dagger และเพิ่มกิ่งใน Weapons.byName เท่านั้น" },
      { question: "ทำไมมอนสเตอร์ที่ hp เป็น 0 ไม่ตีกลับในรอบนั้น", answer: "Battle ตรวจ isAlive ของผู้ถูกโจมตีทันทีหลังการตีแต่ละครั้ง และจบการต่อสู้ก่อนถึงตาของมอนสเตอร์" },
    ],
    recap: ["Weapon interface + composition ใน Hero", "abstract Fighter + Battle ผ่าน polymorphism", "ไม่สุ่ม → fixture ได้"],
    traceHint: "ทำตาราง round, damage ของฮีโร่, hp มอนสเตอร์, damage ของมอนสเตอร์, hp ฮีโร่ แล้วหยุดทันทีที่ hp ใดเป็น 0",
    practiceHints: ["เริ่มจาก Weapon และอาวุธสามแบบ ทดสอบ damage ของรอบ 1–3", "Fighter มี takeDamage แบบไม่ต่ำกว่า 0 Hero ส่งต่อให้ weapon Monster คืนค่าคงที่", "Battle.run วน 50 รอบ ตรวจ isAlive หลังทุกการตี และ Main นำฝ่ายแพ้ออก"],
    acceptance: [local, "ตรวจเอง: test-input ของเฉลยได้ผลตรง expected-output ทุกบรรทัด (รวม Golem wins)", "ตรวจเอง: การเพิ่ม dagger ไม่ได้แก้ Battle หรือ Fighter"],
    solutionNotes: ["Main ถือ hero และ monster เป็น field แล้วล้างฝ่ายที่แพ้ ทำให้ fight ซ้ำได้ need a hero and a monster", "Weapons.byName เป็นที่เดียวที่แปลงชื่อเป็น object (factory)", "เพดาน 50 รอบ (draw) เกิดไม่ได้ตามข้อกำหนดปัจจุบัน แต่กัน loop ไม่จบหากภายหลังมีมอนสเตอร์ที่โจมตี 0 หรือการฟื้น hp"],
    reflection: ["ถ้าเพิ่มสกิลพิเศษให้ฮีโร่ (เช่นฟื้น hp) จะเพิ่มเป็น interface ใหม่หรือ method ใน Fighter"],
    extension: "เพิ่มเกราะ (interface Armor ที่ลดความเสียหาย) ให้ Hero โดย Battle ไม่ต้องเปลี่ยน",
  },
  "oop-collections": {
    hook: "การหาหนังสือด้วย loop ใช้ได้กับสิบเล่ม แต่คำถามอย่าง “ใครยืมบ่อยที่สุด” หรือ “มีกี่หมวดไม่ซ้ำ” ทำให้โค้ดเต็มไปด้วย if และตัวนับ โครงสร้างข้อมูลที่ถูกตอบคำถามเหล่านี้ได้ในไม่กี่บรรทัด",
    explain: [
      { heading: "1) เลือกตามคำถาม", text: ["ต้องการลำดับ/ซ้ำได้ → List, ห้ามซ้ำ → Set, ค้นด้วย key → Map", "ลำดับ: Hash ไม่รับประกัน, Linked คงลำดับที่ใส่, Tree เรียงตาม key"] },
      { heading: "2) Map ที่ใช้บ่อย", text: ["merge(key, 1, Integer::sum) นับ", "computeIfAbsent(key, k -> new ...) สร้างค่าเริ่มต้นแล้วใช้ต่อ", "getOrDefault เมื่อ key อาจไม่มี"] },
      { heading: "3) เรียง", text: ["Comparator.comparing(Book::category).thenComparing(Book::title)", "reversed() กลับลำดับ list.sort เรียงในที่"] },
    ],
    walkthrough: ["byId ค้นด้วย id ได้ทันที get ของ key ที่ไม่มีได้ null", "TreeSet เรียงหมวด LinkedHashMap นับตามลำดับที่พบ", "sort ตามหมวดแล้วชื่อ", "TreeMap เรียง key อัตโนมัติ"],
    pitfalls: ["คาดหวังลำดับจาก HashMap", "ใช้ object ที่ไม่มี equals/hashCode เป็น key", "get แล้วใช้ค่าโดยไม่ตรวจ null", "แก้ collection ระหว่างวน"],
    checks: [
      { question: "ถ้าต้องการนับแล้วแสดงตามลำดับที่พบครั้งแรก ใช้ Map แบบไหน", answer: "LinkedHashMap" },
      { question: "Integer::sum ใน merge ทำอะไร", answer: "เป็น method reference ของ (a, b) -> a + b ใช้รวมค่าเดิมกับ 1 ที่ส่งเข้าไป" },
    ],
    recap: ["List / Set / Map ตามคำถาม", "Hash / Linked / Tree ตามลำดับที่ต้องการ", "merge, computeIfAbsent, Comparator"],
    traceHint: "เขียนสถานะของแต่ละ Map/Set หลังแต่ละรายการใน log",
    practiceHints: ["split(\":\") ได้ชื่อกับหนังสือ", "TreeMap + merge สำหรับการนับ TreeSet สำหรับชื่อไม่ซ้ำ", "หาค่าสูงสุดโดยวน entrySet ของ TreeMap (ชื่อเรียงแล้ว ใช้ > เพื่อให้ตัวแรกชนะเมื่อเท่ากัน)"],
    acceptance: [local, "ตรวจเอง: สี่บรรทัดตรงตามโจทย์"],
    solutionNotes: ["เพราะ perTitle เป็น TreeMap การวนจึงเรียงตามชื่อ และการใช้ > ทำให้ชื่อที่มาก่อนชนะเมื่อจำนวนเท่ากัน"],
    reflection: ["คำถามไหนใน Library M2 ที่จะง่ายขึ้นถ้าเก็บหนังสือใน Map<Integer, Book>"],
    extension: "แปลง Library M2 ให้เก็บหนังสือและสมาชิกใน LinkedHashMap ตาม id แล้วตรวจว่า golden master ยังผ่าน",
  },
  "oop-exceptions": {
    hook: "โค้ดหนึ่งที่ตรวจว่า e.getMessage().equals(\"already borrowed\") พังเงียบ ๆ เมื่อมีคนแก้ข้อความเป็นภาษาไทย exception ที่มีชนิดของตัวเองให้ตรวจด้วยชนิดแทนข้อความ",
    explain: [
      { heading: "1) checked vs unchecked", text: ["checked ต้องจับหรือ throws: ปัญหาภายนอกที่คาดได้ เช่น IOException", "unchecked (RuntimeException): ผิดกติกาหรือบั๊ก"] },
      { heading: "2) exception ของโดเมน", text: ["LibraryException และ subclass ที่ชื่อบอกปัญหา", "จับที่ขอบระบบที่เดียว แปลงเป็นข้อความ"] },
      { heading: "3) cause และ try-with-resources", text: ["ห่อด้วย new X(message, cause) เพื่อเก็บต้นเหตุ", "try (Reader r = ...) ปิด resource แม้มี exception"] },
    ],
    walkthrough: ["รายชื่อปกติอ่านได้สองเล่ม ข้ามบรรทัดว่าง", "บรรทัด #broken ทำให้เกิด IOException ถูกห่อเป็น LibraryDataException พร้อม cause", "LoanLimitException ถูกจับด้วยชนิดแม่ LibraryException"],
    pitfalls: ["catch (Exception e) {} ว่าง", "ห่อ exception โดยทิ้ง cause", "ตรวจข้อความแทนชนิด", "ประกาศ throws Exception กว้างเกิน"],
    checks: [
      { question: "ทำไม LibraryException เป็น unchecked", answer: "เป็นการผิดกติกาของโดเมนที่ CLI จัดการที่ขอบระบบ ไม่ต้องบังคับทุก method ระหว่างทางให้ประกาศ throws" },
      { question: "ทำไม LibraryStore.load ใน M3 ประกาศ throws IOException", answer: "ไฟล์อาจอ่านไม่ได้ด้วยเหตุภายนอก ผู้เรียก (CLI) ควรตัดสินใจว่าจะแจ้งผู้ใช้อย่างไร" },
    ],
    recap: ["checked = ภายนอกที่คาดได้; unchecked = กติกา/บั๊ก", "ชนิดของโดเมน + จับที่ขอบ", "cause + try-with-resources"],
    traceHint: "ไล่ว่า exception แต่ละตัวถูกสร้างที่ไหน ถูกห่อหรือไม่ และ catch ไหนรับ",
    practiceHints: ["LibraryException extends RuntimeException มี constructor รับข้อความ", "subclass สร้างข้อความจาก id ใน constructor", "main จับ LibraryException ครั้งเดียวใน loop แล้วพิมพ์ getSimpleName()"],
    acceptance: [local, "ตรวจเอง: สี่บรรทัดตรงตามโจทย์"],
    solutionNotes: ["Map.get คืน null สำหรับ id ที่ไม่มี จึงแยกกรณีไม่พบออกจากกรณีถูกยืมได้"],
    reflection: ["exception ไหนของ Library M2 ที่ควรมีชนิดของตัวเอง"],
    extension: "แปลง Library M2 ให้ throw exception ของโดเมนแทน IllegalStateException แล้วตรวจว่า golden master ยังผ่าน",
  },
  "oop-refactor-main": {
    hook: "โปรแกรมติดตามการอ่านมี main ยาวร้อยบรรทัดที่ทำงานถูกต้อง ทุกคนกลัวแตะเพราะไม่รู้ว่าอะไรจะพัง golden master ทำให้กล้าแก้ เพราะรู้ทันทีถ้าพฤติกรรมเปลี่ยน",
    analogy: {
      title: "refactor เหมือนย้ายบ้านแบบถ่ายรูปไว้ก่อน",
      text: ["ก่อนย้าย ถ่ายรูปทุกห้องไว้ หลังจัดของในบ้านใหม่ก็เทียบกับรูปว่าครบทุกชิ้น", "golden master คือรูปถ่ายของ output: หลังจัดโค้ดใหม่ ผลต้องเหมือนรูปทุกบรรทัด"],
      mapping: [["รูปถ่ายก่อนย้าย", "expected-output.txt จากโปรแกรมเดิม"], ["รายการห้องที่ถ่าย", "test-input.txt ที่ครอบคลุมทุกเส้นทาง"], ["ย้ายทีละห้อง", "refactor ทีละขั้นเล็ก"], ["เทียบกับรูป", "diff หลังทุกขั้น"]],
      limits: "รูปถ่ายเห็นเฉพาะห้องที่ถ่าย golden master ก็จับได้เฉพาะเส้นทางที่ test-input ครอบคลุม เส้นทางที่ไม่มีใน input อาจเปลี่ยนโดยไม่มีใครรู้",
    },
    explain: [
      { heading: "1) จับพฤติกรรมก่อน", text: ["รันโปรแกรมเดิมกับ input ที่ครอบคลุม เก็บผลไว้", "พฤติกรรมแปลก ๆ ให้คงไว้ก่อน แก้ทีหลังแยกต่างหาก"] },
      { heading: "2) ทีละขั้นเล็ก", text: ["ย้าย state → class โดเมน, ย้ายการแปลงคำสั่ง → handler, main เหลือ I/O", "compile และ diff หลังทุกขั้น"] },
      { heading: "3) code smell", text: ["method ยาว, if ตามคำสั่ง, ตัวแปรที่ต้องแก้คู่กัน, logic ปน System.out", "แต่ละ smell ชี้ว่าควรแยกอะไรออก"] },
    ],
    walkthrough: ["legacy กับ refactored รับ input เดียวกัน", "ทั้งคู่ได้ [logged 120, logged 80, total 200, ?]", "เทียบ list ได้ same output: true"],
    pitfalls: ["แก้บั๊กพร้อม refactor", "ขั้นใหญ่จนหาไม่เจอว่าพังตรงไหน", "test-input ไม่ครอบคลุมกรณีขอบ (เช่นจำนวนเท่ากัน)", "เปลี่ยนข้อความเพราะ “ดูดีกว่า”"],
    checks: [
      { question: "ทำไม test-input ต้องมีหนังสือสองเล่มที่จำนวนหน้าเท่ากัน", answer: "เพื่อจับพฤติกรรมการเลือก top เมื่อเท่ากัน (ตัวแรกชนะ) ซึ่งเปลี่ยนได้ง่ายระหว่าง refactor" },
      { question: "ReadingLog ควรมี System.out ไหม", answer: "ไม่ควร ให้คืนค่าเพื่อทดสอบได้ และให้ Main เป็นที่เดียวที่พิมพ์" },
    ],
    recap: ["golden master ก่อนแตะโค้ด", "ทีละขั้น + diff ทุกครั้ง", "แก้บั๊กแยกจาก refactor"],
    traceHint: "เทียบ legacy กับ refactored ทีละบรรทัดของ input ว่ากิ่งไหนของแต่ละเวอร์ชันทำงาน",
    practiceHints: ["รัน starter กับ test-input ของเฉลยแล้ว diff กับ expected-output ก่อนเริ่ม", "ย้ายรายการอ่านและ goal ไป ReadingLog ก่อน แล้ว diff", "สร้าง CommandHandler ที่คืนข้อความ (null เมื่อไม่ต้องพิมพ์) แล้ว Main แค่วนอ่าน"],
    acceptance: [local, "ตรวจเอง: starter และเฉลยให้ผลตรงกับ expected-output ทุกบรรทัด และเมื่อเปลี่ยน > เป็น >= ใน top ผลบรรทัด top: Clean Code (120) จะเปลี่ยน", "ตรวจเอง: ReadingLog ไม่มี System.out และ Main ไม่มีกติกา"],
    solutionNotes: ["ReadingLog.read throw IllegalArgumentException แต่ข้อความเหมือนโปรแกรมเดิม handler จึงแปลงกลับได้ตรง", "top ใช้ > เพื่อคงพฤติกรรม “ตัวแรกชนะเมื่อเท่ากัน”"],
    reflection: ["ในโค้ดที่เคยเขียน ส่วนไหนที่อยาก refactor และ golden master ของมันควรมีอะไรบ้าง"],
    extension: "หลัง refactor ผ่าน ให้ทำให้ TOTAL (ตัวพิมพ์ใหญ่) ใช้ได้ แล้วอัปเดต expected-output เป็นการเปลี่ยนพฤติกรรมที่ตั้งใจหนึ่งขั้น",
  },
  "oop-junit": {
    hook: "golden master บอกว่ามีอะไรเปลี่ยน แต่ไม่บอกว่ากติกาไหนพัง unit test ที่ตั้งชื่อตามพฤติกรรมชี้ตรงไปที่กติกาที่เสีย",
    explain: [
      { heading: "1) โครงของ test", text: ["@Test บน method, @BeforeEach สร้าง object ใหม่ทุกครั้ง", "assertEquals(expected, actual), assertThrows(Type.class, () -> ...)"] },
      { heading: "2) test ที่ดี", text: ["ชื่อบอกพฤติกรรม", "arrange–act–assert ตรวจทั้งผลและ state ที่สำคัญ", "ไม่พึ่งลำดับหรือ test อื่น"] },
      { heading: "3) รันโดยไม่มี build tool", text: ["javac -cp junit-platform-console-standalone-6.1.3.jar -d out *.java", "java -jar junit-platform-console-standalone-6.1.3.jar execute --class-path out --scan-class-path"] },
    ],
    walkthrough: ["setUp สร้าง FineCalculator ใหม่ก่อนทุก test", "สาม test ตรวจ 0, 15, 100", "test ติดลบตรวจทั้งชนิดและข้อความของ exception"],
    pitfalls: ["สลับลำดับ expected กับ actual", "test ที่ไม่มี assert", "ลืม import static assertions", "test หลายพฤติกรรมในตัวเดียว"],
    checks: [
      { question: "ทำไม @BeforeEach ดีกว่าสร้าง Library เป็น field static ครั้งเดียว", answer: "แต่ละ test ได้ state ใหม่ ไม่มีผลค้างจาก test ก่อน และรันลำดับใดก็ได้ผลเดิม" },
      { question: "พิสูจน์ได้อย่างไรว่า test มีค่า", answer: "แก้โค้ดให้ผิดชั่วคราว (เช่น MAX_LOANS = 3) แล้วต้องเห็น test ที่เกี่ยวข้องล้ม" },
    ],
    recap: ["@Test, @BeforeEach, assertEquals, assertThrows", "ชื่อตามพฤติกรรม + AAA", "console launcher เมื่อไม่มี build tool"],
    traceHint: "สำหรับแต่ละ test เขียนสามบรรทัด: เตรียม / ทำ / คาดหวัง แล้วตรวจว่า assert ตรงบรรทัดที่สาม",
    practiceHints: ["setUp สร้าง Library, หนังสือหนึ่งเล่ม และสมาชิกหนึ่งคน", "ใช้ assertThrows แล้วตรวจ getMessage() ของ exception ที่ได้", "ทดสอบค่าปรับด้วย setDay(20) แล้ว giveBack"],
    acceptance: [localJunit, "ตรวจเอง: test อย่างน้อย 6 ตัวผ่านทั้งหมด", "ตรวจเอง: เปลี่ยน MAX_LOANS เป็น 3 ชั่วคราวแล้ว test โควตาล้ม"],
    solutionNotes: ["test โควตาตรวจทั้ง exception และ loansCount ว่ายังเป็น 2 (กติกาไม่ได้เปลี่ยน state เมื่อถูกปฏิเสธ)"],
    reflection: ["กติกาไหนของ Library ที่ยังไม่มี test และกลัวพังที่สุด"],
    extension: "ใช้ @ParameterizedTest กับ @CsvSource (อยู่ใน junit-platform-console-standalone แล้ว) ทดสอบค่าปรับหลายกรณีใน test เดียว",
  },
  "oop-project-library-3": {
    hook: "ห้องสมุดใช้ M2 ได้ทั้งวัน แต่ปิดโปรแกรมแล้วทุกอย่างหาย capstone นี้ทำให้ข้อมูลอยู่รอด โดยไม่ทำให้กติกาที่สร้างมาตลอดคอร์สอ่อนลงเมื่อโหลดไฟล์ที่อาจเสีย",
    explain: [
      { heading: "1) แยกการตีความออกจากไฟล์", text: ["Library.snapshot() / restore(List<String>) ไม่รู้จักไฟล์ test ได้ในหน่วยความจำ", "LibraryStore เป็นที่เดียวที่ใช้ Files"] },
      { heading: "2) โหลดผ่านกติกาเดิม", text: ["restore สร้างด้วย constructor และ attach/addLoan เดิม ไฟล์เสียจึงสร้าง Library ผิดรูปไม่ได้", "บรรทัดผิดได้ LibraryDataException พร้อมเลขบรรทัดและ cause"] },
      { heading: "3) test ด้วย @TempDir", text: ["JUnit สร้างโฟลเดอร์ชั่วคราวให้และลบให้", "ทดสอบ round trip, id ต่อเนื่อง, ไฟล์หาย, ไฟล์เสีย และคำสั่ง CLI"] },
    ],
    walkthrough: ["example เขียนสองบรรทัดเป็น UTF-8 ลงไฟล์ใน @TempDir", "อ่านกลับแล้วแยกด้วย tab ได้ชื่อภาษาไทยถูกต้อง", "Files.exists บอกว่าไฟล์ไม่มีก่อนพยายามอ่าน"],
    pitfalls: ["restore ที่ข้ามกติกา (ตั้ง field ตรง ๆ)", "ไม่ตั้ง nextId ต่อจากค่าสูงสุด", "ข้อความ error ไม่บอกบรรทัด", "test ที่เขียนไฟล์ลงโฟลเดอร์จริง"],
    checks: [
      { question: "ทำไมชื่อหนังสือห้ามมี tab", answer: "tab คือตัวคั่น field ในไฟล์ ชื่อที่มี tab จะทำให้อ่านกลับผิด จึงปฏิเสธตั้งแต่สร้าง" },
      { question: "ไฟล์ที่มี loan อ้างหนังสือ #9 ที่ไม่มีควรเกิดอะไร", answer: "LibraryDataException ข้อความ line N: no such book และไม่ได้ Library ที่ข้อมูลไม่ครบ" },
    ],
    recap: ["snapshot/restore ไม่รู้จักไฟล์; LibraryStore รู้จัก", "โหลดผ่านกติกาเดิม + เลขบรรทัด", "@TempDir + golden master เดิม"],
    traceHint: "เขียน snapshot ของ sample() ทีละบรรทัด แล้วไล่ restore ว่าแต่ละบรรทัดเรียก constructor/method ไหน",
    practiceHints: ["เริ่มจาก snapshot ใน Library แล้วเขียน test round trip ก่อนเขียนไฟล์จริง", "restore แยกบรรทัดด้วย split(\"\\t\", -1) ตรวจจำนวน field แล้วใช้ constructor และ attach/addLoan เดิม ห่อ error พร้อมเลขบรรทัด", "LibraryStore ใช้ Files.write/readAllLines และ Main เพิ่ม save/load แล้วรัน golden master ของ M2 ซ้ำ"],
    acceptance: [localJunit, "ตรวจเอง: JUnit 11 test ผ่าน", "ตรวจเอง: golden master ของ M2 ยังผ่านกับ M3 (java -cp out library.cli.Main < test-input.txt)", "ตรวจเอง: ลบบรรทัดที่ตั้ง nextBookId ใน restore ชั่วคราวแล้ว test idsContinueAfterLoad ล้ม"],
    solutionNotes: ["split(\"\\t\", -1) เก็บ field ว่างท้ายบรรทัดไว้ การนับ field จึงจับบรรทัดที่ขาดได้", "ข้อความของ NumberFormatException ถูกต่อหลัง line N: ใน test จึงตรวจข้อความเต็มได้แน่นอน"],
    reflection: ["หลังจบคอร์ส การตัดสินใจออกแบบไหนที่ทำให้ M3 ง่ายที่สุด และไหนที่อยากทำต่างออกไป"],
    extension: "เพิ่มการบันทึกอัตโนมัติหลังทุกคำสั่งที่เปลี่ยนข้อมูล โดยเขียนลงไฟล์ชั่วคราวแล้ว Files.move ทับไฟล์จริง (atomic move) เพื่อไม่ให้ไฟล์เสียเมื่อโปรแกรมล่มกลางการเขียน",
  },
};
